-- ============================================================================
-- LinguaLoop Live Database Schema
-- Extracted from live Supabase instance via MCP tools
-- Date: 2026-03-18
--
-- Sources:
--   1. Supabase MCP list_tables (verbose) — all table structures
--   2. Supabase MCP execute_sql — all plpgsql/sql function definitions
--   3. Supabase MCP execute_sql — CHECK constraints, triggers, indexes
--
-- This file reflects the ACTUAL live database state as of 2026-03-18.
-- ============================================================================

-- ============================================================================
-- Extensions
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS vector;       -- pgvector for topic embeddings
CREATE EXTENSION IF NOT EXISTS pgcrypto;     -- gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS intarray;     -- integer array operators (& for intersection)

-- ============================================================================
-- ENUMs
-- ============================================================================

DO $$ BEGIN
    CREATE TYPE exercise_source_type AS ENUM ('grammar', 'vocabulary', 'collocation');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

-- ============================================================================
-- Tier 0: Dimension / Reference Tables (no foreign key dependencies)
-- ============================================================================

-- ---------------------------------------------------------------------------
-- dim_status
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.dim_status (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_code     text NOT NULL UNIQUE,
    status_name     text NOT NULL,
    description     text,
    is_active       boolean DEFAULT true,
    created_at      timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- dim_languages
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.dim_languages (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language_code           text NOT NULL UNIQUE,
    language_name           text NOT NULL,
    native_name             text,
    iso_639_1               text,
    iso_639_3               text,
    is_active               boolean DEFAULT true,
    display_order           integer DEFAULT 0,
    created_at              timestamptz DEFAULT now(),
    updated_at              timestamptz DEFAULT now(),
    prose_model             varchar(100) DEFAULT 'google/gemini-2.5-flash-lite',
    question_model          varchar(100) DEFAULT 'google/gemini-2.5-flash-lite',
    tts_voice_ids           jsonb DEFAULT '["alloy","echo","fable","onyx","nova","shimmer"]',
    tts_speed               real DEFAULT 1.0,
    grammar_check_enabled   boolean DEFAULT true,
    exercise_model          text,
    exercise_sentence_model text
);

-- ---------------------------------------------------------------------------
-- dim_subscription_tiers
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.dim_subscription_tiers (
    id                          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tier_code                   text NOT NULL UNIQUE,
    tier_name                   text NOT NULL,
    display_name                text NOT NULL,
    description                 text,
    daily_free_tests            integer NOT NULL DEFAULT 0 CHECK (daily_free_tests >= 0),
    monthly_token_grant         integer NOT NULL DEFAULT 0 CHECK (monthly_token_grant >= 0),
    tokens_per_test             integer NOT NULL DEFAULT 10 CHECK (tokens_per_test >= 0),
    can_generate_tests          boolean DEFAULT false,
    can_create_custom_tests     boolean DEFAULT false,
    can_access_analytics        boolean DEFAULT false,
    max_custom_tests            integer DEFAULT 0 CHECK (max_custom_tests >= 0),
    is_admin                    boolean DEFAULT false,
    is_moderator                boolean DEFAULT false,
    is_active                   boolean DEFAULT true,
    display_order               integer DEFAULT 0,
    created_at                  timestamptz DEFAULT now(),
    updated_at                  timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- dim_cefr_levels
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.dim_cefr_levels (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cefr_code       text NOT NULL UNIQUE,
    difficulty_min  integer NOT NULL,
    difficulty_max  integer NOT NULL,
    word_count_min  integer NOT NULL,
    word_count_max  integer NOT NULL,
    initial_elo     integer NOT NULL,
    description     text,
    created_at      timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- dim_lens
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.dim_lens (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lens_code       text NOT NULL UNIQUE,
    display_name    text NOT NULL,
    description     text,
    prompt_hint     text,
    is_active       boolean DEFAULT true,
    sort_order      integer DEFAULT 0,
    created_at      timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- dim_test_types
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.dim_test_types (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_code       text NOT NULL UNIQUE,
    type_name       text NOT NULL,
    description     text,
    category        text,
    requires_audio  boolean DEFAULT false,
    is_active       boolean DEFAULT true,
    display_order   integer DEFAULT 0,
    created_at      timestamptz DEFAULT now(),
    updated_at      timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- dim_question_types
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.dim_question_types (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_code       text NOT NULL UNIQUE,
    type_name       text NOT NULL,
    description     text,
    cognitive_level integer NOT NULL CHECK (cognitive_level >= 1 AND cognitive_level <= 3),
    is_active       boolean DEFAULT true,
    display_order   integer DEFAULT 0,
    created_at      timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- test_generation_config
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.test_generation_config (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key      text NOT NULL UNIQUE,
    config_value    text NOT NULL,
    description     text,
    updated_at      timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- test_generation_runs
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.test_generation_runs (
    id                          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_date                    date NOT NULL DEFAULT CURRENT_DATE,
    queue_items_processed       integer DEFAULT 0,
    tests_generated             integer DEFAULT 0,
    tests_failed                integer DEFAULT 0,
    prose_api_calls             integer DEFAULT 0,
    question_api_calls          integer DEFAULT 0,
    audio_api_calls             integer DEFAULT 0,
    grammar_checks_performed    integer DEFAULT 0,
    total_cost_usd              real DEFAULT 0,
    execution_time_seconds      integer,
    error_message               text,
    created_at                  timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- app_error_logs
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.app_error_logs (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    error_type      text NOT NULL,
    error_message   text NOT NULL,
    url             text,
    user_id         uuid,
    metadata        jsonb,
    created_at      timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- users_backup
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.users_backup (
    id              uuid,
    email           text,
    created_at      timestamptz,
    updated_at      timestamptz,
    last_login      timestamptz,
    display_name    text,
    native_language text,
    target_languages jsonb,
    timezone        text,
    is_active       boolean,
    email_verified  boolean
);

-- ============================================================================
-- Tier 1: Depends on Tier 0 only
-- ============================================================================

-- ---------------------------------------------------------------------------
-- organizations
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.organizations (
    id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name                    text NOT NULL,
    slug                    text NOT NULL UNIQUE,
    subscription_tier_id    integer NOT NULL REFERENCES public.dim_subscription_tiers(id),
    max_users               integer,
    token_pool              integer DEFAULT 0 CHECK (token_pool >= 0),
    is_active               boolean DEFAULT true,
    created_at              timestamptz DEFAULT now(),
    updated_at              timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- categories
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.categories (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    text NOT NULL,
    description             text,
    status_id               integer DEFAULT 2 REFERENCES public.dim_status(id),
    target_language_id      integer REFERENCES public.dim_languages(id),
    cooldown_days           integer DEFAULT 7,
    last_used_at            timestamptz,
    total_topics_generated  integer DEFAULT 0,
    created_at              timestamptz DEFAULT now(),
    updated_at              timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- dim_vocabulary
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.dim_vocabulary (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language_id         integer NOT NULL REFERENCES public.dim_languages(id),
    lemma               text NOT NULL,
    phrase_type         text DEFAULT 'single_word',
    component_lemmas    text[],
    part_of_speech      text,
    frequency_rank      real,
    created_at          timestamptz DEFAULT now(),
    updated_at          timestamptz DEFAULT now(),
    level_tag           text
);

-- ---------------------------------------------------------------------------
-- dim_grammar_patterns
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.dim_grammar_patterns (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pattern_code            text NOT NULL UNIQUE,
    pattern_name            text NOT NULL,
    description             text NOT NULL,
    user_facing_description text NOT NULL,
    example_sentence        text NOT NULL,
    example_sentence_en     text,
    language_id             integer NOT NULL REFERENCES public.dim_languages(id),
    cefr_level              text NOT NULL CHECK (cefr_level IN ('A1','A2','B1','B2','C1','C2')),
    category                text NOT NULL CHECK (category IN (
                                'tense','aspect','voice','particles','word_order','modality',
                                'clause_structure','conjugation','honorifics','measure_words','complement'
                            )),
    is_active               boolean NOT NULL DEFAULT true,
    created_at              timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- question_type_distributions
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.question_type_distributions (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    difficulty          integer NOT NULL UNIQUE CHECK (difficulty >= 1 AND difficulty <= 9),
    question_type_1     text NOT NULL REFERENCES public.dim_question_types(type_code),
    question_type_2     text NOT NULL REFERENCES public.dim_question_types(type_code),
    question_type_3     text NOT NULL REFERENCES public.dim_question_types(type_code),
    question_type_4     text NOT NULL REFERENCES public.dim_question_types(type_code),
    question_type_5     text NOT NULL REFERENCES public.dim_question_types(type_code),
    created_at          timestamptz DEFAULT now(),
    updated_at          timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- prompt_templates
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.prompt_templates (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_name       text NOT NULL,
    template_text   text NOT NULL,
    version         integer DEFAULT 1,
    is_active       boolean DEFAULT true,
    description     text,
    created_at      timestamptz DEFAULT now(),
    updated_at      timestamptz DEFAULT now(),
    language_id     integer NOT NULL REFERENCES public.dim_languages(id),
    UNIQUE (task_name, language_id, version)
);

-- ---------------------------------------------------------------------------
-- corpus_sources
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.corpus_sources (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language_id     integer NOT NULL REFERENCES public.dim_languages(id),
    source_name     text NOT NULL,
    source_type     text,
    description     text,
    token_count     integer DEFAULT 0,
    is_active       boolean DEFAULT true,
    created_at      timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- collocation_packs
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.collocation_packs (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language_id     integer NOT NULL REFERENCES public.dim_languages(id),
    pack_name       text NOT NULL,
    description     text,
    pack_type       text,
    tags            text[],
    total_items     integer DEFAULT 0,
    difficulty_range text,
    is_public       boolean DEFAULT true,
    created_at      timestamptz DEFAULT now()
);

-- ============================================================================
-- Tier 2: Depends on Tier 0-1
-- ============================================================================

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.users (
    id                      uuid PRIMARY KEY,
    email                   text NOT NULL UNIQUE,
    display_name            text,
    email_verified          boolean DEFAULT false,
    total_tests_taken       integer DEFAULT 0,
    total_tests_generated   integer DEFAULT 0,
    last_activity_at        timestamptz,
    last_free_test_date     date DEFAULT (CURRENT_DATE - interval '1 day'),
    free_tests_used_today   integer DEFAULT 0,
    total_free_tests_used   integer DEFAULT 0,
    created_at              timestamptz DEFAULT now(),
    updated_at              timestamptz DEFAULT now(),
    last_login              timestamptz DEFAULT now(),
    subscription_tier_id    integer NOT NULL DEFAULT 1 REFERENCES public.dim_subscription_tiers(id),
    deleted_at              timestamptz,
    anonymized_at           timestamptz,
    organization_id         uuid REFERENCES public.organizations(id),
    CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);

-- ---------------------------------------------------------------------------
-- topics
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.topics (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    category_id         integer NOT NULL REFERENCES public.categories(id),
    concept_english     text NOT NULL,
    lens_id             integer NOT NULL REFERENCES public.dim_lens(id),
    keywords            text[],
    embedding           vector(1536),
    semantic_signature  text,
    created_at          timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- daily_test_loads
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.daily_test_loads (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             uuid NOT NULL REFERENCES public.users(id),
    language_id         integer NOT NULL REFERENCES public.dim_languages(id),
    load_date           date NOT NULL DEFAULT CURRENT_DATE,
    test_ids            jsonb NOT NULL,
    completed_test_ids  jsonb DEFAULT '[]',
    created_at          timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- corpus_collocations
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.corpus_collocations (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corpus_source_id    integer NOT NULL REFERENCES public.corpus_sources(id),
    language_id         integer NOT NULL REFERENCES public.dim_languages(id),
    collocation_text    text NOT NULL,
    n_gram_size         integer,
    pmi_score           double precision,
    log_likelihood      double precision,
    t_score             double precision,
    collocation_type    text,
    pos_pattern         text,
    created_at          timestamptz DEFAULT now()
);

-- ============================================================================
-- Tier 3: Depends on Tier 0-2
-- ============================================================================

-- ---------------------------------------------------------------------------
-- organization_members
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.organization_members (
    organization_id     uuid NOT NULL REFERENCES public.organizations(id),
    user_id             uuid NOT NULL REFERENCES public.users(id),
    role                text NOT NULL DEFAULT 'student' CHECK (role IN ('student','teacher','admin','owner')),
    joined_at           timestamptz DEFAULT now(),
    PRIMARY KEY (organization_id, user_id)
);

-- ---------------------------------------------------------------------------
-- dim_word_senses
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.dim_word_senses (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vocab_id                integer NOT NULL REFERENCES public.dim_vocabulary(id),
    definition_language_id  integer NOT NULL REFERENCES public.dim_languages(id),
    definition              text NOT NULL,
    pronunciation           text,
    example_sentence        text,
    usage_notes             text,
    sense_rank              integer NOT NULL DEFAULT 1,
    usage_frequency         text DEFAULT 'common' CHECK (usage_frequency IN ('common','uncommon','rare','archaic')),
    semantic_category       text,
    is_validated            boolean DEFAULT false,
    validated_by            uuid REFERENCES public.users(id),
    validation_notes        text,
    created_at              timestamptz DEFAULT now(),
    updated_at              timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- user_languages
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.user_languages (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         uuid NOT NULL REFERENCES public.users(id),
    total_tests_taken integer DEFAULT 0,
    last_test_date  date,
    created_at      timestamptz DEFAULT now(),
    updated_at      timestamptz DEFAULT now(),
    language_id     integer NOT NULL REFERENCES public.dim_languages(id),
    UNIQUE (user_id, language_id)
);

-- ---------------------------------------------------------------------------
-- user_tokens
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.user_tokens (
    user_id                         uuid PRIMARY KEY REFERENCES public.users(id),
    purchased_tokens                integer DEFAULT 0 CHECK (purchased_tokens >= 0),
    bonus_tokens                    integer DEFAULT 0 CHECK (bonus_tokens >= 0),
    total_tokens_earned             integer DEFAULT 0,
    total_tokens_spent              integer DEFAULT 0,
    total_tokens_purchased          integer DEFAULT 0,
    tokens_spent_tests              integer DEFAULT 0,
    tokens_spent_generation         integer DEFAULT 0,
    tokens_spent_premium_features   integer DEFAULT 0,
    referral_tokens_earned          integer DEFAULT 0,
    achievement_tokens_earned       integer DEFAULT 0,
    created_at                      timestamptz DEFAULT now(),
    updated_at                      timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- user_skill_ratings
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.user_skill_ratings (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         uuid NOT NULL REFERENCES public.users(id),
    elo_rating      integer DEFAULT 1200 CHECK (elo_rating >= 400 AND elo_rating <= 3000),
    tests_taken     integer DEFAULT 0 CHECK (tests_taken >= 0),
    last_test_date  date,
    created_at      timestamptz DEFAULT now(),
    updated_at      timestamptz DEFAULT now(),
    language_id     integer NOT NULL REFERENCES public.dim_languages(id),
    test_type_id    integer NOT NULL REFERENCES public.dim_test_types(id),
    UNIQUE (user_id, language_id, test_type_id)
);

-- ---------------------------------------------------------------------------
-- flagged_content
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.flagged_content (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id             uuid REFERENCES public.users(id),
    content_hash        text NOT NULL,
    content_type        text NOT NULL,
    flagged_categories  jsonb,
    created_at          timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- tests
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.tests (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    gen_user            uuid NOT NULL REFERENCES public.users(id),
    slug                text NOT NULL UNIQUE,
    difficulty          integer NOT NULL CHECK (difficulty >= 1 AND difficulty <= 9),
    style               text DEFAULT 'academic' CHECK (style IN ('academic','conversational','business','casual','technical')),
    tier                text NOT NULL DEFAULT 'free-tier' CHECK (tier IN ('free-tier','premium-tier','enterprise-tier')),
    title               text,
    transcript          text,
    audio_url           text,
    total_attempts      integer DEFAULT 0,
    is_active           boolean DEFAULT true,
    is_featured         boolean DEFAULT false,
    is_custom           boolean DEFAULT false,
    generation_model    text DEFAULT 'gpt-4.1-nano',
    audio_generated     boolean DEFAULT false,
    created_at          timestamptz DEFAULT now(),
    updated_at          timestamptz DEFAULT now(),
    language_id         integer NOT NULL REFERENCES public.dim_languages(id),
    organization_id     uuid REFERENCES public.organizations(id),
    topic_id            uuid REFERENCES public.topics(id),
    vocab_sense_ids     integer[] DEFAULT '{}',
    vocab_sense_stats   jsonb DEFAULT '{}',
    vocab_token_map     jsonb
);

-- ---------------------------------------------------------------------------
-- production_queue
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.production_queue (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    topic_id            uuid NOT NULL REFERENCES public.topics(id),
    language_id         integer NOT NULL REFERENCES public.dim_languages(id),
    status_id           integer DEFAULT 1 REFERENCES public.dim_status(id),
    rejection_reason    text,
    processed_at        timestamptz,
    created_at          timestamptz DEFAULT now(),
    tests_generated     integer DEFAULT 0,
    error_log           text
);

-- ---------------------------------------------------------------------------
-- topic_generation_runs
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.topic_generation_runs (
    id                              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_date                        date NOT NULL,
    category_id                     integer REFERENCES public.categories(id),
    category_name                   text,
    topics_generated                integer DEFAULT 0,
    topics_rejected_similarity      integer DEFAULT 0,
    topics_rejected_gatekeeper      integer DEFAULT 0,
    candidates_proposed             integer DEFAULT 0,
    api_calls_llm                   integer DEFAULT 0,
    api_calls_embedding             integer DEFAULT 0,
    total_cost_usd                  real DEFAULT 0,
    execution_time_seconds          integer,
    error_message                   text,
    created_at                      timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- pack_collocations
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.pack_collocations (
    pack_id             bigint NOT NULL REFERENCES public.collocation_packs(id),
    collocation_id      bigint NOT NULL REFERENCES public.corpus_collocations(id),
    PRIMARY KEY (pack_id, collocation_id)
);

-- ---------------------------------------------------------------------------
-- user_pack_selections
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.user_pack_selections (
    user_id             text NOT NULL,
    pack_id             bigint NOT NULL REFERENCES public.collocation_packs(id),
    selected_at         timestamptz DEFAULT now(),
    PRIMARY KEY (user_id, pack_id)
);

-- ============================================================================
-- Tier 4: Depends on Tier 0-3
-- ============================================================================

-- ---------------------------------------------------------------------------
-- exercises
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.exercises (
    id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    language_id             integer NOT NULL REFERENCES public.dim_languages(id),
    exercise_type           text NOT NULL,
    source_type             text NOT NULL,
    grammar_pattern_id      integer REFERENCES public.dim_grammar_patterns(id),
    word_sense_id           integer REFERENCES public.dim_word_senses(id),
    corpus_collocation_id   integer,
    content                 jsonb NOT NULL,
    tags                    jsonb NOT NULL DEFAULT '{}',
    difficulty_static       real,
    irt_difficulty          real NOT NULL DEFAULT 0.0,
    irt_discrimination      real NOT NULL DEFAULT 1.0,
    cefr_level              text CHECK (cefr_level IN ('A1','A2','B1','B2','C1','C2')),
    attempt_count           integer NOT NULL DEFAULT 0,
    correct_count           integer NOT NULL DEFAULT 0,
    is_active               boolean NOT NULL DEFAULT true,
    generation_batch_id     uuid,
    created_at              timestamptz NOT NULL DEFAULT now(),
    pattern_code            text,
    CONSTRAINT chk_source_fk CHECK (
        (grammar_pattern_id IS NOT NULL)::int +
        (word_sense_id IS NOT NULL)::int +
        (corpus_collocation_id IS NOT NULL)::int = 1
    )
);

-- ---------------------------------------------------------------------------
-- questions
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.questions (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    test_id             uuid NOT NULL REFERENCES public.tests(id),
    question_id         text NOT NULL,
    question_text       text NOT NULL,
    choices             jsonb,
    answer              jsonb NOT NULL,
    answer_explanation  text,
    points              integer DEFAULT 1,
    audio_url           text,
    created_at          timestamptz DEFAULT now(),
    updated_at          timestamptz DEFAULT now(),
    question_type_id    integer REFERENCES public.dim_question_types(id),
    sense_ids           integer[]
);

-- ---------------------------------------------------------------------------
-- test_attempts
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.test_attempts (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id             uuid NOT NULL REFERENCES public.users(id),
    test_id             uuid NOT NULL REFERENCES public.tests(id),
    score               integer NOT NULL CHECK (score >= 0),
    total_questions     integer NOT NULL CHECK (total_questions > 0),
    percentage          real GENERATED ALWAYS AS ((score::real / total_questions::real) * 100) STORED,
    user_elo_before     integer NOT NULL,
    test_elo_before     integer NOT NULL,
    user_elo_after      integer NOT NULL,
    test_elo_after      integer NOT NULL,
    was_free_test       boolean NOT NULL DEFAULT false,
    tokens_consumed     integer NOT NULL DEFAULT 0 CHECK (tokens_consumed >= 0),
    created_at          timestamptz DEFAULT now(),
    language_id         integer NOT NULL REFERENCES public.dim_languages(id),
    test_type_id        integer NOT NULL REFERENCES public.dim_test_types(id),
    idempotency_key     uuid,
    attempt_number      integer DEFAULT 1,
    is_first_attempt    boolean DEFAULT true
);

-- ---------------------------------------------------------------------------
-- test_skill_ratings
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.test_skill_ratings (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    test_id         uuid NOT NULL REFERENCES public.tests(id),
    elo_rating      integer DEFAULT 1400 CHECK (elo_rating >= 400 AND elo_rating <= 3000),
    total_attempts  integer DEFAULT 0 CHECK (total_attempts >= 0),
    created_at      timestamptz DEFAULT now(),
    updated_at      timestamptz DEFAULT now(),
    test_type_id    integer NOT NULL REFERENCES public.dim_test_types(id),
    UNIQUE (test_id, test_type_id)
);

-- ---------------------------------------------------------------------------
-- user_reports
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.user_reports (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id             uuid NOT NULL REFERENCES public.users(id),
    report_category     text NOT NULL CHECK (report_category IN (
                            'test_answer_incorrect','test_load_error','website_crash',
                            'improvement_idea','audio_quality','other'
                        )),
    description         text NOT NULL,
    current_page        text,
    test_id             uuid REFERENCES public.tests(id),
    test_type           text,
    user_agent          text,
    screen_resolution   text,
    status              text DEFAULT 'pending' CHECK (status IN ('pending','reviewing','resolved','dismissed')),
    created_at          timestamptz DEFAULT now(),
    updated_at          timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- user_flashcards
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.user_flashcards (
    id              integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id         uuid NOT NULL REFERENCES public.users(id),
    sense_id        integer NOT NULL REFERENCES public.dim_word_senses(id),
    language_id     integer NOT NULL REFERENCES public.dim_languages(id),
    stability       real DEFAULT 0,
    difficulty      real DEFAULT 0.3,
    due_date        date,
    last_review     timestamptz,
    reps            integer DEFAULT 0,
    lapses          integer DEFAULT 0,
    state           text DEFAULT 'new' CHECK (state IN ('new','learning','review','relearning')),
    example_sentence text,
    audio_url       text,
    created_at      timestamptz DEFAULT now(),
    updated_at      timestamptz DEFAULT now(),
    UNIQUE (user_id, sense_id)
);

-- ---------------------------------------------------------------------------
-- user_vocabulary_knowledge
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.user_vocabulary_knowledge (
    id                      integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id                 uuid NOT NULL REFERENCES public.users(id),
    sense_id                integer NOT NULL REFERENCES public.dim_word_senses(id),
    language_id             integer NOT NULL REFERENCES public.dim_languages(id),
    p_known                 real NOT NULL DEFAULT 0.10,
    status                  text NOT NULL DEFAULT 'unknown' CHECK (status IN (
                                'unknown','encountered','learning','probably_known','known','user_marked_unknown'
                            )),
    evidence_count          integer DEFAULT 0,
    comprehension_correct   integer DEFAULT 0,
    comprehension_wrong     integer DEFAULT 0,
    word_test_correct       integer DEFAULT 0,
    word_test_wrong         integer DEFAULT 0,
    last_evidence_at        timestamptz,
    created_at              timestamptz DEFAULT now(),
    updated_at              timestamptz DEFAULT now(),
    UNIQUE (user_id, sense_id)
);

-- ---------------------------------------------------------------------------
-- vocabulary_review_queue
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.vocabulary_review_queue (
    id                  bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    vocab_id            integer NOT NULL REFERENCES public.dim_vocabulary(id),
    sense_id            integer REFERENCES public.dim_word_senses(id),
    issue_type          text NOT NULL CHECK (issue_type IN (
                            'validation_failed','duplicate_suspected','definition_unclear',
                            'offensive_content','llm_error'
                        )),
    proposed_definition text,
    failure_reason      text,
    context_sentence    text,
    status              text DEFAULT 'pending' CHECK (status IN ('pending','reviewing','resolved','dismissed')),
    reviewed_by         uuid REFERENCES public.users(id),
    resolution_notes    text,
    resolved_at         timestamptz,
    created_at          timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- exercise_attempts
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.exercise_attempts (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         uuid NOT NULL REFERENCES public.users(id),
    exercise_id     uuid REFERENCES public.exercises(id),
    user_response   jsonb,
    is_correct      boolean NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now()
);

-- ============================================================================
-- Tier 5: Depends on Tier 0-4
-- ============================================================================

-- ---------------------------------------------------------------------------
-- token_transactions
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.token_transactions (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id             uuid NOT NULL REFERENCES public.users(id),
    tokens_consumed     integer DEFAULT 0 CHECK (tokens_consumed >= 0),
    tokens_added        integer DEFAULT 0 CHECK (tokens_added >= 0),
    token_balance_after integer NOT NULL CHECK (token_balance_after >= 0),
    action              text NOT NULL,
    payment_intent_id   text,
    package_id          text,
    test_id             uuid REFERENCES public.tests(id),
    attempt_id          uuid REFERENCES public.test_attempts(id),
    is_valid            boolean DEFAULT true,
    invalidated_at      timestamptz,
    invalidation_reason text,
    created_by_system   boolean DEFAULT true,
    created_at          timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- word_quiz_results
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.word_quiz_results (
    id              integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id         uuid NOT NULL REFERENCES public.users(id),
    attempt_id      uuid REFERENCES public.test_attempts(id),
    sense_id        integer NOT NULL REFERENCES public.dim_word_senses(id),
    is_correct      boolean NOT NULL,
    selected_answer text,
    correct_answer  text,
    response_time_ms integer,
    created_at      timestamptz DEFAULT now()
);

-- ============================================================================
-- Indexes
-- ============================================================================

-- dim_grammar_patterns
CREATE INDEX IF NOT EXISTS idx_grammar_patterns_language ON public.dim_grammar_patterns(language_id);
CREATE INDEX IF NOT EXISTS idx_grammar_patterns_cefr     ON public.dim_grammar_patterns(cefr_level);
CREATE INDEX IF NOT EXISTS idx_grammar_patterns_active   ON public.dim_grammar_patterns(is_active) WHERE is_active = TRUE;

-- dim_vocabulary
CREATE INDEX IF NOT EXISTS idx_dv_level_tag ON public.dim_vocabulary(level_tag);

-- exercises
CREATE INDEX IF NOT EXISTS idx_exercises_language    ON public.exercises(language_id);
CREATE INDEX IF NOT EXISTS idx_exercises_type        ON public.exercises(exercise_type);
CREATE INDEX IF NOT EXISTS idx_exercises_source      ON public.exercises(source_type);
CREATE INDEX IF NOT EXISTS idx_exercises_grammar     ON public.exercises(grammar_pattern_id) WHERE grammar_pattern_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_exercises_sense       ON public.exercises(word_sense_id) WHERE word_sense_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_exercises_collocation ON public.exercises(corpus_collocation_id) WHERE corpus_collocation_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_exercises_cefr        ON public.exercises(cefr_level);
CREATE INDEX IF NOT EXISTS idx_exercises_active      ON public.exercises(is_active) WHERE is_active = TRUE;
CREATE INDEX IF NOT EXISTS idx_exercises_tags_gin    ON public.exercises USING GIN (tags);
CREATE INDEX IF NOT EXISTS idx_exercises_content_gin ON public.exercises USING GIN (content);

-- exercise_attempts
CREATE INDEX IF NOT EXISTS idx_ea_exercise_id        ON public.exercise_attempts(exercise_id);
CREATE INDEX IF NOT EXISTS idx_ea_user_response_gin  ON public.exercise_attempts USING GIN (user_response);

-- questions
CREATE INDEX IF NOT EXISTS idx_questions_type ON public.questions(question_type_id);

-- test_generation_runs
CREATE INDEX IF NOT EXISTS idx_test_generation_runs_date ON public.test_generation_runs(run_date);

-- user_vocabulary_knowledge
CREATE INDEX IF NOT EXISTS idx_uvk_user_language ON public.user_vocabulary_knowledge(user_id, language_id);
CREATE INDEX IF NOT EXISTS idx_uvk_user_status   ON public.user_vocabulary_knowledge(user_id, status);
CREATE INDEX IF NOT EXISTS idx_uvk_user_pknown   ON public.user_vocabulary_knowledge(user_id, p_known);

-- user_flashcards
CREATE INDEX IF NOT EXISTS idx_uf_user_due   ON public.user_flashcards(user_id, language_id, due_date);
CREATE INDEX IF NOT EXISTS idx_uf_user_state ON public.user_flashcards(user_id, state);

-- word_quiz_results
CREATE INDEX IF NOT EXISTS idx_wqr_user    ON public.word_quiz_results(user_id);
CREATE INDEX IF NOT EXISTS idx_wqr_attempt ON public.word_quiz_results(attempt_id);

-- ============================================================================
-- Analytics Views
-- ============================================================================

CREATE OR REPLACE VIEW public.vw_distractor_error_analysis AS
SELECT
    ea.user_id,
    e.tags->>'grammar_pattern'          AS pattern_code,
    ea.user_response->>'distractor_tag' AS error_type,
    COUNT(*)                             AS error_count,
    MIN(ea.created_at)                   AS first_seen,
    MAX(ea.created_at)                   AS last_seen
FROM public.exercise_attempts ea
JOIN public.exercises e ON ea.exercise_id = e.id
WHERE ea.is_correct = FALSE
  AND ea.user_response->>'distractor_tag' IS NOT NULL
  AND e.exercise_type = 'cloze_completion'
GROUP BY 1, 2, 3;

CREATE OR REPLACE VIEW public.vw_exercise_performance_by_type AS
SELECT
    e.exercise_type,
    e.cefr_level,
    e.language_id,
    COUNT(DISTINCT e.id)             AS exercise_count,
    COUNT(ea.id)                     AS total_attempts,
    SUM(ea.is_correct::int)          AS correct_count,
    ROUND(
        SUM(ea.is_correct::int)::numeric / NULLIF(COUNT(ea.id), 0) * 100,
        1
    )                                AS accuracy_pct
FROM public.exercises e
LEFT JOIN public.exercise_attempts ea ON ea.exercise_id = e.id
WHERE e.is_active = TRUE
GROUP BY 1, 2, 3;

-- ============================================================================
-- Functions (all 41 live function definitions)
-- ============================================================================

CREATE OR REPLACE FUNCTION public.add_tokens_atomic(p_user_id uuid, p_tokens_to_add integer, p_action text, p_idempotency_key text, p_payment_intent_id text DEFAULT NULL::text, p_package_id text DEFAULT NULL::text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
BEGIN
  IF p_user_id != auth.uid() THEN
    IF NOT (is_admin(auth.uid()) OR is_moderator(auth.uid())) THEN
      RAISE EXCEPTION 'Unauthorized: Cannot add tokens for another user';
    END IF;
  END IF;
  RETURN true;
END;
$function$;

CREATE OR REPLACE FUNCTION public.anonymize_user_data(p_user_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
BEGIN
  IF p_user_id != auth.uid() AND NOT is_admin(auth.uid()) THEN
    RAISE EXCEPTION 'Unauthorized: Cannot anonymize another user';
  END IF;
  UPDATE users
  SET
    email = 'deleted-' || id || '@lingualoop.local',
    display_name = 'Deleted User',
    deleted_at = NOW(),
    anonymized_at = NOW()
  WHERE id = p_user_id;
  RAISE NOTICE 'User % anonymized successfully', p_user_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.batch_lookup_lemmas(p_lemmas text[], p_language_id integer)
 RETURNS TABLE(lemma text, vocab_id integer)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
AS $function$
BEGIN
  RETURN QUERY
  SELECT v.lemma, v.id
  FROM dim_vocabulary v
  WHERE v.language_id = p_language_id
    AND v.lemma = ANY(p_lemmas);
END;
$function$;

CREATE OR REPLACE FUNCTION public.bkt_status(p_known numeric)
 RETURNS text
 LANGUAGE plpgsql
 IMMUTABLE
AS $function$
BEGIN
    RETURN CASE
        WHEN p_known < 0.20 THEN 'unknown'
        WHEN p_known < 0.50 THEN 'encountered'
        WHEN p_known < 0.75 THEN 'learning'
        WHEN p_known < 0.90 THEN 'probably_known'
        ELSE 'known'
    END;
END;
$function$;

CREATE OR REPLACE FUNCTION public.bkt_update(p_current numeric, p_correct boolean, p_slip numeric DEFAULT 0.10, p_guess numeric DEFAULT 0.25)
 RETURNS numeric
 LANGUAGE plpgsql
 IMMUTABLE
AS $function$
DECLARE
    p_obs_knows NUMERIC;
    p_obs_not_knows NUMERIC;
BEGIN
    IF p_correct THEN
        p_obs_knows := 1 - p_slip;
        p_obs_not_knows := p_guess;
    ELSE
        p_obs_knows := p_slip;
        p_obs_not_knows := 1 - p_guess;
    END IF;

    RETURN GREATEST(0.02, LEAST(0.98,
        (p_obs_knows * p_current) /
        (p_obs_knows * p_current + p_obs_not_knows * (1 - p_current))
    ));
END;
$function$;

CREATE OR REPLACE FUNCTION public.bkt_update_comprehension(p_current numeric, p_correct boolean)
 RETURNS numeric
 LANGUAGE plpgsql
 IMMUTABLE
AS $function$
BEGIN
    RETURN bkt_update(p_current, p_correct, 0.10, 0.25);
END;
$function$;

CREATE OR REPLACE FUNCTION public.bkt_update_word_test(p_current numeric, p_correct boolean)
 RETURNS numeric
 LANGUAGE plpgsql
 IMMUTABLE
AS $function$
BEGIN
    RETURN bkt_update(p_current, p_correct, 0.05, 0.25);
END;
$function$;

CREATE OR REPLACE FUNCTION public.calculate_elo_rating(current_rating integer, opposing_rating integer, actual_score numeric, k_factor integer DEFAULT 32, volatility_multiplier numeric DEFAULT 1.0)
 RETURNS integer
 LANGUAGE plpgsql
 IMMUTABLE
AS $function$
DECLARE
    expected_score NUMERIC;
    adjusted_k NUMERIC;
    new_rating NUMERIC;
BEGIN
    expected_score := 1.0 / (1.0 + POWER(10, (opposing_rating - current_rating) / 400.0));
    adjusted_k := k_factor * volatility_multiplier;
    new_rating := current_rating + (adjusted_k * (actual_score - expected_score));
    RETURN GREATEST(400, LEAST(3000, ROUND(new_rating)::INTEGER));
END;
$function$;

CREATE OR REPLACE FUNCTION public.calculate_volatility_multiplier(attempts integer, last_date date DEFAULT NULL::date, base_volatility numeric DEFAULT 1.0)
 RETURNS numeric
 LANGUAGE plpgsql
 IMMUTABLE
AS $function$
DECLARE
    multiplier NUMERIC := base_volatility;
BEGIN
    IF attempts < 10 THEN
        multiplier := multiplier + 0.5;
    END IF;
    IF last_date IS NOT NULL AND (CURRENT_DATE - last_date) > 90 THEN
        multiplier := multiplier + 0.5;
    END IF;
    RETURN multiplier;
END;
$function$;

CREATE OR REPLACE FUNCTION public.can_use_free_test(p_user_id uuid)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  user_record RECORD;
  daily_limit integer;
BEGIN
  IF p_user_id != auth.uid() THEN
    RAISE EXCEPTION 'Unauthorized: Cannot check free test status for another user';
  END IF;
  daily_limit := get_daily_free_test_limit(p_user_id);
  RETURN daily_limit > 0;
END;
$function$;

CREATE OR REPLACE FUNCTION public.create_user_dependencies()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    INSERT INTO user_tokens (user_id, purchased_tokens)
    VALUES (NEW.id, 0)
    ON CONFLICT (user_id) DO NOTHING;
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_active_languages()
 RETURNS TABLE(id integer, language_code text, language_name text, native_name text)
 LANGUAGE plpgsql
AS $function$
BEGIN
    RETURN QUERY
    SELECT
        dl.id::INTEGER,
        dl.language_code::TEXT,
        dl.language_name::TEXT,
        COALESCE(dl.native_name, dl.language_name)::TEXT AS native_name
    FROM dim_languages dl
    WHERE dl.is_active = true
    ORDER BY dl.display_order;
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_daily_free_test_limit(p_user_id uuid)
 RETURNS integer
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
  SELECT COALESCE(dst.daily_free_tests, 0)
  FROM users u
  JOIN dim_subscription_tiers dst ON u.subscription_tier_id = dst.id
  WHERE u.id = p_user_id AND u.deleted_at IS NULL;
$function$;

CREATE OR REPLACE FUNCTION public.get_distractors(p_sense_id integer, p_language_id smallint, p_count integer DEFAULT 3)
 RETURNS TABLE(out_definition text)
 LANGUAGE plpgsql
AS $function$
BEGIN
    RETURN QUERY
    SELECT dws.definition
    FROM dim_word_senses dws
    JOIN dim_vocabulary dv ON dv.id = dws.vocab_id
    WHERE dv.language_id = p_language_id
      AND dws.id != p_sense_id
      AND dws.vocab_id != (SELECT vocab_id FROM dim_word_senses WHERE id = p_sense_id)
      AND dws.sense_rank = 1
    ORDER BY random()
    LIMIT p_count;
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_next_category()
 RETURNS TABLE(id integer, name text, status_id integer, target_language_id integer, last_used_at timestamp with time zone, cooldown_days integer)
 LANGUAGE plpgsql
AS $function$
BEGIN
    RETURN QUERY
    SELECT
        c.id,
        c.name::TEXT,
        c.status_id,
        c.target_language_id,
        c.last_used_at,
        c.cooldown_days
    FROM categories c
    JOIN dim_status s ON c.status_id = s.id
    WHERE s.status_code = 'active'
      AND c.target_language_id IS NULL
      AND (
          c.last_used_at IS NULL
          OR c.last_used_at < NOW() - (c.cooldown_days || ' days')::INTERVAL
      )
    ORDER BY c.last_used_at NULLS FIRST
    LIMIT 1;
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_org_role(p_user_id uuid, p_org_id uuid)
 RETURNS text
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
  SELECT role FROM organization_members
  WHERE user_id = p_user_id AND organization_id = p_org_id;
$function$;

CREATE OR REPLACE FUNCTION public.get_packs_with_user_selection(p_language_id integer, p_user_id text)
 RETURNS TABLE(id bigint, pack_name text, description text, pack_type text, tags text[], total_items integer, difficulty_range text, is_selected boolean)
 LANGUAGE sql
 STABLE
AS $function$
    SELECT
        cp.id,
        cp.pack_name,
        cp.description,
        cp.pack_type,
        cp.tags,
        cp.total_items,
        cp.difficulty_range,
        (ups.user_id IS NOT NULL) AS is_selected
    FROM collocation_packs cp
    LEFT JOIN user_pack_selections ups
        ON ups.pack_id = cp.id
       AND ups.user_id = p_user_id
    WHERE cp.language_id = p_language_id
      AND cp.is_public = TRUE
    ORDER BY cp.pack_name;
$function$;

CREATE OR REPLACE FUNCTION public.get_prompt_template(p_task_name character varying, p_language_code character varying DEFAULT 'default'::character varying)
 RETURNS text
 LANGUAGE plpgsql
AS $function$
DECLARE
    result_text TEXT;
BEGIN
    SELECT template_text INTO result_text
    FROM prompt_templates
    WHERE task_name = p_task_name
      AND language_code = p_language_code
      AND is_active = true
    ORDER BY version DESC
    LIMIT 1;

    IF result_text IS NULL THEN
        SELECT template_text INTO result_text
        FROM prompt_templates
        WHERE task_name = p_task_name
          AND language_code = 'default'
          AND is_active = true
        ORDER BY version DESC
        LIMIT 1;
    END IF;

    RETURN result_text;
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_recommended_test(p_user_id uuid, p_language_id integer)
 RETURNS SETOF tests
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_listening_type_id SMALLINT;
  v_reading_type_id SMALLINT;
  v_user_listening_elo INT := 1200;
  v_user_reading_elo INT := 1200;
  v_radius INT;
  v_radii INT[] := ARRAY[50, 100, 250, 500, 10000];
  v_test_found tests%ROWTYPE;
BEGIN
  SELECT id INTO v_listening_type_id FROM dim_test_types WHERE type_code = 'listening';
  SELECT id INTO v_reading_type_id FROM dim_test_types WHERE type_code = 'reading';

  SELECT
    MAX(CASE WHEN test_type_id = v_listening_type_id THEN elo_rating END),
    MAX(CASE WHEN test_type_id = v_reading_type_id THEN elo_rating END)
  INTO v_user_listening_elo, v_user_reading_elo
  FROM user_skill_ratings
  WHERE user_id = p_user_id
    AND language_id = p_language_id;

  IF v_user_listening_elo IS NULL THEN v_user_listening_elo := 1200; END IF;
  IF v_user_reading_elo IS NULL THEN v_user_reading_elo := 1200; END IF;

  FOREACH v_radius IN ARRAY v_radii
  LOOP
    SELECT t.*
    INTO v_test_found
    FROM tests t
    JOIN test_skill_ratings tsr ON t.id = tsr.test_id
    WHERE t.language_id = p_language_id
      AND t.is_active = TRUE
      AND tsr.test_type_id IN (v_listening_type_id, v_reading_type_id)
      AND (
        (tsr.test_type_id = v_listening_type_id
         AND tsr.elo_rating BETWEEN (v_user_listening_elo - v_radius) AND (v_user_listening_elo + v_radius))
        OR
        (tsr.test_type_id = v_reading_type_id
         AND tsr.elo_rating BETWEEN (v_user_reading_elo - v_radius) AND (v_user_reading_elo + v_radius))
      )
    ORDER BY random()
    LIMIT 1;

    IF v_test_found.id IS NOT NULL THEN
      RETURN NEXT v_test_found;
      RETURN;
    END IF;
  END LOOP;
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_recommended_tests(p_user_id uuid, p_language text)
 RETURNS TABLE(test_id uuid, slug text, test_type text, title text, difficulty_level integer, elo_rating integer, elo_diff integer, tier text)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_language_id SMALLINT;
  v_user_tier_code TEXT;
  v_is_premium BOOLEAN;
BEGIN
  SELECT id INTO v_language_id
  FROM dim_languages
  WHERE LOWER(language_code) = LOWER(p_language)
     OR LOWER(language_name) = LOWER(p_language)
  LIMIT 1;

  IF v_language_id IS NULL THEN
    RAISE EXCEPTION 'Language not found: %', p_language;
  END IF;

  SELECT st.tier_code INTO v_user_tier_code
  FROM users u
  JOIN dim_subscription_tiers st ON u.subscription_tier_id = st.id
  WHERE u.id = p_user_id;

  v_is_premium := (v_user_tier_code NOT ILIKE '%free%');

  RETURN QUERY
  WITH target_types AS (
    SELECT id AS type_id, type_code
    FROM dim_test_types
    WHERE type_code IN ('listening', 'reading', 'dictation')
  ),
  user_stats AS (
    SELECT
      tt.type_id,
      tt.type_code,
      COALESCE(usr.elo_rating, 1200) as current_elo
    FROM target_types tt
    LEFT JOIN user_skill_ratings usr
      ON usr.user_id = p_user_id
      AND usr.language_id = v_language_id
      AND usr.test_type_id = tt.type_id
  ),
  all_candidates AS (
    SELECT
      t.id AS c_test_id,
      t.slug::text AS c_slug,
      us.type_code::text AS c_test_type,
      t.title::text AS c_title,
      t.difficulty AS c_difficulty_level,
      tsr.elo_rating AS c_elo_rating,
      ABS(tsr.elo_rating - us.current_elo) AS c_elo_diff,
      t.tier::text AS c_tier,
      ROW_NUMBER() OVER (
        PARTITION BY us.type_code
        ORDER BY ABS(tsr.elo_rating - us.current_elo) ASC
      ) AS rank_in_type
    FROM user_stats us
    JOIN test_skill_ratings tsr ON tsr.test_type_id = us.type_id
    JOIN tests t ON t.id = tsr.test_id
    WHERE t.language_id = v_language_id
      AND t.is_active = true
      AND (
        t.tier = 'free-tier'
        OR (t.tier != 'free-tier' AND v_is_premium)
      )
      AND NOT EXISTS (
        SELECT 1
        FROM test_attempts ta
        WHERE ta.user_id = p_user_id
          AND ta.test_id = t.id
      )
  ),
  deduplicated AS (
    SELECT DISTINCT ON (c_test_id)
      c_test_id, c_slug, c_test_type, c_title,
      c_difficulty_level, c_elo_rating, c_elo_diff, c_tier
    FROM all_candidates
    WHERE rank_in_type <= 3
    ORDER BY c_test_id, c_elo_diff ASC
  )
  SELECT
    d.c_test_id, d.c_slug, d.c_test_type, d.c_title,
    d.c_difficulty_level, d.c_elo_rating, d.c_elo_diff, d.c_tier
  FROM deduplicated d
  ORDER BY d.c_elo_diff ASC;
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_test_token_cost(p_user_id uuid)
 RETURNS integer
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
  SELECT COALESCE(dst.tokens_per_test, 10)
  FROM users u
  JOIN dim_subscription_tiers dst ON u.subscription_tier_id = dst.id
  WHERE u.id = p_user_id AND u.deleted_at IS NULL;
$function$;

CREATE OR REPLACE FUNCTION public.get_token_balance(p_user_id uuid)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
BEGIN
  IF p_user_id != auth.uid() THEN
    IF NOT (is_admin(auth.uid()) OR is_moderator(auth.uid())) THEN
      RAISE EXCEPTION 'Unauthorized: Cannot view another user''s token balance';
    END IF;
  END IF;
  RETURN 0;
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_top_collocations_for_sources(p_source_ids integer[], p_min_pmi double precision, p_top_n integer)
 RETURNS TABLE(id bigint, collocation_text text, n_gram_size integer, pmi_score double precision, log_likelihood double precision, t_score double precision, collocation_type text, pos_pattern text, language_id integer)
 LANGUAGE sql
 STABLE
AS $function$
    SELECT sub.id, sub.collocation_text, sub.n_gram_size, sub.pmi_score,
           sub.log_likelihood, sub.t_score, sub.collocation_type,
           sub.pos_pattern, sub.language_id
    FROM (
        SELECT DISTINCT ON (cc.collocation_text)
            cc.id,
            cc.collocation_text,
            cc.n_gram_size,
            cc.pmi_score,
            cc.log_likelihood,
            cc.t_score,
            cc.collocation_type,
            cc.pos_pattern,
            cc.language_id
        FROM corpus_collocations cc
        WHERE cc.corpus_source_id = ANY(p_source_ids)
          AND cc.pmi_score >= p_min_pmi
        ORDER BY cc.collocation_text, cc.pmi_score DESC
    ) sub
    ORDER BY sub.pmi_score DESC
    LIMIT p_top_n;
$function$;

CREATE OR REPLACE FUNCTION public.get_vocab_recommendations(p_user_id uuid, p_language_id integer, p_target_unknown_min double precision DEFAULT 0.03, p_target_unknown_max double precision DEFAULT 0.07, p_limit integer DEFAULT 20)
 RETURNS TABLE(test_id uuid, title text, slug text, unknown_pct double precision, unknown_count integer)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
AS $function$
DECLARE
  v_known_sense_ids int[];
  v_user_elo int;
BEGIN
  SELECT known_sense_ids INTO v_known_sense_ids
  FROM user_vocabulary
  WHERE user_id = p_user_id AND language_id = p_language_id;

  SELECT elo_rating INTO v_user_elo
  FROM user_skill_ratings
  WHERE user_id = p_user_id AND language_id = p_language_id
  LIMIT 1;

  IF v_known_sense_ids IS NULL THEN v_known_sense_ids := '{}'; END IF;
  IF v_user_elo IS NULL THEN v_user_elo := 1200; END IF;

  RETURN QUERY
  SELECT
    t.id,
    t.title,
    t.slug,
    (CARDINALITY(t.vocab_sense_ids) - CARDINALITY(t.vocab_sense_ids & v_known_sense_ids))::float
      / NULLIF(CARDINALITY(t.vocab_sense_ids), 0) as u_pct,
    (CARDINALITY(t.vocab_sense_ids) - CARDINALITY(t.vocab_sense_ids & v_known_sense_ids)) as u_count
  FROM public.tests t
  LEFT JOIN public.test_skill_ratings tsr ON tsr.test_id = t.id
  WHERE
    t.language_id = p_language_id
    AND t.is_active = true
    AND (tsr.elo_rating BETWEEN (v_user_elo - 200) AND (v_user_elo + 200) OR tsr.elo_rating IS NULL)
    AND CARDINALITY(t.vocab_sense_ids) > 0
  HAVING
    (CARDINALITY(t.vocab_sense_ids) - CARDINALITY(t.vocab_sense_ids & v_known_sense_ids))::float
      / NULLIF(CARDINALITY(t.vocab_sense_ids), 0)
    BETWEEN p_target_unknown_min AND p_target_unknown_max
  ORDER BY ABS(u_pct - 0.05)
  LIMIT p_limit;
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_word_quiz_candidates(p_user_id uuid, p_sense_ids integer[], p_language_id smallint, p_max_words integer DEFAULT 5)
 RETURNS TABLE(out_sense_id integer, out_lemma text, out_definition text, out_pronunciation text, out_p_known numeric, out_score numeric)
 LANGUAGE plpgsql
AS $function$
BEGIN
    RETURN QUERY
    SELECT
        uvk.sense_id,
        dv.lemma,
        dws.definition,
        dws.pronunciation,
        uvk.p_known,
        (uvk.p_known * (1 - uvk.p_known) *
         (1.0 / GREATEST(1.0, ln(GREATEST(1.0, COALESCE(dv.frequency_rank, 1.0)::numeric))))
        ) AS score
    FROM user_vocabulary_knowledge uvk
    JOIN dim_word_senses dws ON dws.id = uvk.sense_id
    JOIN dim_vocabulary dv ON dv.id = dws.vocab_id
    WHERE uvk.user_id = p_user_id
      AND uvk.sense_id = ANY(p_sense_ids)
      AND uvk.p_known BETWEEN 0.25 AND 0.75
      AND uvk.status != 'user_marked_unknown'
    ORDER BY score DESC
    LIMIT p_max_words;
END;
$function$;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
    v_free_tier_id integer;
BEGIN
    SELECT id INTO v_free_tier_id
    FROM dim_subscription_tiers
    WHERE tier_code = 'free'
    LIMIT 1;

    IF v_free_tier_id IS NULL THEN
        INSERT INTO dim_subscription_tiers (
            tier_code, display_name, can_generate_tests, can_create_custom_tests, daily_free_tests
        )
        VALUES ('free', 'Free', false, false, 2)
        RETURNING id INTO v_free_tier_id;
        RAISE LOG 'Created free tier with ID: %', v_free_tier_id;
    END IF;

    INSERT INTO public.users (
        id, email, subscription_tier_id, email_verified,
        created_at, last_login, total_tests_taken, total_tests_generated
    )
    VALUES (
        NEW.id, NEW.email, v_free_tier_id,
        COALESCE(NEW.email_confirmed_at IS NOT NULL, false),
        NOW(), NOW(), 0, 0
    )
    ON CONFLICT (id) DO UPDATE SET
        email = EXCLUDED.email,
        email_verified = COALESCE(NEW.email_confirmed_at IS NOT NULL, false),
        last_login = NOW();

    RAISE LOG 'User profile created successfully for: % (tier_id: %)', NEW.email, v_free_tier_id;
    RETURN NEW;

EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'Failed to create user profile for %: % (SQLSTATE: %)',
        NEW.email, SQLERRM, SQLSTATE;
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.is_admin(p_user_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
  SELECT COALESCE(dst.is_admin, false)
  FROM users u
  JOIN dim_subscription_tiers dst ON u.subscription_tier_id = dst.id
  WHERE u.id = p_user_id AND u.deleted_at IS NULL;
$function$;

CREATE OR REPLACE FUNCTION public.is_moderator(p_user_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
  SELECT COALESCE(dst.is_moderator OR dst.is_admin, false)
  FROM users u
  JOIN dim_subscription_tiers dst ON u.subscription_tier_id = dst.id
  WHERE u.id = p_user_id AND u.deleted_at IS NULL;
$function$;

CREATE OR REPLACE FUNCTION public.is_org_member(p_user_id uuid, p_org_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
  SELECT EXISTS (
    SELECT 1 FROM organization_members
    WHERE user_id = p_user_id AND organization_id = p_org_id
  );
$function$;

CREATE OR REPLACE FUNCTION public.match_topics(query_category integer, query_embedding vector, match_threshold double precision DEFAULT 0.85, match_count integer DEFAULT 5)
 RETURNS TABLE(id uuid, concept_english text, similarity double precision)
 LANGUAGE plpgsql
AS $function$
BEGIN
    RETURN QUERY
    SELECT
        t.id,
        t.concept_english,
        (1 - (t.embedding <=> query_embedding))::FLOAT AS similarity
    FROM topics t
    WHERE t.category_id = query_category
      AND t.embedding IS NOT NULL
      AND (1 - (t.embedding <=> query_embedding)) > match_threshold
    ORDER BY t.embedding <=> query_embedding
    LIMIT match_count;
END;
$function$;

CREATE OR REPLACE FUNCTION public.migrate_test_json(test_json jsonb)
 RETURNS uuid
 LANGUAGE plpgsql
AS $function$
DECLARE
    test_id UUID;
    question_record JSONB;
    question_order_counter INTEGER := 1;
BEGIN
    INSERT INTO tests (
        slug, language, topic, difficulty, transcript,
        listening_rating, reading_rating,
        listening_volatility, reading_volatility
    )
    VALUES (
        test_json->>'slug',
        test_json->>'language',
        test_json->>'topic',
        (test_json->>'difficulty')::INTEGER,
        test_json->>'transcript',
        (test_json->'ratings'->'listening'->>'rating')::INTEGER,
        (test_json->'ratings'->'reading'->>'rating')::INTEGER,
        (test_json->'ratings'->'listening'->>'volatility')::DECIMAL,
        (test_json->'ratings'->'reading'->>'volatility')::DECIMAL
    )
    RETURNING id INTO test_id;

    FOR question_record IN SELECT * FROM jsonb_array_elements(test_json->'questions')
    LOOP
        INSERT INTO test_questions (
            test_id, question_id, question_text, choices, correct_answer,
            question_order, listening_rating, reading_rating,
            listening_volatility, reading_volatility
        )
        VALUES (
            test_id,
            question_record->>'id',
            question_record->>'question',
            question_record->'choices',
            question_record->>'answer',
            question_order_counter,
            (question_record->'ratings'->'listening'->>'rating')::INTEGER,
            (question_record->'ratings'->'reading'->>'rating')::INTEGER,
            (question_record->'ratings'->'listening'->>'volatility')::DECIMAL,
            (question_record->'ratings'->'reading'->>'volatility')::DECIMAL
        );
        question_order_counter := question_order_counter + 1;
    END LOOP;

    INSERT INTO test_catalog (test_id, slug, language, difficulty, topic, listening_rating, reading_rating)
    VALUES (
        test_id,
        test_json->>'slug',
        test_json->>'language',
        (test_json->>'difficulty')::INTEGER,
        test_json->>'topic',
        (test_json->'ratings'->'listening'->>'rating')::INTEGER,
        (test_json->'ratings'->'reading'->>'rating')::INTEGER
    );

    RETURN test_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.process_stripe_payment(p_user_id uuid, p_tokens_to_add integer, p_payment_intent_id text, p_package_id text, p_amount_cents integer)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    current_balance INTEGER;
    token_record RECORD;
BEGIN
    SELECT * INTO token_record FROM token_transactions WHERE payment_intent_id = p_payment_intent_id;
    IF FOUND THEN
        RETURN TRUE;
    END IF;

    SELECT * INTO token_record FROM user_tokens WHERE user_id = p_user_id FOR UPDATE;
    current_balance := token_record.purchased_tokens + token_record.bonus_tokens;

    UPDATE user_tokens SET
        purchased_tokens = purchased_tokens + p_tokens_to_add,
        total_tokens_purchased = total_tokens_purchased + p_tokens_to_add
    WHERE user_id = p_user_id;

    INSERT INTO token_transactions (
        user_id, tokens_added, action, idempotency_key,
        payment_intent_id, package_id, token_balance_after, created_at
    ) VALUES (
        p_user_id, p_tokens_to_add, 'stripe_payment', p_payment_intent_id,
        p_payment_intent_id, p_package_id, current_balance + p_tokens_to_add, NOW()
    );

    RETURN TRUE;
END;
$function$;

CREATE OR REPLACE FUNCTION public.process_test_submission(p_user_id uuid, p_test_id uuid, p_language_id smallint, p_test_type_id smallint, p_responses jsonb, p_was_free_test boolean DEFAULT true, p_idempotency_key uuid DEFAULT NULL::uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_user_elo integer;
  v_test_elo integer;
  v_user_tests_taken integer;
  v_user_last_date date;
  v_test_attempts integer;
  v_percentage numeric;
  v_percentage_decimal numeric;
  v_new_user_elo integer;
  v_new_test_elo integer;
  v_attempt_id uuid;
  v_attempt_number integer;
  v_is_first_attempt boolean;
  v_existing_attempt record;
  v_tokens_cost integer;
  v_score integer := 0;
  v_total_questions integer := 0;
  v_question_results jsonb := '[]'::jsonb;
  v_question_record record;
  v_user_answer text;
  v_correct_answer text;
  v_is_correct boolean;
BEGIN
  -- SECURITY VALIDATION
  IF p_user_id != auth.uid() THEN
    RAISE EXCEPTION 'Unauthorized: Cannot submit test for another user';
  END IF;

  -- INPUT VALIDATION
  IF p_responses IS NULL OR jsonb_array_length(p_responses) = 0 THEN
    RAISE EXCEPTION 'No responses provided';
  END IF;

  -- ANSWER VALIDATION
  CREATE TEMP TABLE temp_user_responses AS
  SELECT
      (elem->>'question_id')::UUID as question_id,
      elem->>'selected_answer' as selected_answer
  FROM jsonb_array_elements(p_responses) as elem;

  FOR v_question_record IN (
      SELECT q.id, q.answer
      FROM questions q
      WHERE q.test_id = p_test_id
      ORDER BY q.created_at
  ) LOOP
      SELECT selected_answer INTO v_user_answer
      FROM temp_user_responses
      WHERE question_id = v_question_record.id;

      v_user_answer := COALESCE(v_user_answer, '');
      v_correct_answer := v_question_record.answer #>> '{}';
      v_is_correct := (v_user_answer = v_correct_answer);

      IF v_is_correct THEN
          v_score := v_score + 1;
      END IF;

      v_question_results := v_question_results || jsonb_build_object(
          'question_id', v_question_record.id::TEXT,
          'selected_answer', v_user_answer,
          'correct_answer', v_correct_answer,
          'is_correct', v_is_correct
      );

      v_total_questions := v_total_questions + 1;
  END LOOP;

  DROP TABLE IF EXISTS temp_user_responses;

  -- IDEMPOTENCY CHECK
  IF p_idempotency_key IS NOT NULL THEN
    SELECT * INTO v_existing_attempt
    FROM test_attempts
    WHERE user_id = p_user_id AND idempotency_key = p_idempotency_key;

    IF FOUND THEN
      RETURN jsonb_build_object(
        'success', true,
        'attempt_id', v_existing_attempt.id,
        'cached', true,
        'user_elo_change', COALESCE(
          v_existing_attempt.user_elo_after - v_existing_attempt.user_elo_before,
          0
        ),
        'message', 'Duplicate submission detected - returning cached result'
      );
    END IF;
  END IF;

  -- GET TOKEN COST
  v_tokens_cost := get_test_token_cost(p_user_id);

  -- CALCULATE PERCENTAGE
  v_percentage := (v_score::numeric / v_total_questions::numeric) * 100;
  v_percentage_decimal := v_percentage / 100.0;

  -- DETERMINE ATTEMPT NUMBER
  SELECT COUNT(*) INTO v_attempt_number
  FROM test_attempts
  WHERE user_id = p_user_id
    AND test_id = p_test_id
    AND test_type_id = p_test_type_id;

  v_attempt_number := v_attempt_number + 1;
  v_is_first_attempt := (v_attempt_number = 1);

  -- GET OR CREATE USER ELO RATING
  SELECT elo_rating, tests_taken, last_test_date
  INTO v_user_elo, v_user_tests_taken, v_user_last_date
  FROM user_skill_ratings
  WHERE user_id = p_user_id
    AND language_id = p_language_id
    AND test_type_id = p_test_type_id;

  IF NOT FOUND THEN
    v_user_elo := 1200;
    v_user_tests_taken := 0;
    v_user_last_date := NULL;

    INSERT INTO user_skill_ratings (
      user_id, language_id, test_type_id, elo_rating, tests_taken
    ) VALUES (
      p_user_id, p_language_id, p_test_type_id, v_user_elo, 0
    );
  END IF;

  -- GET OR CREATE TEST ELO RATING
  SELECT elo_rating, total_attempts
  INTO v_test_elo, v_test_attempts
  FROM test_skill_ratings
  WHERE test_id = p_test_id AND test_type_id = p_test_type_id;

  IF NOT FOUND THEN
    v_test_elo := 1400;
    v_test_attempts := 0;

    INSERT INTO test_skill_ratings (
      test_id, test_type_id, elo_rating, total_attempts
    ) VALUES (
      p_test_id, p_test_type_id, v_test_elo, 0
    );
  END IF;

  -- CALCULATE ELO CHANGES (ONLY FOR FIRST ATTEMPTS)
  IF v_is_first_attempt THEN
    DECLARE
      expected_user_score numeric;
      k_factor integer := 32;
    BEGIN
      expected_user_score := 1.0 / (1.0 + POWER(10, (v_test_elo - v_user_elo) / 400.0));
      v_new_user_elo := ROUND(v_user_elo + k_factor * (v_percentage_decimal - expected_user_score));
      v_new_test_elo := ROUND(v_test_elo + k_factor * ((1.0 - v_percentage_decimal) - (1.0 - expected_user_score)));
      v_new_user_elo := GREATEST(400, LEAST(3000, v_new_user_elo));
      v_new_test_elo := GREATEST(400, LEAST(3000, v_new_test_elo));
    END;

    UPDATE user_skill_ratings
    SET elo_rating = v_new_user_elo, tests_taken = tests_taken + 1,
        last_test_date = CURRENT_DATE, updated_at = NOW()
    WHERE user_id = p_user_id AND language_id = p_language_id AND test_type_id = p_test_type_id;

    UPDATE test_skill_ratings
    SET elo_rating = v_new_test_elo, total_attempts = total_attempts + 1, updated_at = NOW()
    WHERE test_id = p_test_id AND test_type_id = p_test_type_id;
  ELSE
    v_new_user_elo := v_user_elo;
    v_new_test_elo := v_test_elo;
  END IF;

  -- INSERT ATTEMPT RECORD
  INSERT INTO test_attempts (
    user_id, test_id, test_type_id, language_id, score, total_questions,
    attempt_number, is_first_attempt, user_elo_before, user_elo_after,
    test_elo_before, test_elo_after, tokens_consumed, was_free_test, idempotency_key
  ) VALUES (
    p_user_id, p_test_id, p_test_type_id, p_language_id, v_score, v_total_questions,
    v_attempt_number, v_is_first_attempt, v_user_elo, v_new_user_elo,
    v_test_elo, v_new_test_elo,
    CASE WHEN p_was_free_test THEN 0 ELSE v_tokens_cost END,
    p_was_free_test, p_idempotency_key
  )
  RETURNING id INTO v_attempt_id;

  -- UPDATE USER_LANGUAGES
  INSERT INTO user_languages (user_id, language_id, total_tests_taken, last_test_date)
  VALUES (p_user_id, p_language_id, 1, CURRENT_DATE)
  ON CONFLICT (user_id, language_id)
  DO UPDATE SET total_tests_taken = user_languages.total_tests_taken + 1,
    last_test_date = CURRENT_DATE, updated_at = NOW();

  -- RETURN SUCCESS
  RETURN jsonb_build_object(
    'success', true, 'attempt_id', v_attempt_id, 'attempt_number', v_attempt_number,
    'is_first_attempt', v_is_first_attempt, 'user_elo_before', v_user_elo,
    'user_elo_after', v_new_user_elo, 'user_elo_change', v_new_user_elo - v_user_elo,
    'test_elo_before', v_test_elo, 'test_elo_after', v_new_test_elo,
    'test_elo_change', CASE WHEN v_is_first_attempt THEN v_new_test_elo - v_test_elo ELSE 0 END,
    'tokens_cost', CASE WHEN p_was_free_test THEN 0 ELSE v_tokens_cost END,
    'score', v_score, 'total_questions', v_total_questions, 'percentage', v_percentage,
    'question_results', v_question_results,
    'message', CASE WHEN v_is_first_attempt THEN 'First attempt - ELO updated' ELSE 'Retake - ELO unchanged' END
  );

EXCEPTION WHEN OTHERS THEN
  RETURN jsonb_build_object('success', false, 'error', SQLERRM, 'error_detail', SQLSTATE);
END;
$function$;

CREATE OR REPLACE FUNCTION public."process_test_submission-old"(p_user_id uuid, p_test_id uuid, p_language_id smallint, p_test_type_id smallint, p_responses jsonb, p_was_free_test boolean DEFAULT true, p_idempotency_key uuid DEFAULT NULL::uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$DECLARE
  v_user_elo integer;
  v_test_elo integer;
  v_user_tests_taken integer;
  v_user_last_date date;
  v_test_attempts integer;
  v_percentage numeric;
  v_percentage_decimal numeric;
  v_new_user_elo integer;
  v_new_test_elo integer;
  v_attempt_id uuid;
  v_attempt_number integer;
  v_is_first_attempt boolean;
  v_existing_attempt record;
  v_tokens_cost integer;
  v_score integer := 0;
  v_total_questions integer := 0;
  v_question_results jsonb := '[]'::jsonb;
  v_question_record record;
  v_user_answer text;
  v_correct_answer text;
  v_is_correct boolean;
BEGIN
  IF p_user_id != auth.uid() THEN
    RAISE EXCEPTION 'Unauthorized: Cannot submit test for another user';
  END IF;

  IF p_responses IS NULL OR jsonb_array_length(p_responses) = 0 THEN
    RAISE EXCEPTION 'No responses provided';
  END IF;

  CREATE TEMP TABLE temp_user_responses AS
  SELECT
      (elem->>'question_id')::UUID as question_id,
      elem->>'selected_answer' as selected_answer
  FROM jsonb_array_elements(p_responses) as elem;

  FOR v_question_record IN (
      SELECT q.id, q.answer
      FROM questions q
      WHERE q.test_id = p_test_id
      ORDER BY q.created_at
  ) LOOP
      SELECT selected_answer INTO v_user_answer
      FROM temp_user_responses
      WHERE question_id = v_question_record.id;

      v_user_answer := COALESCE(v_user_answer, '');
      v_correct_answer := v_question_record.answer #>> '{}';
      v_is_correct := (v_user_answer = v_correct_answer);

      IF v_is_correct THEN
          v_score := v_score + 1;
      END IF;

      v_question_results := v_question_results || jsonb_build_object(
          'question_id', v_question_record.id::TEXT,
          'selected_answer', v_user_answer,
          'correct_answer', v_correct_answer,
          'is_correct', v_is_correct
      );

      v_total_questions := v_total_questions + 1;
  END LOOP;

  DROP TABLE IF EXISTS temp_user_responses;

  IF p_idempotency_key IS NOT NULL THEN
    SELECT * INTO v_existing_attempt
    FROM test_attempts
    WHERE user_id = p_user_id AND idempotency_key = p_idempotency_key;

    IF FOUND THEN
      RETURN jsonb_build_object(
        'success', true,
        'attempt_id', v_existing_attempt.id,
        'cached', true,
        'user_elo_change', COALESCE(
          v_existing_attempt.user_elo_after - v_existing_attempt.user_elo_before, 0
        ),
        'message', 'Duplicate submission detected - returning cached result'
      );
    END IF;
  END IF;

  v_tokens_cost := get_test_token_cost(p_user_id);
  v_percentage := (v_score::numeric / v_total_questions::numeric) * 100;
  v_percentage_decimal := v_percentage / 100.0;

  SELECT COUNT(*) INTO v_attempt_number
  FROM test_attempts
  WHERE user_id = p_user_id AND test_id = p_test_id AND test_type_id = p_test_type_id;

  v_attempt_number := v_attempt_number + 1;
  v_is_first_attempt := (v_attempt_number = 1);

  SELECT elo_rating, tests_taken, last_test_date
  INTO v_user_elo, v_user_tests_taken, v_user_last_date
  FROM user_skill_ratings
  WHERE user_id = p_user_id AND language_id = p_language_id AND test_type_id = p_test_type_id;

  IF NOT FOUND THEN
    v_user_elo := 1200; v_user_tests_taken := 0; v_user_last_date := NULL;
    INSERT INTO user_skill_ratings (user_id, language_id, test_type_id, elo_rating, tests_taken)
    VALUES (p_user_id, p_language_id, p_test_type_id, v_user_elo, 0);
  END IF;

  SELECT elo_rating, total_attempts INTO v_test_elo, v_test_attempts
  FROM test_skill_ratings WHERE test_id = p_test_id AND test_type_id = p_test_type_id;

  IF NOT FOUND THEN
    v_test_elo := 1400; v_test_attempts := 0;
    INSERT INTO test_skill_ratings (test_id, test_type_id, elo_rating, total_attempts)
    VALUES (p_test_id, p_test_type_id, v_test_elo, 0);
  END IF;

  IF v_is_first_attempt THEN
    DECLARE
      expected_user_score numeric;
      k_factor integer := 32;
    BEGIN
      expected_user_score := 1.0 / (1.0 + POWER(10, (v_test_elo - v_user_elo) / 400.0));
      v_new_user_elo := ROUND(v_user_elo + k_factor * (v_percentage_decimal - expected_user_score));
      v_new_test_elo := ROUND(v_test_elo + k_factor * ((1.0 - v_percentage_decimal) - (1.0 - expected_user_score)));
      v_new_user_elo := GREATEST(400, LEAST(3000, v_new_user_elo));
      v_new_test_elo := GREATEST(400, LEAST(3000, v_new_test_elo));
    END;

    UPDATE user_skill_ratings
    SET elo_rating = v_new_user_elo, tests_taken = tests_taken + 1,
        last_test_date = CURRENT_DATE, updated_at = NOW()
    WHERE user_id = p_user_id AND language_id = p_language_id AND test_type_id = p_test_type_id;

    UPDATE test_skill_ratings
    SET elo_rating = v_new_test_elo, total_attempts = total_attempts + 1, updated_at = NOW()
    WHERE test_id = p_test_id AND test_type_id = p_test_type_id;
  ELSE
    v_new_user_elo := v_user_elo;
    v_new_test_elo := v_test_elo;
  END IF;

  INSERT INTO test_attempts (
    user_id, test_id, test_type_id, language_id, score, total_questions,
    attempt_number, is_first_attempt, user_elo_before, user_elo_after,
    test_elo_before, test_elo_after, tokens_consumed, was_free_test, idempotency_key
  ) VALUES (
    p_user_id, p_test_id, p_test_type_id, p_language_id, v_score, v_total_questions,
    v_attempt_number, v_is_first_attempt,
    CASE WHEN v_is_first_attempt THEN v_user_elo ELSE NULL END,
    CASE WHEN v_is_first_attempt THEN v_new_user_elo ELSE NULL END,
    CASE WHEN v_is_first_attempt THEN v_test_elo ELSE NULL END,
    CASE WHEN v_is_first_attempt THEN v_new_test_elo ELSE NULL END,
    CASE WHEN p_was_free_test THEN 0 ELSE v_tokens_cost END,
    p_was_free_test, p_idempotency_key
  )
  RETURNING id INTO v_attempt_id;

  INSERT INTO user_languages (user_id, language_id, total_tests_taken, last_test_date)
  VALUES (p_user_id, p_language_id, 1, CURRENT_DATE)
  ON CONFLICT (user_id, language_id)
  DO UPDATE SET total_tests_taken = user_languages.total_tests_taken + 1,
    last_test_date = CURRENT_DATE, updated_at = NOW();

  RETURN jsonb_build_object(
    'success', true, 'attempt_id', v_attempt_id, 'attempt_number', v_attempt_number,
    'is_first_attempt', v_is_first_attempt, 'user_elo_before', v_user_elo,
    'user_elo_after', v_new_user_elo, 'user_elo_change', v_new_user_elo - v_user_elo,
    'test_elo_before', v_test_elo, 'test_elo_after', v_new_test_elo,
    'test_elo_change', CASE WHEN v_is_first_attempt THEN v_new_test_elo - v_test_elo ELSE 0 END,
    'tokens_cost', CASE WHEN p_was_free_test THEN 0 ELSE v_tokens_cost END,
    'score', v_score, 'total_questions', v_total_questions, 'percentage', v_percentage,
    'question_results', v_question_results,
    'message', CASE WHEN v_is_first_attempt THEN 'First attempt - ELO updated' ELSE 'Retake - ELO unchanged' END
  );

EXCEPTION WHEN OTHERS THEN
  RETURN jsonb_build_object('success', false, 'error', SQLERRM, 'error_detail', SQLSTATE);
END;$function$;

CREATE OR REPLACE FUNCTION public.tests_containing_sense(p_sense_id integer, p_language_id integer)
 RETURNS TABLE(id uuid, transcript text, difficulty numeric, vocab_token_map jsonb)
 LANGUAGE sql
 STABLE
AS $function$
    SELECT t.id, t.transcript, t.difficulty, t.vocab_token_map
    FROM tests t
    JOIN dim_languages dl ON dl.id = p_language_id
    WHERE t.vocab_sense_ids @> ARRAY[p_sense_id]
      AND t.language_id = p_language_id
      AND t.is_active = TRUE;
$function$;

CREATE OR REPLACE FUNCTION public.update_skill_attempts_count()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    UPDATE test_skill_ratings
    SET
        total_attempts = (
            SELECT COUNT(*)
            FROM test_attempts
            WHERE test_id = NEW.test_id
            AND test_type_id = test_skill_ratings.test_type_id
        ),
        updated_at = NOW()
    WHERE test_id = NEW.test_id
    AND test_type_id = NEW.test_type_id;
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.update_test_attempts_count()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    UPDATE public.tests
    SET total_attempts = (
        SELECT COUNT(*)
        FROM public.test_attempts
        WHERE test_id = NEW.test_id
    )
    WHERE id = NEW.test_id;
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.update_user_vocab_stats()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.total_senses_tracked := (
    SELECT COUNT(*) FROM jsonb_object_keys(NEW.sense_learning_stats)
  );
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.update_vocabulary_from_test(p_user_id uuid, p_language_id smallint, p_question_results jsonb)
 RETURNS TABLE(out_sense_id integer, out_p_known_before numeric, out_p_known_after numeric, out_status text)
 LANGUAGE plpgsql
AS $function$
BEGIN
    RETURN QUERY
    WITH question_senses AS (
        SELECT
            unnest(q.sense_ids) AS sense_id,
            (qr->>'is_correct')::boolean AS is_correct
        FROM jsonb_array_elements(p_question_results) qr
        JOIN questions q ON q.id = (qr->>'question_id')::uuid
        WHERE q.sense_ids IS NOT NULL
          AND array_length(q.sense_ids, 1) > 0
    ),
    deduped AS (
        SELECT qs.sense_id, bool_or(qs.is_correct) AS is_correct
        FROM question_senses qs
        GROUP BY qs.sense_id
    ),
    current_state AS (
        SELECT
            d.sense_id,
            d.is_correct,
            COALESCE(
                uvk.p_known,
                CASE
                    WHEN dv.frequency_rank IS NULL THEN 0.10
                    WHEN dv.frequency_rank >= 6.0 THEN 0.85
                    WHEN dv.frequency_rank >= 5.0 THEN 0.65
                    WHEN dv.frequency_rank >= 4.0 THEN 0.35
                    WHEN dv.frequency_rank >= 3.0 THEN 0.15
                    ELSE 0.05
                END
            ) AS p_current
        FROM deduped d
        JOIN dim_word_senses dws ON dws.id = d.sense_id
        JOIN dim_vocabulary dv ON dv.id = dws.vocab_id
        LEFT JOIN user_vocabulary_knowledge uvk
            ON uvk.user_id = p_user_id AND uvk.sense_id = d.sense_id
    ),
    updated AS (
        SELECT
            cs.sense_id,
            cs.p_current AS p_before,
            bkt_update_comprehension(cs.p_current, cs.is_correct) AS p_after,
            cs.is_correct
        FROM current_state cs
    ),
    upserted AS (
        INSERT INTO user_vocabulary_knowledge
            (user_id, sense_id, language_id, p_known, status,
             evidence_count, comprehension_correct, comprehension_wrong,
             last_evidence_at, updated_at)
        SELECT
            p_user_id, u.sense_id, p_language_id,
            u.p_after, bkt_status(u.p_after),
            1,
            CASE WHEN u.is_correct THEN 1 ELSE 0 END,
            CASE WHEN u.is_correct THEN 0 ELSE 1 END,
            NOW(), NOW()
        FROM updated u
        ON CONFLICT (user_id, sense_id) DO UPDATE SET
            p_known = EXCLUDED.p_known,
            status = CASE
                WHEN user_vocabulary_knowledge.status = 'user_marked_unknown'
                THEN 'user_marked_unknown'
                ELSE EXCLUDED.status
            END,
            evidence_count = user_vocabulary_knowledge.evidence_count + 1,
            comprehension_correct = user_vocabulary_knowledge.comprehension_correct + EXCLUDED.comprehension_correct,
            comprehension_wrong = user_vocabulary_knowledge.comprehension_wrong + EXCLUDED.comprehension_wrong,
            last_evidence_at = NOW(),
            updated_at = NOW()
        RETURNING sense_id, p_known, status
    )
    SELECT
        upserted.sense_id,
        COALESCE(u.p_before, 0.10),
        upserted.p_known,
        upserted.status
    FROM upserted
    LEFT JOIN updated u ON u.sense_id = upserted.sense_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.update_vocabulary_from_word_test(p_user_id uuid, p_sense_id integer, p_is_correct boolean, p_language_id smallint)
 RETURNS TABLE(out_sense_id integer, out_p_known_before numeric, out_p_known_after numeric, out_status text)
 LANGUAGE plpgsql
AS $function$
DECLARE
    v_p_current NUMERIC;
    v_p_new NUMERIC;
    v_status TEXT;
BEGIN
    SELECT COALESCE(uvk.p_known,
        CASE
            WHEN dv.frequency_rank IS NULL THEN 0.10
            WHEN dv.frequency_rank >= 6.0 THEN 0.85
            WHEN dv.frequency_rank >= 5.0 THEN 0.65
            WHEN dv.frequency_rank >= 4.0 THEN 0.35
            WHEN dv.frequency_rank >= 3.0 THEN 0.15
            ELSE 0.05
        END
    ) INTO v_p_current
    FROM dim_word_senses dws
    JOIN dim_vocabulary dv ON dv.id = dws.vocab_id
    LEFT JOIN user_vocabulary_knowledge uvk
        ON uvk.user_id = p_user_id AND uvk.sense_id = p_sense_id
    WHERE dws.id = p_sense_id;

    IF v_p_current IS NULL THEN
        v_p_current := 0.10;
    END IF;

    v_p_new := bkt_update_word_test(v_p_current, p_is_correct);
    v_status := bkt_status(v_p_new);

    INSERT INTO user_vocabulary_knowledge
        (user_id, sense_id, language_id, p_known, status,
         evidence_count, word_test_correct, word_test_wrong,
         last_evidence_at, updated_at)
    VALUES (
        p_user_id, p_sense_id, p_language_id,
        v_p_new, v_status,
        1,
        CASE WHEN p_is_correct THEN 1 ELSE 0 END,
        CASE WHEN p_is_correct THEN 0 ELSE 1 END,
        NOW(), NOW()
    )
    ON CONFLICT (user_id, sense_id) DO UPDATE SET
        p_known = EXCLUDED.p_known,
        status = CASE
            WHEN user_vocabulary_knowledge.status = 'user_marked_unknown'
            THEN 'user_marked_unknown'
            ELSE EXCLUDED.status
        END,
        evidence_count = user_vocabulary_knowledge.evidence_count + 1,
        word_test_correct = user_vocabulary_knowledge.word_test_correct + EXCLUDED.word_test_correct,
        word_test_wrong = user_vocabulary_knowledge.word_test_wrong + EXCLUDED.word_test_wrong,
        last_evidence_at = NOW(),
        updated_at = NOW();

    RETURN QUERY SELECT p_sense_id, v_p_current, v_p_new, v_status;
END;
$function$;

-- ============================================================================
-- Triggers
-- ============================================================================

-- updated_at triggers
CREATE TRIGGER update_vocab_timestamp
    BEFORE UPDATE ON public.dim_vocabulary
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_sense_timestamp
    BEFORE UPDATE ON public.dim_word_senses
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_tests_updated_at
    BEFORE UPDATE ON public.tests
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_user_languages_updated_at
    BEFORE UPDATE ON public.user_languages
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_user_reports_updated_at
    BEFORE UPDATE ON public.user_reports
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_user_skill_ratings_updated_at
    BEFORE UPDATE ON public.user_skill_ratings
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_users_updated_at
    BEFORE UPDATE ON public.users
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- test_attempts triggers
CREATE TRIGGER trigger_increment_test_attempts
    AFTER INSERT ON public.test_attempts
    FOR EACH ROW EXECUTE FUNCTION update_test_attempts_count();

CREATE TRIGGER trigger_update_skill_attempts
    AFTER INSERT ON public.test_attempts
    FOR EACH ROW EXECUTE FUNCTION update_skill_attempts_count();

CREATE TRIGGER update_skill_attempts_count_trigger
    AFTER INSERT ON public.test_attempts
    FOR EACH ROW EXECUTE FUNCTION update_skill_attempts_count();

-- user creation trigger
CREATE TRIGGER create_user_dependencies_trigger
    AFTER INSERT ON public.users
    FOR EACH ROW EXECUTE FUNCTION create_user_dependencies();

-- ============================================================================
-- Grants
-- ============================================================================

GRANT EXECUTE ON FUNCTION public.process_test_submission TO authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_elo_rating TO authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_volatility_multiplier TO authenticated;

-- ============================================================================
-- End of LinguaLoop Live Schema
-- ============================================================================
