-- ============================================================================
-- LinguaLoop Live Database Schema
-- Extracted from live Supabase instance + GitHub migration files
-- Date: 2026-03-16
--
-- Sources:
--   1. Live Supabase API column probes (confirmed column names & types)
--   2. create_all_tables.sql (comprehensive migration, constraints/defaults)
--   3. migrations_bkt_vocabulary_tracking.sql (BKT functions, flashcards)
--   4. migrations_exercise_generation_schema.sql (exercises, grammar patterns)
--   5. migrations_test_generation_tables.sql (question types, CEFR, config)
--   6. migrations_elo_functions.sql (ELO calculation functions)
--   7. migrations_process_test_submission_v2.sql (test submission v2)
--
-- Differences from old migration schema (confirmed via live probes):
--   - users.subscription_tier text      → users.subscription_tier_id integer FK
--   - tests.language text               → tests.language_id integer FK
--   - questions.correct_answer jsonb    → questions.answer text
--   - questions.question_type text      → questions.question_type_id integer FK
--   - test_attempts.test_mode text      → test_attempts.test_type_id integer FK
--   - test_attempts.language text       → test_attempts.language_id integer FK
--   - test_attempts.elo_change removed; idempotency_key, attempt_number, is_first_attempt added
--   - test_skill_ratings.skill_type     → test_skill_ratings.test_type_id FK; volatility removed
--   - user_skill_ratings.language text  → user_skill_ratings.language_id FK
--   - user_skill_ratings.skill_type     → user_skill_ratings.test_type_id FK
--   - user_skill_ratings: volatility, current_streak, longest_streak removed
--   - user_languages.language text      → user_languages.language_id integer FK
--   - dim_languages.tts_voice_ids jsonb → text[] (live returns text array)
--   - dim_word_senses.validated_by uuid → text (live returns text, not uuid FK)
--   - exercises: added pattern_code column (live)
--   - tests: added topic_id, vocab_sense_ids, vocab_sense_stats, vocab_token_map
-- ============================================================================

-- ============================================================================
-- Extensions
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS vector;       -- pgvector for topic embeddings
CREATE EXTENSION IF NOT EXISTS pgcrypto;     -- gen_random_uuid()

-- ============================================================================
-- ENUMs
-- ============================================================================

DO $$ BEGIN
    CREATE TYPE exercise_source_type AS ENUM ('grammar', 'vocabulary', 'collocation');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

-- ============================================================================
-- Tier 0: Dimension / Reference Tables (no foreign key dependencies)
-- ============================================================================

-- ---------------------------------------------------------------------------
-- dim_status
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.dim_status (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_code     text NOT NULL UNIQUE,
    status_name     text NOT NULL,
    description     text,
    is_active       boolean DEFAULT true,
    created_at      timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- dim_languages
-- NOTE: Live data shows tts_voice_ids as text[] (not jsonb) and tts_speed as real (not numeric)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.dim_languages (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language_code           text NOT NULL UNIQUE,
    language_name           text NOT NULL,
    native_name             text,
    iso_639_1               text,
    iso_639_3               text,
    is_active               boolean DEFAULT true,
    display_order           integer DEFAULT 0,
    created_at              timestamptz DEFAULT now(),
    updated_at              timestamptz DEFAULT now(),
    prose_model             text,
    question_model          text,
    tts_voice_ids           text[],
    tts_speed               real DEFAULT 1.0,
    grammar_check_enabled   boolean DEFAULT true,
    exercise_model          text,
    exercise_sentence_model text
);

-- ---------------------------------------------------------------------------
-- dim_subscription_tiers
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.dim_subscription_tiers (
    id                          integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tier_code                   text NOT NULL UNIQUE,
    tier_name                   text NOT NULL,
    display_name                text NOT NULL,
    description                 text,
    daily_free_tests            integer NOT NULL DEFAULT 0 CHECK (daily_free_tests >= 0),
    monthly_token_grant         integer NOT NULL DEFAULT 0 CHECK (monthly_token_grant >= 0),
    tokens_per_test             integer NOT NULL DEFAULT 10 CHECK (tokens_per_test >= 0),
    can_generate_tests          boolean DEFAULT false,
    can_create_custom_tests     boolean DEFAULT false,
    can_access_analytics        boolean DEFAULT false,
    max_custom_tests            integer DEFAULT 0 CHECK (max_custom_tests >= 0),
    is_admin                    boolean DEFAULT false,
    is_moderator                boolean DEFAULT false,
    is_active                   boolean DEFAULT true,
    display_order               integer DEFAULT 0,
    created_at                  timestamptz DEFAULT now(),
    updated_at                  timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- dim_cefr_levels
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.dim_cefr_levels (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cefr_code       text NOT NULL UNIQUE,
    difficulty_min  integer NOT NULL,
    difficulty_max  integer NOT NULL,
    word_count_min  integer NOT NULL,
    word_count_max  integer NOT NULL,
    initial_elo     integer NOT NULL,
    description     text,
    created_at      timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- dim_lens
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.dim_lens (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lens_code       text NOT NULL UNIQUE,
    display_name    text NOT NULL,
    description     text,
    prompt_hint     text,
    is_active       boolean DEFAULT true,
    sort_order      integer DEFAULT 0,
    created_at      timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- dim_test_types
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.dim_test_types (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_code       text NOT NULL UNIQUE,
    type_name       text NOT NULL,
    description     text,
    category        text,
    requires_audio  boolean DEFAULT false,
    is_active       boolean DEFAULT true,
    display_order   integer DEFAULT 0,
    created_at      timestamptz DEFAULT now(),
    updated_at      timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- dim_question_types
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.dim_question_types (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_code       text NOT NULL UNIQUE,
    type_name       text NOT NULL,
    description     text,
    cognitive_level integer NOT NULL CHECK (cognitive_level >= 1 AND cognitive_level <= 3),
    is_active       boolean DEFAULT true,
    display_order   integer DEFAULT 0,
    created_at      timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- dim_prog_language
-- NOTE: Could not be verified live (returned NULL). Structure from migration.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.dim_prog_language (
    id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name        text NOT NULL UNIQUE,
    slug        text NOT NULL UNIQUE,
    icon_url    text,
    created_at  timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- dim_variable_pool
-- NOTE: Could not be verified live (returned NULL). Structure from migration.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.dim_variable_pool (
    id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    pool_name   text NOT NULL UNIQUE,
    values      jsonb NOT NULL DEFAULT '[]',
    created_at  timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- test_generation_config
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.test_generation_config (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key      text NOT NULL UNIQUE,
    config_value    text NOT NULL,
    description     text,
    updated_at      timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- test_generation_runs
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.test_generation_runs (
    id                          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_date                    date NOT NULL DEFAULT CURRENT_DATE,
    queue_items_processed       integer DEFAULT 0,
    tests_generated             integer DEFAULT 0,
    tests_failed                integer DEFAULT 0,
    prose_api_calls             integer DEFAULT 0,
    question_api_calls          integer DEFAULT 0,
    audio_api_calls             integer DEFAULT 0,
    grammar_checks_performed    integer DEFAULT 0,
    total_cost_usd              real DEFAULT 0,
    execution_time_seconds      integer,
    error_message               text,
    created_at                  timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- app_error_logs
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.app_error_logs (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    error_type      text NOT NULL,
    error_message   text NOT NULL,
    url             text,
    user_id         uuid,
    metadata        jsonb,
    created_at      timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- users_backup
-- NOTE: Could not be verified live (returned NULL). Structure from migration.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.users_backup (
    id              uuid,
    email           text,
    created_at      timestamptz,
    updated_at      timestamptz,
    last_login      timestamptz,
    display_name    text,
    native_language text,
    target_languages jsonb,
    timezone        text,
    is_active       boolean,
    email_verified  boolean
);

-- ============================================================================
-- Tier 1: Depends on Tier 0 only
-- ============================================================================

-- ---------------------------------------------------------------------------
-- organizations
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.organizations (
    id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name                    text NOT NULL,
    slug                    text NOT NULL UNIQUE,
    subscription_tier_id    integer NOT NULL REFERENCES public.dim_subscription_tiers(id),
    max_users               integer,
    token_pool              integer DEFAULT 0 CHECK (token_pool >= 0),
    is_active               boolean DEFAULT true,
    created_at              timestamptz DEFAULT now(),
    updated_at              timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- categories
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.categories (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    text NOT NULL,
    description             text,
    status_id               integer DEFAULT 2 REFERENCES public.dim_status(id),
    target_language_id      integer REFERENCES public.dim_languages(id),
    cooldown_days           integer DEFAULT 7,
    last_used_at            timestamptz,
    total_topics_generated  integer DEFAULT 0,
    created_at              timestamptz DEFAULT now(),
    updated_at              timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- dim_library
-- NOTE: Could not be verified live (returned NULL). Structure from migration.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.dim_library (
    id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    language_id     bigint NOT NULL REFERENCES public.dim_prog_language(id),
    name            text NOT NULL,
    version         text,
    doc_base_url    text,
    created_at      timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- dim_vocabulary
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.dim_vocabulary (
    id                  integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    language_id         integer NOT NULL REFERENCES public.dim_languages(id),
    lemma               text NOT NULL,
    phrase_type         text DEFAULT 'single_word',
    component_lemmas    text[],
    part_of_speech      text,
    frequency_rank      real,
    created_at          timestamptz DEFAULT now(),
    updated_at          timestamptz DEFAULT now(),
    level_tag           text
);

-- ---------------------------------------------------------------------------
-- dim_grammar_patterns
-- NOTE: Confirmed to exist live but returned empty. Structure from migration.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.dim_grammar_patterns (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pattern_code            text NOT NULL UNIQUE,
    pattern_name            text NOT NULL,
    description             text NOT NULL,
    user_facing_description text NOT NULL,
    example_sentence        text NOT NULL,
    example_sentence_en     text,
    language_id             integer NOT NULL REFERENCES public.dim_languages(id),
    cefr_level              text NOT NULL CHECK (cefr_level IN ('A1','A2','B1','B2','C1','C2')),
    category                text NOT NULL CHECK (category IN (
                                'tense','aspect','voice','particles','word_order','modality',
                                'clause_structure','conjugation','honorifics','measure_words','complement'
                            )),
    is_active               boolean NOT NULL DEFAULT true,
    created_at              timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- question_type_distributions
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.question_type_distributions (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    difficulty          integer NOT NULL UNIQUE CHECK (difficulty >= 1 AND difficulty <= 9),
    question_type_1     text NOT NULL REFERENCES public.dim_question_types(type_code),
    question_type_2     text NOT NULL REFERENCES public.dim_question_types(type_code),
    question_type_3     text NOT NULL REFERENCES public.dim_question_types(type_code),
    question_type_4     text NOT NULL REFERENCES public.dim_question_types(type_code),
    question_type_5     text NOT NULL REFERENCES public.dim_question_types(type_code),
    created_at          timestamptz DEFAULT now(),
    updated_at          timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- prompt_templates
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.prompt_templates (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_name       text NOT NULL,
    template_text   text NOT NULL,
    version         integer DEFAULT 1,
    is_active       boolean DEFAULT true,
    description     text,
    created_at      timestamptz DEFAULT now(),
    updated_at      timestamptz DEFAULT now(),
    language_id     integer NOT NULL REFERENCES public.dim_languages(id),
    UNIQUE (task_name, language_id, version)
);

-- ============================================================================
-- Tier 2: Depends on Tier 0-1
-- ============================================================================

-- ---------------------------------------------------------------------------
-- users
-- NOTE: Live confirmed subscription_tier_id (integer FK) replaces old subscription_tier (text)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.users (
    id                      uuid PRIMARY KEY,
    email                   text NOT NULL UNIQUE,
    display_name            text,
    email_verified          boolean DEFAULT false,
    total_tests_taken       integer DEFAULT 0,
    total_tests_generated   integer DEFAULT 0,
    last_activity_at        timestamptz,
    last_free_test_date     date DEFAULT (CURRENT_DATE - interval '1 day'),
    free_tests_used_today   integer DEFAULT 0,
    total_free_tests_used   integer DEFAULT 0,
    created_at              timestamptz DEFAULT now(),
    updated_at              timestamptz DEFAULT now(),
    last_login              timestamptz DEFAULT now(),
    subscription_tier_id    integer NOT NULL DEFAULT 1 REFERENCES public.dim_subscription_tiers(id),
    deleted_at              timestamptz,
    anonymized_at           timestamptz,
    organization_id         uuid REFERENCES public.organizations(id),
    CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);

-- ---------------------------------------------------------------------------
-- dim_block
-- NOTE: Could not be verified live (returned NULL). Structure from migration.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.dim_block (
    id                  bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    library_id          bigint NOT NULL REFERENCES public.dim_library(id),
    name                text NOT NULL,
    qualified_name      text NOT NULL UNIQUE,
    syntax_template     text NOT NULL,
    description         text,
    difficulty          integer DEFAULT 1 CHECK (difficulty >= 1 AND difficulty <= 5),
    created_at          timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- topics
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.topics (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    category_id         integer NOT NULL REFERENCES public.categories(id),
    concept_english     text NOT NULL,
    lens_id             integer NOT NULL REFERENCES public.dim_lens(id),
    keywords            text[],
    embedding           vector(1536),
    semantic_signature  text,
    created_at          timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- daily_test_loads
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.daily_test_loads (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             uuid NOT NULL REFERENCES public.users(id),
    language_id         integer NOT NULL REFERENCES public.dim_languages(id),
    load_date           date NOT NULL DEFAULT CURRENT_DATE,
    test_ids            jsonb NOT NULL,
    completed_test_ids  jsonb DEFAULT '[]',
    created_at          timestamptz DEFAULT now()
);

-- ============================================================================
-- Tier 3: Depends on Tier 0-2
-- ============================================================================

-- ---------------------------------------------------------------------------
-- organization_members
-- NOTE: Could not be verified live (returned NULL). Structure from migration.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.organization_members (
    organization_id     uuid NOT NULL REFERENCES public.organizations(id),
    user_id             uuid NOT NULL REFERENCES public.users(id),
    role                text NOT NULL DEFAULT 'student' CHECK (role IN ('student','teacher','admin','owner')),
    joined_at           timestamptz DEFAULT now(),
    PRIMARY KEY (organization_id, user_id)
);

-- ---------------------------------------------------------------------------
-- dim_word_senses
-- NOTE: Live shows validated_by as text (not uuid FK). Adjusted accordingly.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.dim_word_senses (
    id                      integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    vocab_id                integer NOT NULL REFERENCES public.dim_vocabulary(id),
    definition_language_id  integer NOT NULL REFERENCES public.dim_languages(id),
    definition              text NOT NULL,
    pronunciation           text,
    example_sentence        text,
    usage_notes             text,
    sense_rank              integer NOT NULL DEFAULT 1,
    usage_frequency         text DEFAULT 'common' CHECK (usage_frequency IN ('common','uncommon','rare','archaic')),
    semantic_category       text,
    is_validated            boolean DEFAULT false,
    validated_by            text,
    validation_notes        text,
    created_at              timestamptz DEFAULT now(),
    updated_at              timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- user_languages
-- NOTE: Live confirmed language_id (integer FK) replaces old language (text)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.user_languages (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         uuid NOT NULL REFERENCES public.users(id),
    total_tests_taken integer DEFAULT 0,
    last_test_date  date,
    created_at      timestamptz DEFAULT now(),
    updated_at      timestamptz DEFAULT now(),
    language_id     integer NOT NULL REFERENCES public.dim_languages(id),
    UNIQUE (user_id, language_id)
);

-- ---------------------------------------------------------------------------
-- user_tokens
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.user_tokens (
    user_id                         uuid PRIMARY KEY REFERENCES public.users(id),
    purchased_tokens                integer DEFAULT 0 CHECK (purchased_tokens >= 0),
    bonus_tokens                    integer DEFAULT 0 CHECK (bonus_tokens >= 0),
    total_tokens_earned             integer DEFAULT 0,
    total_tokens_spent              integer DEFAULT 0,
    total_tokens_purchased          integer DEFAULT 0,
    tokens_spent_tests              integer DEFAULT 0,
    tokens_spent_generation         integer DEFAULT 0,
    tokens_spent_premium_features   integer DEFAULT 0,
    referral_tokens_earned          integer DEFAULT 0,
    achievement_tokens_earned       integer DEFAULT 0,
    created_at                      timestamptz DEFAULT now(),
    updated_at                      timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- user_vocabulary
-- NOTE: Could not be verified live (returned NULL). Structure from migration.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.user_vocabulary (
    id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id                 uuid NOT NULL REFERENCES public.users(id),
    language_id             integer NOT NULL REFERENCES public.dim_languages(id),
    known_sense_ids         integer[] DEFAULT '{}',
    sense_learning_stats    jsonb DEFAULT '{}',
    bootstrap_source        text,
    bootstrap_date          timestamptz,
    total_senses_tracked    integer DEFAULT 0,
    last_updated_at         timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- user_skill_ratings
-- NOTE: Live confirmed language_id/test_type_id FKs. Volatility, streaks removed.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.user_skill_ratings (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         uuid NOT NULL REFERENCES public.users(id),
    elo_rating      integer DEFAULT 1200 CHECK (elo_rating >= 400 AND elo_rating <= 3000),
    tests_taken     integer DEFAULT 0 CHECK (tests_taken >= 0),
    last_test_date  date,
    created_at      timestamptz DEFAULT now(),
    updated_at      timestamptz DEFAULT now(),
    language_id     integer NOT NULL REFERENCES public.dim_languages(id),
    test_type_id    integer NOT NULL REFERENCES public.dim_test_types(id),
    UNIQUE (user_id, language_id, test_type_id)
);

-- ---------------------------------------------------------------------------
-- flagged_content
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.flagged_content (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id             uuid REFERENCES public.users(id),
    content_hash        text NOT NULL,
    content_type        text NOT NULL,
    flagged_categories  jsonb,
    created_at          timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- tests
-- NOTE: Live confirmed language_id FK, topic_id FK, vocab_sense_ids, vocab_sense_stats, vocab_token_map
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.tests (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    gen_user            uuid NOT NULL REFERENCES public.users(id),
    slug                text NOT NULL UNIQUE,
    difficulty          integer NOT NULL CHECK (difficulty >= 1 AND difficulty <= 9),
    style               text DEFAULT 'academic' CHECK (style IN ('academic','conversational','business','casual','technical')),
    tier                text NOT NULL DEFAULT 'free-tier' CHECK (tier IN ('free-tier','premium-tier','enterprise-tier')),
    title               text,
    transcript          text,
    audio_url           text,
    total_attempts      integer DEFAULT 0,
    is_active           boolean DEFAULT true,
    is_featured         boolean DEFAULT false,
    is_custom           boolean DEFAULT false,
    generation_model    text DEFAULT 'gpt-4.1-nano',
    audio_generated     boolean DEFAULT false,
    created_at          timestamptz DEFAULT now(),
    updated_at          timestamptz DEFAULT now(),
    language_id         integer NOT NULL REFERENCES public.dim_languages(id),
    organization_id     uuid REFERENCES public.organizations(id),
    topic_id            uuid REFERENCES public.topics(id),
    vocab_sense_ids     integer[] DEFAULT '{}',
    vocab_sense_stats   jsonb DEFAULT '{}',
    vocab_token_map     jsonb
);

-- ---------------------------------------------------------------------------
-- dim_question_template
-- NOTE: Could not be verified live (returned NULL). Structure from migration.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.dim_question_template (
    id                  bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    block_id            bigint NOT NULL REFERENCES public.dim_block(id),
    question_pattern    text NOT NULL,
    answer_pattern      text NOT NULL,
    variable_config     jsonb NOT NULL DEFAULT '{}',
    created_at          timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- production_queue
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.production_queue (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    topic_id            uuid NOT NULL REFERENCES public.topics(id),
    language_id         integer NOT NULL REFERENCES public.dim_languages(id),
    status_id           integer DEFAULT 1 REFERENCES public.dim_status(id),
    rejection_reason    text,
    processed_at        timestamptz,
    created_at          timestamptz DEFAULT now(),
    tests_generated     integer DEFAULT 0,
    error_log           text
);

-- ---------------------------------------------------------------------------
-- topic_generation_runs
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.topic_generation_runs (
    id                              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_date                        date NOT NULL,
    category_id                     integer REFERENCES public.categories(id),
    category_name                   text,
    topics_generated                integer DEFAULT 0,
    topics_rejected_similarity      integer DEFAULT 0,
    topics_rejected_gatekeeper      integer DEFAULT 0,
    candidates_proposed             integer DEFAULT 0,
    api_calls_llm                   integer DEFAULT 0,
    api_calls_embedding             integer DEFAULT 0,
    total_cost_usd                  real DEFAULT 0,
    execution_time_seconds          integer,
    error_message                   text,
    created_at                      timestamptz DEFAULT now()
);

-- ============================================================================
-- Tier 4: Depends on Tier 0-3
-- ============================================================================

-- ---------------------------------------------------------------------------
-- exercises
-- NOTE: Live data includes pattern_code column not in original migration
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.exercises (
    id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    language_id             integer NOT NULL REFERENCES public.dim_languages(id),
    exercise_type           text NOT NULL,
    source_type             text NOT NULL,
    grammar_pattern_id      integer REFERENCES public.dim_grammar_patterns(id),
    word_sense_id           integer REFERENCES public.dim_word_senses(id),
    corpus_collocation_id   integer,
    content                 jsonb NOT NULL,
    tags                    jsonb NOT NULL DEFAULT '{}',
    difficulty_static       real,
    irt_difficulty          real NOT NULL DEFAULT 0.0,
    irt_discrimination      real NOT NULL DEFAULT 1.0,
    cefr_level              text CHECK (cefr_level IN ('A1','A2','B1','B2','C1','C2')),
    attempt_count           integer NOT NULL DEFAULT 0,
    correct_count           integer NOT NULL DEFAULT 0,
    is_active               boolean NOT NULL DEFAULT true,
    generation_batch_id     uuid,
    created_at              timestamptz NOT NULL DEFAULT now(),
    pattern_code            text,
    CONSTRAINT chk_source_fk CHECK (
        (grammar_pattern_id IS NOT NULL)::int +
        (word_sense_id IS NOT NULL)::int +
        (corpus_collocation_id IS NOT NULL)::int = 1
    )
);

-- ---------------------------------------------------------------------------
-- questions
-- NOTE: Live confirmed answer as text (not jsonb), question_type_id FK, sense_ids array
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.questions (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    test_id             uuid NOT NULL REFERENCES public.tests(id),
    question_id         text NOT NULL,
    question_text       text NOT NULL,
    choices             jsonb,
    answer              text NOT NULL,
    answer_explanation  text,
    points              integer DEFAULT 1,
    audio_url           text,
    created_at          timestamptz DEFAULT now(),
    updated_at          timestamptz DEFAULT now(),
    question_type_id    integer REFERENCES public.dim_question_types(id),
    sense_ids           integer[]
);

-- ---------------------------------------------------------------------------
-- test_attempts
-- NOTE: Live confirmed language_id/test_type_id FKs, idempotency_key, attempt_number, is_first_attempt
--       elo_change column removed in live
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.test_attempts (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id             uuid NOT NULL REFERENCES public.users(id),
    test_id             uuid NOT NULL REFERENCES public.tests(id),
    score               integer NOT NULL CHECK (score >= 0),
    total_questions     integer NOT NULL CHECK (total_questions > 0),
    percentage          real CHECK (percentage >= 0 AND percentage <= 100),
    user_elo_before     integer NOT NULL,
    test_elo_before     integer NOT NULL,
    user_elo_after      integer NOT NULL,
    test_elo_after      integer NOT NULL,
    was_free_test       boolean NOT NULL DEFAULT false,
    tokens_consumed     integer NOT NULL DEFAULT 0 CHECK (tokens_consumed >= 0),
    created_at          timestamptz DEFAULT now(),
    language_id         integer NOT NULL REFERENCES public.dim_languages(id),
    test_type_id        integer NOT NULL REFERENCES public.dim_test_types(id),
    idempotency_key     text,
    attempt_number      integer DEFAULT 1,
    is_first_attempt    boolean DEFAULT true
);

-- ---------------------------------------------------------------------------
-- test_skill_ratings
-- NOTE: Live confirmed test_type_id FK. volatility column removed.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.test_skill_ratings (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    test_id         uuid NOT NULL REFERENCES public.tests(id),
    elo_rating      integer DEFAULT 1400 CHECK (elo_rating >= 400 AND elo_rating <= 3000),
    total_attempts  integer DEFAULT 0 CHECK (total_attempts >= 0),
    created_at      timestamptz DEFAULT now(),
    updated_at      timestamptz DEFAULT now(),
    test_type_id    integer NOT NULL REFERENCES public.dim_test_types(id),
    UNIQUE (test_id, test_type_id)
);

-- ---------------------------------------------------------------------------
-- user_reports (from migration; not probed live but likely exists)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.user_reports (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id             uuid NOT NULL REFERENCES public.users(id),
    report_category     text NOT NULL CHECK (report_category IN (
                            'test_answer_incorrect','test_load_error','website_crash',
                            'improvement_idea','audio_quality','other'
                        )),
    description         text NOT NULL,
    current_page        text,
    test_id             uuid REFERENCES public.tests(id),
    test_type           text,
    user_agent          text,
    screen_resolution   text,
    status              text DEFAULT 'pending' CHECK (status IN ('pending','reviewing','resolved','dismissed')),
    created_at          timestamptz DEFAULT now(),
    updated_at          timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- user_flashcards
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.user_flashcards (
    id              integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id         uuid NOT NULL REFERENCES public.users(id),
    sense_id        integer NOT NULL REFERENCES public.dim_word_senses(id),
    language_id     integer NOT NULL REFERENCES public.dim_languages(id),
    stability       real DEFAULT 0,
    difficulty      real DEFAULT 0.3,
    due_date        date,
    last_review     timestamptz,
    reps            integer DEFAULT 0,
    lapses          integer DEFAULT 0,
    state           text DEFAULT 'new' CHECK (state IN ('new','learning','review','relearning')),
    example_sentence text,
    audio_url       text,
    created_at      timestamptz DEFAULT now(),
    updated_at      timestamptz DEFAULT now(),
    UNIQUE (user_id, sense_id)
);

-- ---------------------------------------------------------------------------
-- user_vocabulary_knowledge
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.user_vocabulary_knowledge (
    id                      integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id                 uuid NOT NULL REFERENCES public.users(id),
    sense_id                integer NOT NULL REFERENCES public.dim_word_senses(id),
    language_id             integer NOT NULL REFERENCES public.dim_languages(id),
    p_known                 real NOT NULL DEFAULT 0.10,
    status                  text NOT NULL DEFAULT 'unknown' CHECK (status IN (
                                'unknown','encountered','learning','probably_known','known','user_marked_unknown'
                            )),
    evidence_count          integer DEFAULT 0,
    comprehension_correct   integer DEFAULT 0,
    comprehension_wrong     integer DEFAULT 0,
    word_test_correct       integer DEFAULT 0,
    word_test_wrong         integer DEFAULT 0,
    last_evidence_at        timestamptz,
    created_at              timestamptz DEFAULT now(),
    updated_at              timestamptz DEFAULT now(),
    UNIQUE (user_id, sense_id)
);

-- ---------------------------------------------------------------------------
-- vocabulary_review_queue (from migration; not probed live but likely exists)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.vocabulary_review_queue (
    id                  bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    vocab_id            integer NOT NULL REFERENCES public.dim_vocabulary(id),
    sense_id            integer REFERENCES public.dim_word_senses(id),
    issue_type          text NOT NULL CHECK (issue_type IN (
                            'validation_failed','duplicate_suspected','definition_unclear',
                            'offensive_content','llm_error'
                        )),
    proposed_definition text,
    failure_reason      text,
    context_sentence    text,
    status              text DEFAULT 'pending' CHECK (status IN ('pending','reviewing','resolved','dismissed')),
    reviewed_by         uuid REFERENCES public.users(id),
    resolution_notes    text,
    resolved_at         timestamptz,
    created_at          timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- exercise_attempts (from migration; not probed live but likely exists)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.exercise_attempts (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         uuid NOT NULL REFERENCES public.users(id),
    exercise_id     uuid REFERENCES public.exercises(id),
    user_response   jsonb,
    is_correct      boolean NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now()
);

-- ============================================================================
-- Tier 5: Depends on Tier 0-4
-- ============================================================================

-- ---------------------------------------------------------------------------
-- token_transactions
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.token_transactions (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id             uuid NOT NULL REFERENCES public.users(id),
    tokens_consumed     integer DEFAULT 0 CHECK (tokens_consumed >= 0),
    tokens_added        integer DEFAULT 0 CHECK (tokens_added >= 0),
    token_balance_after integer NOT NULL CHECK (token_balance_after >= 0),
    action              text NOT NULL,
    payment_intent_id   text,
    package_id          text,
    test_id             uuid REFERENCES public.tests(id),
    attempt_id          uuid REFERENCES public.test_attempts(id),
    is_valid            boolean DEFAULT true,
    invalidated_at      timestamptz,
    invalidation_reason text,
    created_by_system   boolean DEFAULT true,
    created_at          timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- word_quiz_results
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.word_quiz_results (
    id              integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id         uuid NOT NULL REFERENCES public.users(id),
    attempt_id      uuid REFERENCES public.test_attempts(id),
    sense_id        integer NOT NULL REFERENCES public.dim_word_senses(id),
    is_correct      boolean NOT NULL,
    selected_answer text,
    correct_answer  text,
    response_time_ms integer,
    created_at      timestamptz DEFAULT now()
);

-- ============================================================================
-- Indexes
-- ============================================================================

-- dim_grammar_patterns
CREATE INDEX IF NOT EXISTS idx_grammar_patterns_language ON public.dim_grammar_patterns(language_id);
CREATE INDEX IF NOT EXISTS idx_grammar_patterns_cefr     ON public.dim_grammar_patterns(cefr_level);
CREATE INDEX IF NOT EXISTS idx_grammar_patterns_active   ON public.dim_grammar_patterns(is_active) WHERE is_active = TRUE;

-- dim_vocabulary
CREATE INDEX IF NOT EXISTS idx_dv_level_tag ON public.dim_vocabulary(level_tag);

-- exercises
CREATE INDEX IF NOT EXISTS idx_exercises_language    ON public.exercises(language_id);
CREATE INDEX IF NOT EXISTS idx_exercises_type        ON public.exercises(exercise_type);
CREATE INDEX IF NOT EXISTS idx_exercises_source      ON public.exercises(source_type);
CREATE INDEX IF NOT EXISTS idx_exercises_grammar     ON public.exercises(grammar_pattern_id) WHERE grammar_pattern_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_exercises_sense       ON public.exercises(word_sense_id) WHERE word_sense_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_exercises_collocation ON public.exercises(corpus_collocation_id) WHERE corpus_collocation_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_exercises_cefr        ON public.exercises(cefr_level);
CREATE INDEX IF NOT EXISTS idx_exercises_active      ON public.exercises(is_active) WHERE is_active = TRUE;
CREATE INDEX IF NOT EXISTS idx_exercises_tags_gin    ON public.exercises USING GIN (tags);
CREATE INDEX IF NOT EXISTS idx_exercises_content_gin ON public.exercises USING GIN (content);

-- exercise_attempts
CREATE INDEX IF NOT EXISTS idx_ea_exercise_id        ON public.exercise_attempts(exercise_id);
CREATE INDEX IF NOT EXISTS idx_ea_user_response_gin  ON public.exercise_attempts USING GIN (user_response);

-- questions
CREATE INDEX IF NOT EXISTS idx_questions_type ON public.questions(question_type_id);

-- test_generation_runs
CREATE INDEX IF NOT EXISTS idx_test_generation_runs_date ON public.test_generation_runs(run_date);

-- user_vocabulary_knowledge
CREATE INDEX IF NOT EXISTS idx_uvk_user_language ON public.user_vocabulary_knowledge(user_id, language_id);
CREATE INDEX IF NOT EXISTS idx_uvk_user_status   ON public.user_vocabulary_knowledge(user_id, status);
CREATE INDEX IF NOT EXISTS idx_uvk_user_pknown   ON public.user_vocabulary_knowledge(user_id, p_known);

-- user_flashcards
CREATE INDEX IF NOT EXISTS idx_uf_user_due   ON public.user_flashcards(user_id, language_id, due_date);
CREATE INDEX IF NOT EXISTS idx_uf_user_state ON public.user_flashcards(user_id, state);

-- word_quiz_results
CREATE INDEX IF NOT EXISTS idx_wqr_user    ON public.word_quiz_results(user_id);
CREATE INDEX IF NOT EXISTS idx_wqr_attempt ON public.word_quiz_results(attempt_id);

-- ============================================================================
-- Analytics Views
-- ============================================================================

CREATE OR REPLACE VIEW public.vw_distractor_error_analysis AS
SELECT
    ea.user_id,
    e.tags->>'grammar_pattern'          AS pattern_code,
    ea.user_response->>'distractor_tag' AS error_type,
    COUNT(*)                             AS error_count,
    MIN(ea.created_at)                   AS first_seen,
    MAX(ea.created_at)                   AS last_seen
FROM public.exercise_attempts ea
JOIN public.exercises e ON ea.exercise_id = e.id
WHERE ea.is_correct = FALSE
  AND ea.user_response->>'distractor_tag' IS NOT NULL
  AND e.exercise_type = 'cloze_completion'
GROUP BY 1, 2, 3;

CREATE OR REPLACE VIEW public.vw_exercise_performance_by_type AS
SELECT
    e.exercise_type,
    e.cefr_level,
    e.language_id,
    COUNT(DISTINCT e.id)             AS exercise_count,
    COUNT(ea.id)                     AS total_attempts,
    SUM(ea.is_correct::int)          AS correct_count,
    ROUND(
        SUM(ea.is_correct::int)::numeric / NULLIF(COUNT(ea.id), 0) * 100,
        1
    )                                AS accuracy_pct
FROM public.exercises e
LEFT JOIN public.exercise_attempts ea ON ea.exercise_id = e.id
WHERE e.is_active = TRUE
GROUP BY 1, 2, 3;

-- ============================================================================
-- RPC Functions: ELO Calculation
-- ============================================================================

-- ---------------------------------------------------------------------------
-- calculate_volatility_multiplier
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.calculate_volatility_multiplier(
    attempts INTEGER,
    last_date DATE DEFAULT NULL,
    base_volatility NUMERIC DEFAULT 1.0
)
RETURNS NUMERIC AS $$
DECLARE
    multiplier NUMERIC := base_volatility;
BEGIN
    IF attempts < 10 THEN
        multiplier := multiplier + 0.5;
    END IF;

    IF last_date IS NOT NULL AND (CURRENT_DATE - last_date) > 90 THEN
        multiplier := multiplier + 0.5;
    END IF;

    RETURN multiplier;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- ---------------------------------------------------------------------------
-- calculate_elo_rating
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.calculate_elo_rating(
    current_rating INTEGER,
    opposing_rating INTEGER,
    actual_score NUMERIC,
    k_factor INTEGER DEFAULT 32,
    volatility_multiplier NUMERIC DEFAULT 1.0
)
RETURNS INTEGER AS $$
DECLARE
    expected_score NUMERIC;
    adjusted_k NUMERIC;
    new_rating NUMERIC;
BEGIN
    expected_score := 1.0 / (1.0 + POWER(10, (opposing_rating - current_rating) / 400.0));
    adjusted_k := k_factor * volatility_multiplier;
    new_rating := current_rating + (adjusted_k * (actual_score - expected_score));
    RETURN GREATEST(400, LEAST(3000, ROUND(new_rating)::INTEGER));
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- ============================================================================
-- RPC Functions: Test Submission (v2 — current live version)
-- Accepts user responses as JSONB, validates answers, calculates score internally
-- ============================================================================

CREATE OR REPLACE FUNCTION public.process_test_submission(
    p_user_id UUID,
    p_test_id UUID,
    p_language_id SMALLINT,
    p_test_type_id SMALLINT,
    p_responses JSONB,
    p_was_free_test BOOLEAN DEFAULT TRUE,
    p_idempotency_key UUID DEFAULT NULL
)
RETURNS JSONB AS $$
DECLARE
    v_user_elo integer;
    v_test_elo integer;
    v_user_tests_taken integer;
    v_user_last_date date;
    v_test_attempts integer;
    v_percentage numeric;
    v_percentage_decimal numeric;
    v_new_user_elo integer;
    v_new_test_elo integer;
    v_attempt_id uuid;
    v_attempt_number integer;
    v_is_first_attempt boolean;
    v_existing_attempt record;
    v_tokens_cost integer;
    v_score integer := 0;
    v_total_questions integer := 0;
    v_question_results jsonb := '[]'::jsonb;
    v_question_record record;
    v_user_answer text;
    v_correct_answer text;
    v_is_correct boolean;
BEGIN
    -- Security: ensure caller is the user
    IF p_user_id != auth.uid() THEN
        RAISE EXCEPTION 'Unauthorized: Cannot submit test for another user';
    END IF;

    -- Input validation
    IF p_responses IS NULL OR jsonb_array_length(p_responses) = 0 THEN
        RAISE EXCEPTION 'No responses provided';
    END IF;

    -- Build temp lookup for user responses
    CREATE TEMP TABLE temp_user_responses AS
    SELECT
        (elem->>'question_id')::UUID as question_id,
        elem->>'selected_answer' as selected_answer
    FROM jsonb_array_elements(p_responses) as elem;

    -- Validate each question against the database
    FOR v_question_record IN (
        SELECT q.id, q.answer
        FROM public.questions q
        WHERE q.test_id = p_test_id
        ORDER BY q.created_at
    ) LOOP
        SELECT selected_answer INTO v_user_answer
        FROM temp_user_responses
        WHERE question_id = v_question_record.id;

        v_user_answer := COALESCE(v_user_answer, '');
        v_correct_answer := v_question_record.answer #>> '{}';
        v_is_correct := (v_user_answer = v_correct_answer);

        IF v_is_correct THEN
            v_score := v_score + 1;
        END IF;

        v_question_results := v_question_results || jsonb_build_object(
            'question_id', v_question_record.id::TEXT,
            'selected_answer', v_user_answer,
            'correct_answer', v_correct_answer,
            'is_correct', v_is_correct
        );

        v_total_questions := v_total_questions + 1;
    END LOOP;

    DROP TABLE IF EXISTS temp_user_responses;

    -- Idempotency check
    IF p_idempotency_key IS NOT NULL THEN
        SELECT * INTO v_existing_attempt
        FROM public.test_attempts
        WHERE user_id = p_user_id AND idempotency_key = p_idempotency_key::text;

        IF FOUND THEN
            RETURN jsonb_build_object(
                'success', true,
                'attempt_id', v_existing_attempt.id,
                'cached', true,
                'user_elo_change', COALESCE(
                    v_existing_attempt.user_elo_after - v_existing_attempt.user_elo_before, 0
                ),
                'message', 'Duplicate submission detected - returning cached result'
            );
        END IF;
    END IF;

    -- Token cost
    v_tokens_cost := get_test_token_cost(p_user_id);

    -- Percentage (0-100 scale)
    v_percentage := (v_score::numeric / v_total_questions::numeric) * 100;
    v_percentage_decimal := v_percentage / 100.0;

    -- Attempt number
    SELECT COUNT(*) INTO v_attempt_number
    FROM public.test_attempts
    WHERE user_id = p_user_id
      AND test_id = p_test_id
      AND test_type_id = p_test_type_id;

    v_attempt_number := v_attempt_number + 1;
    v_is_first_attempt := (v_attempt_number = 1);

    -- Get or create user ELO
    SELECT elo_rating, tests_taken, last_test_date
    INTO v_user_elo, v_user_tests_taken, v_user_last_date
    FROM public.user_skill_ratings
    WHERE user_id = p_user_id
      AND language_id = p_language_id
      AND test_type_id = p_test_type_id;

    IF NOT FOUND THEN
        v_user_elo := 1200;
        v_user_tests_taken := 0;
        v_user_last_date := NULL;

        INSERT INTO public.user_skill_ratings (
            user_id, language_id, test_type_id, elo_rating, tests_taken
        ) VALUES (
            p_user_id, p_language_id, p_test_type_id, v_user_elo, 0
        );
    END IF;

    -- Get or create test ELO
    SELECT elo_rating, total_attempts
    INTO v_test_elo, v_test_attempts
    FROM public.test_skill_ratings
    WHERE test_id = p_test_id AND test_type_id = p_test_type_id;

    IF NOT FOUND THEN
        v_test_elo := 1400;
        v_test_attempts := 0;

        INSERT INTO public.test_skill_ratings (
            test_id, test_type_id, elo_rating, total_attempts
        ) VALUES (
            p_test_id, p_test_type_id, v_test_elo, 0
        );
    END IF;

    -- ELO calculation (only for first attempts)
    IF v_is_first_attempt THEN
        DECLARE
            expected_user_score numeric;
            k_factor integer := 32;
        BEGIN
            expected_user_score := 1.0 / (1.0 + POWER(10, (v_test_elo - v_user_elo) / 400.0));
            v_new_user_elo := ROUND(v_user_elo + k_factor * (v_percentage_decimal - expected_user_score));
            v_new_test_elo := ROUND(v_test_elo + k_factor * ((1.0 - v_percentage_decimal) - (1.0 - expected_user_score)));
            v_new_user_elo := GREATEST(400, LEAST(3000, v_new_user_elo));
            v_new_test_elo := GREATEST(400, LEAST(3000, v_new_test_elo));
        END;

        UPDATE public.user_skill_ratings
        SET elo_rating = v_new_user_elo,
            tests_taken = tests_taken + 1,
            last_test_date = CURRENT_DATE,
            updated_at = NOW()
        WHERE user_id = p_user_id
          AND language_id = p_language_id
          AND test_type_id = p_test_type_id;

        UPDATE public.test_skill_ratings
        SET elo_rating = v_new_test_elo,
            total_attempts = total_attempts + 1,
            updated_at = NOW()
        WHERE test_id = p_test_id
          AND test_type_id = p_test_type_id;
    ELSE
        v_new_user_elo := v_user_elo;
        v_new_test_elo := v_test_elo;
    END IF;

    -- Insert attempt record
    INSERT INTO public.test_attempts (
        user_id, test_id, test_type_id, language_id,
        score, total_questions, attempt_number, is_first_attempt,
        user_elo_before, user_elo_after, test_elo_before, test_elo_after,
        tokens_consumed, was_free_test, idempotency_key
    ) VALUES (
        p_user_id, p_test_id, p_test_type_id, p_language_id,
        v_score, v_total_questions, v_attempt_number, v_is_first_attempt,
        v_user_elo, v_new_user_elo, v_test_elo, v_new_test_elo,
        CASE WHEN p_was_free_test THEN 0 ELSE v_tokens_cost END,
        p_was_free_test, p_idempotency_key
    )
    RETURNING id INTO v_attempt_id;

    -- Update user_languages
    INSERT INTO public.user_languages (
        user_id, language_id, total_tests_taken, last_test_date
    ) VALUES (
        p_user_id, p_language_id, 1, CURRENT_DATE
    )
    ON CONFLICT (user_id, language_id)
    DO UPDATE SET
        total_tests_taken = user_languages.total_tests_taken + 1,
        last_test_date = CURRENT_DATE,
        updated_at = NOW();

    -- Return result
    RETURN jsonb_build_object(
        'success', true,
        'attempt_id', v_attempt_id,
        'attempt_number', v_attempt_number,
        'is_first_attempt', v_is_first_attempt,
        'user_elo_before', v_user_elo,
        'user_elo_after', v_new_user_elo,
        'user_elo_change', v_new_user_elo - v_user_elo,
        'test_elo_before', v_test_elo,
        'test_elo_after', v_new_test_elo,
        'test_elo_change', CASE WHEN v_is_first_attempt THEN v_new_test_elo - v_test_elo ELSE 0 END,
        'tokens_cost', CASE WHEN p_was_free_test THEN 0 ELSE v_tokens_cost END,
        'score', v_score,
        'total_questions', v_total_questions,
        'percentage', v_percentage,
        'question_results', v_question_results,
        'message', CASE
            WHEN v_is_first_attempt THEN 'First attempt - ELO updated'
            ELSE 'Retake - ELO unchanged'
        END
    );

EXCEPTION WHEN OTHERS THEN
    RETURN jsonb_build_object(
        'success', false,
        'error', SQLERRM,
        'error_detail', SQLSTATE
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================================
-- RPC Functions: BKT (Bayesian Knowledge Tracing)
-- ============================================================================

-- ---------------------------------------------------------------------------
-- bkt_update — Core BKT posterior update
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.bkt_update(
    p_current NUMERIC,
    p_correct BOOLEAN,
    p_slip NUMERIC DEFAULT 0.10,
    p_guess NUMERIC DEFAULT 0.25
)
RETURNS NUMERIC AS $$
DECLARE
    p_obs_knows NUMERIC;
    p_obs_not_knows NUMERIC;
BEGIN
    IF p_correct THEN
        p_obs_knows := 1 - p_slip;
        p_obs_not_knows := p_guess;
    ELSE
        p_obs_knows := p_slip;
        p_obs_not_knows := 1 - p_guess;
    END IF;

    RETURN GREATEST(0.02, LEAST(0.98,
        (p_obs_knows * p_current) /
        (p_obs_knows * p_current + p_obs_not_knows * (1 - p_current))
    ));
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- ---------------------------------------------------------------------------
-- bkt_update_comprehension — Weak signal (comprehension test)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.bkt_update_comprehension(
    p_current NUMERIC,
    p_correct BOOLEAN
)
RETURNS NUMERIC AS $$
BEGIN
    RETURN bkt_update(p_current, p_correct, 0.10, 0.25);
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- ---------------------------------------------------------------------------
-- bkt_update_word_test — Strong signal (direct word quiz)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.bkt_update_word_test(
    p_current NUMERIC,
    p_correct BOOLEAN
)
RETURNS NUMERIC AS $$
BEGIN
    RETURN bkt_update(p_current, p_correct, 0.05, 0.25);
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- ---------------------------------------------------------------------------
-- bkt_status — Derive human-readable status from p_known
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.bkt_status(p_known NUMERIC)
RETURNS TEXT AS $$
BEGIN
    RETURN CASE
        WHEN p_known < 0.20 THEN 'unknown'
        WHEN p_known < 0.50 THEN 'encountered'
        WHEN p_known < 0.75 THEN 'learning'
        WHEN p_known < 0.90 THEN 'probably_known'
        ELSE 'known'
    END;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- ---------------------------------------------------------------------------
-- update_vocabulary_from_test — Batch BKT update after comprehension test
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.update_vocabulary_from_test(
    p_user_id UUID,
    p_language_id SMALLINT,
    p_question_results JSONB   -- [{question_id, is_correct}]
)
RETURNS TABLE(
    out_sense_id INTEGER,
    out_p_known_before NUMERIC,
    out_p_known_after NUMERIC,
    out_status TEXT
) AS $$
BEGIN
    RETURN QUERY
    WITH question_senses AS (
        SELECT
            unnest(q.sense_ids) AS sense_id,
            (qr->>'is_correct')::boolean AS is_correct
        FROM jsonb_array_elements(p_question_results) qr
        JOIN public.questions q ON q.id = (qr->>'question_id')::uuid
        WHERE q.sense_ids IS NOT NULL
          AND array_length(q.sense_ids, 1) > 0
    ),
    deduped AS (
        SELECT qs.sense_id, bool_or(qs.is_correct) AS is_correct
        FROM question_senses qs
        GROUP BY qs.sense_id
    ),
    current_state AS (
        SELECT
            d.sense_id,
            d.is_correct,
            COALESCE(
                uvk.p_known,
                CASE
                    WHEN dv.frequency_rank IS NULL THEN 0.10
                    WHEN dv.frequency_rank >= 6.0 THEN 0.85
                    WHEN dv.frequency_rank >= 5.0 THEN 0.65
                    WHEN dv.frequency_rank >= 4.0 THEN 0.35
                    WHEN dv.frequency_rank >= 3.0 THEN 0.15
                    ELSE 0.05
                END
            ) AS p_current
        FROM deduped d
        JOIN public.dim_word_senses dws ON dws.id = d.sense_id
        JOIN public.dim_vocabulary dv ON dv.id = dws.vocab_id
        LEFT JOIN public.user_vocabulary_knowledge uvk
            ON uvk.user_id = p_user_id AND uvk.sense_id = d.sense_id
    ),
    updated AS (
        SELECT
            cs.sense_id,
            cs.p_current AS p_before,
            bkt_update_comprehension(cs.p_current, cs.is_correct) AS p_after,
            cs.is_correct
        FROM current_state cs
    ),
    upserted AS (
        INSERT INTO public.user_vocabulary_knowledge
            (user_id, sense_id, language_id, p_known, status,
             evidence_count, comprehension_correct, comprehension_wrong,
             last_evidence_at, updated_at)
        SELECT
            p_user_id, u.sense_id, p_language_id,
            u.p_after, bkt_status(u.p_after),
            1,
            CASE WHEN u.is_correct THEN 1 ELSE 0 END,
            CASE WHEN u.is_correct THEN 0 ELSE 1 END,
            NOW(), NOW()
        FROM updated u
        ON CONFLICT (user_id, sense_id) DO UPDATE SET
            p_known = EXCLUDED.p_known,
            status = CASE
                WHEN user_vocabulary_knowledge.status = 'user_marked_unknown'
                THEN 'user_marked_unknown'
                ELSE EXCLUDED.status
            END,
            evidence_count = user_vocabulary_knowledge.evidence_count + 1,
            comprehension_correct = user_vocabulary_knowledge.comprehension_correct + EXCLUDED.comprehension_correct,
            comprehension_wrong = user_vocabulary_knowledge.comprehension_wrong + EXCLUDED.comprehension_wrong,
            last_evidence_at = NOW(),
            updated_at = NOW()
        RETURNING sense_id, p_known, status
    )
    SELECT
        upserted.sense_id,
        COALESCE(u.p_before, 0.10),
        upserted.p_known,
        upserted.status
    FROM upserted
    LEFT JOIN updated u ON u.sense_id = upserted.sense_id;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- update_vocabulary_from_word_test — Single-word BKT update after word quiz
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.update_vocabulary_from_word_test(
    p_user_id UUID,
    p_sense_id INTEGER,
    p_is_correct BOOLEAN,
    p_language_id SMALLINT
)
RETURNS TABLE(
    out_sense_id INTEGER,
    out_p_known_before NUMERIC,
    out_p_known_after NUMERIC,
    out_status TEXT
) AS $$
DECLARE
    v_p_current NUMERIC;
    v_p_new NUMERIC;
    v_status TEXT;
BEGIN
    SELECT COALESCE(uvk.p_known,
        CASE
            WHEN dv.frequency_rank IS NULL THEN 0.10
            WHEN dv.frequency_rank >= 6.0 THEN 0.85
            WHEN dv.frequency_rank >= 5.0 THEN 0.65
            WHEN dv.frequency_rank >= 4.0 THEN 0.35
            WHEN dv.frequency_rank >= 3.0 THEN 0.15
            ELSE 0.05
        END
    ) INTO v_p_current
    FROM public.dim_word_senses dws
    JOIN public.dim_vocabulary dv ON dv.id = dws.vocab_id
    LEFT JOIN public.user_vocabulary_knowledge uvk
        ON uvk.user_id = p_user_id AND uvk.sense_id = p_sense_id
    WHERE dws.id = p_sense_id;

    IF v_p_current IS NULL THEN
        v_p_current := 0.10;
    END IF;

    v_p_new := bkt_update_word_test(v_p_current, p_is_correct);
    v_status := bkt_status(v_p_new);

    INSERT INTO public.user_vocabulary_knowledge
        (user_id, sense_id, language_id, p_known, status,
         evidence_count, word_test_correct, word_test_wrong,
         last_evidence_at, updated_at)
    VALUES (
        p_user_id, p_sense_id, p_language_id,
        v_p_new, v_status,
        1,
        CASE WHEN p_is_correct THEN 1 ELSE 0 END,
        CASE WHEN p_is_correct THEN 0 ELSE 1 END,
        NOW(), NOW()
    )
    ON CONFLICT (user_id, sense_id) DO UPDATE SET
        p_known = EXCLUDED.p_known,
        status = CASE
            WHEN user_vocabulary_knowledge.status = 'user_marked_unknown'
            THEN 'user_marked_unknown'
            ELSE EXCLUDED.status
        END,
        evidence_count = user_vocabulary_knowledge.evidence_count + 1,
        word_test_correct = user_vocabulary_knowledge.word_test_correct + EXCLUDED.word_test_correct,
        word_test_wrong = user_vocabulary_knowledge.word_test_wrong + EXCLUDED.word_test_wrong,
        last_evidence_at = NOW(),
        updated_at = NOW();

    RETURN QUERY SELECT p_sense_id, v_p_current, v_p_new, v_status;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- RPC Functions: Word Quiz Helpers
-- ============================================================================

-- ---------------------------------------------------------------------------
-- get_word_quiz_candidates — Select words for quiz based on BKT uncertainty
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_word_quiz_candidates(
    p_user_id UUID,
    p_sense_ids INTEGER[],
    p_language_id SMALLINT,
    p_max_words INTEGER DEFAULT 5
)
RETURNS TABLE(
    out_sense_id INTEGER,
    out_lemma TEXT,
    out_definition TEXT,
    out_pronunciation TEXT,
    out_p_known NUMERIC,
    out_score NUMERIC
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        uvk.sense_id,
        dv.lemma,
        dws.definition,
        dws.pronunciation,
        uvk.p_known,
        (uvk.p_known * (1 - uvk.p_known) *
         (1.0 / GREATEST(1.0, ln(GREATEST(1.0, COALESCE(dv.frequency_rank, 1.0)::numeric))))
        ) AS score
    FROM public.user_vocabulary_knowledge uvk
    JOIN public.dim_word_senses dws ON dws.id = uvk.sense_id
    JOIN public.dim_vocabulary dv ON dv.id = dws.vocab_id
    WHERE uvk.user_id = p_user_id
      AND uvk.sense_id = ANY(p_sense_ids)
      AND uvk.p_known BETWEEN 0.25 AND 0.75
      AND uvk.status != 'user_marked_unknown'
    ORDER BY score DESC
    LIMIT p_max_words;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- get_distractors — Random distractors for word quiz
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_distractors(
    p_sense_id INTEGER,
    p_language_id SMALLINT,
    p_count INTEGER DEFAULT 3
)
RETURNS TABLE(out_definition TEXT) AS $$
BEGIN
    RETURN QUERY
    SELECT dws.definition
    FROM public.dim_word_senses dws
    JOIN public.dim_vocabulary dv ON dv.id = dws.vocab_id
    WHERE dv.language_id = p_language_id
      AND dws.id != p_sense_id
      AND dws.vocab_id != (SELECT vocab_id FROM public.dim_word_senses WHERE id = p_sense_id)
      AND dws.sense_rank = 1
    ORDER BY random()
    LIMIT p_count;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- RPC Functions: Test Generation Helpers
-- ============================================================================

-- ---------------------------------------------------------------------------
-- tests_containing_sense — Find tests that include a given word sense
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.tests_containing_sense(
    p_sense_id    INTEGER,
    p_language_id INTEGER
)
RETURNS TABLE (
    id              UUID,
    transcript      TEXT,
    difficulty      NUMERIC,
    vocab_token_map JSONB
)
LANGUAGE sql STABLE
AS $$
    SELECT t.id, t.transcript, t.difficulty, t.vocab_token_map
    FROM public.tests t
    WHERE t.vocab_sense_ids @> ARRAY[p_sense_id]
      AND t.language_id = p_language_id
      AND t.is_active = TRUE;
$$;

-- ---------------------------------------------------------------------------
-- get_cefr_config — CEFR level config for a given difficulty
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_cefr_config(p_difficulty INTEGER)
RETURNS TABLE (
    id INTEGER,
    cefr_code TEXT,
    word_count_min INTEGER,
    word_count_max INTEGER,
    initial_elo INTEGER
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        c.id::INTEGER,
        c.cefr_code::TEXT,
        c.word_count_min,
        c.word_count_max,
        c.initial_elo
    FROM public.dim_cefr_levels c
    WHERE p_difficulty BETWEEN c.difficulty_min AND c.difficulty_max
    LIMIT 1;
END;
$$;

-- ---------------------------------------------------------------------------
-- get_question_distribution — Question types for a given difficulty
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_question_distribution(p_difficulty INTEGER)
RETURNS TABLE (
    question_type_code TEXT
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT unnest(ARRAY[
        d.question_type_1,
        d.question_type_2,
        d.question_type_3,
        d.question_type_4,
        d.question_type_5
    ]) AS question_type_code
    FROM public.question_type_distributions d
    WHERE d.difficulty = p_difficulty;
END;
$$;

-- ============================================================================
-- Grants
-- ============================================================================

GRANT EXECUTE ON FUNCTION public.process_test_submission TO authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_elo_rating TO authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_volatility_multiplier TO authenticated;

-- ============================================================================
-- End of LinguaLoop Live Schema
-- ============================================================================
