-- ============================================================================
-- LinguaLoop Complete Schema
-- Run once against a fresh Supabase project to create all tables.
-- Prerequisite: auth.users must already exist (Supabase managed).
-- ============================================================================

-- ============================================================================
-- Extensions
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS vector;       -- pgvector for topic embeddings
CREATE EXTENSION IF NOT EXISTS pgcrypto;     -- gen_random_uuid()

-- ============================================================================
-- ENUMs
-- ============================================================================

DO $$ BEGIN
    CREATE TYPE exercise_source_type AS ENUM ('grammar', 'vocabulary', 'collocation');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

-- ============================================================================
-- Tier 0: No foreign key dependencies
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.dim_status (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_code     varchar NOT NULL UNIQUE,
    status_name     varchar NOT NULL,
    description     text,
    is_active       boolean DEFAULT true,
    created_at      timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.dim_languages (
    id                      smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language_code           varchar NOT NULL UNIQUE,
    language_name           varchar NOT NULL,
    native_name             varchar,
    iso_639_1               char,
    iso_639_3               char,
    is_active               boolean DEFAULT true,
    display_order           integer DEFAULT 0,
    created_at              timestamptz DEFAULT now(),
    updated_at              timestamptz DEFAULT now(),
    prose_model             varchar DEFAULT 'google/gemini-2.5-flash-lite',
    question_model          varchar DEFAULT 'google/gemini-2.5-flash-lite',
    tts_voice_ids           jsonb DEFAULT '["alloy","echo","fable","onyx","nova","shimmer"]',
    tts_speed               numeric DEFAULT 1.0 CHECK (tts_speed >= 0.25 AND tts_speed <= 4.0),
    grammar_check_enabled   boolean DEFAULT true,
    exercise_model          text,
    exercise_sentence_model text
);

CREATE TABLE IF NOT EXISTS public.dim_subscription_tiers (
    id                          smallint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tier_code                   varchar NOT NULL UNIQUE,
    tier_name                   varchar NOT NULL,
    display_name                varchar NOT NULL,
    description                 text,
    daily_free_tests            integer NOT NULL DEFAULT 0 CHECK (daily_free_tests >= 0),
    monthly_token_grant         integer NOT NULL DEFAULT 0 CHECK (monthly_token_grant >= 0),
    tokens_per_test             integer NOT NULL DEFAULT 10 CHECK (tokens_per_test >= 0),
    can_generate_tests          boolean DEFAULT false,
    can_create_custom_tests     boolean DEFAULT false,
    can_access_analytics        boolean DEFAULT false,
    max_custom_tests            integer DEFAULT 0 CHECK (max_custom_tests >= 0),
    is_admin                    boolean DEFAULT false,
    is_moderator                boolean DEFAULT false,
    is_active                   boolean DEFAULT true,
    display_order               integer DEFAULT 0,
    created_at                  timestamptz DEFAULT now(),
    updated_at                  timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.dim_cefr_levels (
    id              smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cefr_code       varchar NOT NULL UNIQUE,
    difficulty_min  integer NOT NULL,
    difficulty_max  integer NOT NULL,
    word_count_min  integer NOT NULL,
    word_count_max  integer NOT NULL,
    initial_elo     integer NOT NULL,
    description     text,
    created_at      timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.dim_lens (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lens_code       varchar NOT NULL UNIQUE,
    display_name    varchar NOT NULL,
    description     text,
    prompt_hint     text,
    is_active       boolean DEFAULT true,
    sort_order      integer DEFAULT 0,
    created_at      timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.dim_test_types (
    id              smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_code       varchar NOT NULL UNIQUE,
    type_name       varchar NOT NULL,
    description     text,
    category        varchar,
    requires_audio  boolean DEFAULT false,
    is_active       boolean DEFAULT true,
    display_order   integer DEFAULT 0,
    created_at      timestamptz DEFAULT now(),
    updated_at      timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.dim_question_types (
    id              smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_code       varchar NOT NULL UNIQUE,
    type_name       varchar NOT NULL,
    description     text,
    cognitive_level integer NOT NULL CHECK (cognitive_level >= 1 AND cognitive_level <= 3),
    is_active       boolean DEFAULT true,
    display_order   integer DEFAULT 0,
    created_at      timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.dim_prog_language (
    id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name        text NOT NULL UNIQUE,
    slug        text NOT NULL UNIQUE,
    icon_url    text,
    created_at  timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.dim_variable_pool (
    id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    pool_name   text NOT NULL UNIQUE,
    values      jsonb NOT NULL DEFAULT '[]',
    created_at  timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.test_generation_config (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key      varchar NOT NULL UNIQUE,
    config_value    text NOT NULL,
    description     text,
    updated_at      timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.test_generation_runs (
    id                          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_date                    date NOT NULL DEFAULT CURRENT_DATE,
    queue_items_processed       integer DEFAULT 0,
    tests_generated             integer DEFAULT 0,
    tests_failed                integer DEFAULT 0,
    prose_api_calls             integer DEFAULT 0,
    question_api_calls          integer DEFAULT 0,
    audio_api_calls             integer DEFAULT 0,
    grammar_checks_performed    integer DEFAULT 0,
    total_cost_usd              numeric DEFAULT 0,
    execution_time_seconds      integer,
    error_message               text,
    created_at                  timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.app_error_logs (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    error_type      text NOT NULL,
    error_message   text NOT NULL,
    url             text,
    user_id         uuid,
    metadata        jsonb,
    created_at      timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.users_backup (
    id              uuid,
    email           varchar,
    created_at      timestamptz,
    updated_at      timestamptz,
    last_login      timestamptz,
    display_name    varchar,
    native_language varchar,
    target_languages jsonb,
    timezone        varchar,
    is_active       boolean,
    email_verified  boolean
);

-- ============================================================================
-- Tier 1: Depends on tier 0 only
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.organizations (
    id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name                    text NOT NULL,
    slug                    text NOT NULL UNIQUE,
    subscription_tier_id    smallint NOT NULL REFERENCES public.dim_subscription_tiers(id),
    max_users               integer,
    token_pool              integer DEFAULT 0 CHECK (token_pool >= 0),
    is_active               boolean DEFAULT true,
    created_at              timestamptz DEFAULT now(),
    updated_at              timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.categories (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    varchar NOT NULL,
    description             text,
    status_id               integer DEFAULT 2 REFERENCES public.dim_status(id),
    target_language_id      integer REFERENCES public.dim_languages(id),
    cooldown_days           integer DEFAULT 7,
    last_used_at            timestamptz,
    total_topics_generated  integer DEFAULT 0,
    created_at              timestamptz DEFAULT now(),
    updated_at              timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.dim_library (
    id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    language_id     bigint NOT NULL REFERENCES public.dim_prog_language(id),
    name            text NOT NULL,
    version         text,
    doc_base_url    text,
    created_at      timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.dim_vocabulary (
    id                  integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    language_id         smallint NOT NULL REFERENCES public.dim_languages(id),
    lemma               text NOT NULL,
    phrase_type         text DEFAULT 'single_word',
    component_lemmas    text[],
    part_of_speech      text,
    frequency_rank      real,
    created_at          timestamptz DEFAULT now(),
    updated_at          timestamptz DEFAULT now(),
    level_tag           text
);

CREATE TABLE IF NOT EXISTS public.dim_grammar_patterns (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pattern_code            text NOT NULL UNIQUE,
    pattern_name            text NOT NULL,
    description             text NOT NULL,
    user_facing_description text NOT NULL,
    example_sentence        text NOT NULL,
    example_sentence_en     text,
    language_id             integer NOT NULL REFERENCES public.dim_languages(id),
    cefr_level              text NOT NULL CHECK (cefr_level IN ('A1','A2','B1','B2','C1','C2')),
    category                text NOT NULL CHECK (category IN (
                                'tense','aspect','voice','particles','word_order','modality',
                                'clause_structure','conjugation','honorifics','measure_words','complement'
                            )),
    is_active               boolean NOT NULL DEFAULT true,
    created_at              timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.question_type_distributions (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    difficulty          integer NOT NULL UNIQUE CHECK (difficulty >= 1 AND difficulty <= 9),
    question_type_1     varchar NOT NULL REFERENCES public.dim_question_types(type_code),
    question_type_2     varchar NOT NULL REFERENCES public.dim_question_types(type_code),
    question_type_3     varchar NOT NULL REFERENCES public.dim_question_types(type_code),
    question_type_4     varchar NOT NULL REFERENCES public.dim_question_types(type_code),
    question_type_5     varchar NOT NULL REFERENCES public.dim_question_types(type_code),
    created_at          timestamptz DEFAULT now(),
    updated_at          timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.prompt_templates (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_name       varchar NOT NULL,
    template_text   text NOT NULL,
    version         integer DEFAULT 1,
    is_active       boolean DEFAULT true,
    description     text,
    created_at      timestamptz DEFAULT now(),
    updated_at      timestamptz DEFAULT now(),
    language_id     integer NOT NULL REFERENCES public.dim_languages(id)
);

-- ============================================================================
-- Tier 2: Depends on tier 0–1
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.users (
    id                      uuid PRIMARY KEY,
    email                   text NOT NULL UNIQUE,
    display_name            text,
    email_verified          boolean DEFAULT false,
    total_tests_taken       integer DEFAULT 0,
    total_tests_generated   integer DEFAULT 0,
    last_activity_at        timestamptz,
    last_free_test_date     date DEFAULT (CURRENT_DATE - interval '1 day'),
    free_tests_used_today   integer DEFAULT 0,
    total_free_tests_used   integer DEFAULT 0,
    created_at              timestamptz DEFAULT now(),
    updated_at              timestamptz DEFAULT now(),
    last_login              timestamptz DEFAULT now(),
    subscription_tier_id    smallint NOT NULL DEFAULT 1 REFERENCES public.dim_subscription_tiers(id),
    deleted_at              timestamptz,
    anonymized_at           timestamptz,
    organization_id         uuid REFERENCES public.organizations(id),
    CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);

CREATE TABLE IF NOT EXISTS public.dim_block (
    id                  bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    library_id          bigint NOT NULL REFERENCES public.dim_library(id),
    name                text NOT NULL,
    qualified_name      text NOT NULL UNIQUE,
    syntax_template     text NOT NULL,
    description         text,
    difficulty          integer DEFAULT 1 CHECK (difficulty >= 1 AND difficulty <= 5),
    created_at          timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.topics (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    category_id         integer NOT NULL REFERENCES public.categories(id),
    concept_english     text NOT NULL,
    lens_id             integer NOT NULL REFERENCES public.dim_lens(id),
    keywords            jsonb DEFAULT '[]',
    embedding           vector(1536),
    semantic_signature  text,
    created_at          timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.daily_test_loads (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             uuid NOT NULL REFERENCES auth.users(id),
    language_id         integer NOT NULL,
    load_date           date NOT NULL DEFAULT CURRENT_DATE,
    test_ids            jsonb NOT NULL,
    completed_test_ids  jsonb DEFAULT '[]',
    created_at          timestamptz DEFAULT now()
);

-- ============================================================================
-- Tier 3: Depends on tier 0–2
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.organization_members (
    organization_id     uuid NOT NULL REFERENCES public.organizations(id),
    user_id             uuid NOT NULL REFERENCES public.users(id),
    role                text NOT NULL DEFAULT 'student' CHECK (role IN ('student','teacher','admin','owner')),
    joined_at           timestamptz DEFAULT now(),
    PRIMARY KEY (organization_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.dim_word_senses (
    id                      integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    vocab_id                integer NOT NULL REFERENCES public.dim_vocabulary(id),
    definition_language_id  smallint NOT NULL REFERENCES public.dim_languages(id),
    definition              text NOT NULL,
    pronunciation           text,
    example_sentence        text,
    usage_notes             text,
    sense_rank              integer NOT NULL DEFAULT 1,
    usage_frequency         text DEFAULT 'common' CHECK (usage_frequency IN ('common','uncommon','rare','archaic')),
    semantic_category       text,
    is_validated            boolean DEFAULT false,
    validated_by            uuid REFERENCES public.users(id),
    validation_notes        text,
    created_at              timestamptz DEFAULT now(),
    updated_at              timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.user_languages (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         uuid NOT NULL REFERENCES public.users(id),
    total_tests_taken integer DEFAULT 0,
    last_test_date  date,
    created_at      timestamptz DEFAULT now(),
    updated_at      timestamptz DEFAULT now(),
    language_id     smallint NOT NULL REFERENCES public.dim_languages(id)
);

CREATE TABLE IF NOT EXISTS public.user_tokens (
    user_id                         uuid PRIMARY KEY REFERENCES public.users(id),
    purchased_tokens                integer DEFAULT 0 CHECK (purchased_tokens >= 0),
    bonus_tokens                    integer DEFAULT 0 CHECK (bonus_tokens >= 0),
    total_tokens_earned             integer DEFAULT 0,
    total_tokens_spent              integer DEFAULT 0,
    total_tokens_purchased          integer DEFAULT 0,
    tokens_spent_tests              integer DEFAULT 0,
    tokens_spent_generation         integer DEFAULT 0,
    tokens_spent_premium_features   integer DEFAULT 0,
    referral_tokens_earned          integer DEFAULT 0,
    achievement_tokens_earned       integer DEFAULT 0,
    created_at                      timestamptz DEFAULT now(),
    updated_at                      timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.user_vocabulary (
    id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id                 uuid NOT NULL REFERENCES public.users(id),
    language_id             smallint NOT NULL REFERENCES public.dim_languages(id),
    known_sense_ids         integer[] DEFAULT '{}',
    sense_learning_stats    jsonb DEFAULT '{}',
    bootstrap_source        text,
    bootstrap_date          timestamptz,
    total_senses_tracked    integer DEFAULT 0,
    last_updated_at         timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.user_skill_ratings (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         uuid NOT NULL REFERENCES public.users(id),
    elo_rating      integer DEFAULT 1200 CHECK (elo_rating >= 400 AND elo_rating <= 3000),
    volatility      real DEFAULT 2.0 CHECK (volatility > 0),
    tests_taken     integer DEFAULT 0 CHECK (tests_taken >= 0),
    last_test_date  date,
    current_streak  integer DEFAULT 0,
    longest_streak  integer DEFAULT 0 CHECK (longest_streak >= 0),
    created_at      timestamptz DEFAULT now(),
    updated_at      timestamptz DEFAULT now(),
    language_id     smallint NOT NULL REFERENCES public.dim_languages(id),
    test_type_id    smallint NOT NULL REFERENCES public.dim_test_types(id)
);

CREATE TABLE IF NOT EXISTS public.flagged_content (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id             uuid REFERENCES public.users(id),
    content_hash        text NOT NULL,
    content_type        text NOT NULL,
    flagged_categories  jsonb,
    created_at          timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.tests (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    gen_user            uuid NOT NULL REFERENCES public.users(id),
    slug                text NOT NULL UNIQUE,
    difficulty          integer NOT NULL CHECK (difficulty >= 1 AND difficulty <= 9),
    style               text DEFAULT 'academic' CHECK (style IN ('academic','conversational','business','casual','technical')),
    tier                text NOT NULL DEFAULT 'free-tier' CHECK (tier IN ('free-tier','premium-tier','enterprise-tier')),
    title               text,
    transcript          text,
    audio_url           text,
    total_attempts      integer DEFAULT 0,
    is_active           boolean DEFAULT true,
    is_featured         boolean DEFAULT false,
    is_custom           boolean DEFAULT false,
    generation_model    text DEFAULT 'gpt-4.1-nano',
    audio_generated     boolean DEFAULT false,
    created_at          timestamptz DEFAULT now(),
    updated_at          timestamptz DEFAULT now(),
    language_id         smallint NOT NULL REFERENCES public.dim_languages(id),
    organization_id     uuid REFERENCES public.organizations(id),
    topic_id            uuid REFERENCES public.topics(id),
    vocab_sense_ids     integer[] DEFAULT '{}',
    vocab_sense_stats   jsonb DEFAULT '{}',
    vocab_token_map     jsonb
);

CREATE TABLE IF NOT EXISTS public.dim_question_template (
    id                  bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    block_id            bigint NOT NULL REFERENCES public.dim_block(id),
    question_pattern    text NOT NULL,
    answer_pattern      text NOT NULL,
    variable_config     jsonb NOT NULL DEFAULT '{}',
    created_at          timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.production_queue (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    topic_id            uuid NOT NULL REFERENCES public.topics(id),
    language_id         integer NOT NULL REFERENCES public.dim_languages(id),
    status_id           integer DEFAULT 1 REFERENCES public.dim_status(id),
    rejection_reason    text,
    processed_at        timestamptz,
    created_at          timestamptz DEFAULT now(),
    tests_generated     integer DEFAULT 0,
    error_log           text
);

CREATE TABLE IF NOT EXISTS public.topic_generation_runs (
    id                              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_date                        date NOT NULL,
    category_id                     integer REFERENCES public.categories(id),
    category_name                   text,
    topics_generated                integer DEFAULT 0,
    topics_rejected_similarity      integer DEFAULT 0,
    topics_rejected_gatekeeper      integer DEFAULT 0,
    candidates_proposed             integer DEFAULT 0,
    api_calls_llm                   integer DEFAULT 0,
    api_calls_embedding             integer DEFAULT 0,
    total_cost_usd                  numeric DEFAULT 0,
    execution_time_seconds          integer,
    error_message                   text,
    created_at                      timestamptz DEFAULT now()
);

-- ============================================================================
-- Tier 4: Depends on tier 0–3
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.exercises (
    id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    language_id             integer NOT NULL REFERENCES public.dim_languages(id),
    exercise_type           text NOT NULL,
    source_type             exercise_source_type NOT NULL,
    grammar_pattern_id      integer REFERENCES public.dim_grammar_patterns(id),
    word_sense_id           integer REFERENCES public.dim_word_senses(id),
    corpus_collocation_id   integer,
    content                 jsonb NOT NULL,
    tags                    jsonb NOT NULL DEFAULT '{}',
    difficulty_static       numeric(4,2),
    irt_difficulty          numeric(5,3) NOT NULL DEFAULT 0.0,
    irt_discrimination      numeric(5,3) NOT NULL DEFAULT 1.0,
    cefr_level              text CHECK (cefr_level IN ('A1','A2','B1','B2','C1','C2')),
    attempt_count           integer NOT NULL DEFAULT 0,
    correct_count           integer NOT NULL DEFAULT 0,
    is_active               boolean NOT NULL DEFAULT true,
    generation_batch_id     uuid,
    created_at              timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT chk_source_fk CHECK (
        (grammar_pattern_id IS NOT NULL)::int +
        (word_sense_id IS NOT NULL)::int +
        (corpus_collocation_id IS NOT NULL)::int = 1
    )
);

CREATE TABLE IF NOT EXISTS public.questions (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    test_id             uuid NOT NULL REFERENCES public.tests(id),
    question_id         text NOT NULL,
    question_text       text NOT NULL,
    choices             jsonb,
    answer              jsonb NOT NULL,
    answer_explanation  text,
    points              integer DEFAULT 1,
    audio_url           text,
    created_at          timestamptz DEFAULT now(),
    updated_at          timestamptz DEFAULT now(),
    question_type_id    smallint REFERENCES public.dim_question_types(id),
    sense_ids           integer[]
);

CREATE TABLE IF NOT EXISTS public.test_attempts (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id             uuid NOT NULL REFERENCES public.users(id),
    test_id             uuid NOT NULL REFERENCES public.tests(id),
    score               integer NOT NULL CHECK (score >= 0),
    total_questions     integer NOT NULL CHECK (total_questions > 0),
    percentage          real CHECK (percentage >= 0 AND percentage <= 100),
    user_elo_before     integer NOT NULL,
    test_elo_before     integer NOT NULL,
    user_elo_after      integer NOT NULL,
    test_elo_after      integer NOT NULL,
    elo_change          integer,
    was_free_test       boolean NOT NULL DEFAULT false,
    tokens_consumed     integer NOT NULL DEFAULT 0 CHECK (tokens_consumed >= 0),
    created_at          timestamptz DEFAULT now(),
    language_id         smallint NOT NULL REFERENCES public.dim_languages(id),
    test_type_id        smallint NOT NULL REFERENCES public.dim_test_types(id),
    idempotency_key     uuid,
    attempt_number      integer DEFAULT 1,
    is_first_attempt    boolean DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.test_skill_ratings (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    test_id         uuid NOT NULL REFERENCES public.tests(id),
    elo_rating      integer DEFAULT 1400 CHECK (elo_rating >= 400 AND elo_rating <= 3000),
    volatility      real DEFAULT 1.0 CHECK (volatility > 0),
    total_attempts  integer DEFAULT 0 CHECK (total_attempts >= 0),
    created_at      timestamptz DEFAULT now(),
    updated_at      timestamptz DEFAULT now(),
    test_type_id    smallint NOT NULL REFERENCES public.dim_test_types(id)
);

CREATE TABLE IF NOT EXISTS public.user_reports (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id             uuid NOT NULL REFERENCES auth.users(id),
    report_category     varchar NOT NULL CHECK (report_category IN (
                            'test_answer_incorrect','test_load_error','website_crash',
                            'improvement_idea','audio_quality','other'
                        )),
    description         text NOT NULL,
    current_page        varchar,
    test_id             uuid REFERENCES public.tests(id),
    test_type           varchar,
    user_agent          text,
    screen_resolution   varchar,
    status              varchar DEFAULT 'pending' CHECK (status IN ('pending','reviewing','resolved','dismissed')),
    created_at          timestamptz DEFAULT now(),
    updated_at          timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.user_flashcards (
    id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id         uuid NOT NULL REFERENCES public.users(id),
    sense_id        integer NOT NULL REFERENCES public.dim_word_senses(id),
    language_id     smallint NOT NULL REFERENCES public.dim_languages(id),
    stability       real DEFAULT 0,
    difficulty      real DEFAULT 0.3,
    due_date        date,
    last_review     timestamptz,
    reps            integer DEFAULT 0,
    lapses          integer DEFAULT 0,
    state           text DEFAULT 'new' CHECK (state IN ('new','learning','review','relearning')),
    example_sentence text,
    audio_url       text,
    created_at      timestamptz DEFAULT now(),
    updated_at      timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.user_vocabulary_knowledge (
    id                      bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id                 uuid NOT NULL REFERENCES public.users(id),
    sense_id                integer NOT NULL REFERENCES public.dim_word_senses(id),
    language_id             smallint NOT NULL REFERENCES public.dim_languages(id),
    p_known                 numeric NOT NULL DEFAULT 0.10,
    status                  text NOT NULL DEFAULT 'unknown' CHECK (status IN (
                                'unknown','encountered','learning','probably_known','known','user_marked_unknown'
                            )),
    evidence_count          integer DEFAULT 0,
    comprehension_correct   integer DEFAULT 0,
    comprehension_wrong     integer DEFAULT 0,
    word_test_correct       integer DEFAULT 0,
    word_test_wrong         integer DEFAULT 0,
    last_evidence_at        timestamptz,
    created_at              timestamptz DEFAULT now(),
    updated_at              timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.vocabulary_review_queue (
    id                  bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    vocab_id            integer NOT NULL REFERENCES public.dim_vocabulary(id),
    sense_id            integer REFERENCES public.dim_word_senses(id),
    issue_type          text NOT NULL CHECK (issue_type IN (
                            'validation_failed','duplicate_suspected','definition_unclear',
                            'offensive_content','llm_error'
                        )),
    proposed_definition text,
    failure_reason      text,
    context_sentence    text,
    status              text DEFAULT 'pending' CHECK (status IN ('pending','reviewing','resolved','dismissed')),
    reviewed_by         uuid REFERENCES public.users(id),
    resolution_notes    text,
    resolved_at         timestamptz,
    created_at          timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.exercise_attempts (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         uuid NOT NULL REFERENCES public.users(id),
    exercise_id     uuid REFERENCES public.exercises(id),
    user_response   jsonb,
    is_correct      boolean NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now()
);

-- ============================================================================
-- Tier 5: Depends on tier 0–4
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.token_transactions (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id             uuid NOT NULL REFERENCES public.users(id),
    tokens_consumed     integer DEFAULT 0 CHECK (tokens_consumed >= 0),
    tokens_added        integer DEFAULT 0 CHECK (tokens_added >= 0),
    token_balance_after integer NOT NULL CHECK (token_balance_after >= 0),
    action              text NOT NULL,
    payment_intent_id   text,
    package_id          text,
    test_id             uuid REFERENCES public.tests(id),
    attempt_id          uuid REFERENCES public.test_attempts(id),
    is_valid            boolean DEFAULT true,
    invalidated_at      timestamptz,
    invalidation_reason text,
    created_by_system   boolean DEFAULT true,
    created_at          timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.word_quiz_results (
    id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id         uuid NOT NULL REFERENCES public.users(id),
    attempt_id      uuid REFERENCES public.test_attempts(id),
    sense_id        integer NOT NULL REFERENCES public.dim_word_senses(id),
    is_correct      boolean NOT NULL,
    selected_answer text,
    correct_answer  text,
    response_time_ms integer,
    created_at      timestamptz DEFAULT now()
);

-- ============================================================================
-- Indexes
-- ============================================================================

-- dim_grammar_patterns
CREATE INDEX IF NOT EXISTS idx_grammar_patterns_language ON dim_grammar_patterns(language_id);
CREATE INDEX IF NOT EXISTS idx_grammar_patterns_cefr     ON dim_grammar_patterns(cefr_level);
CREATE INDEX IF NOT EXISTS idx_grammar_patterns_active   ON dim_grammar_patterns(is_active) WHERE is_active = TRUE;

-- exercises
CREATE INDEX IF NOT EXISTS idx_exercises_language    ON exercises(language_id);
CREATE INDEX IF NOT EXISTS idx_exercises_type        ON exercises(exercise_type);
CREATE INDEX IF NOT EXISTS idx_exercises_source      ON exercises(source_type);
CREATE INDEX IF NOT EXISTS idx_exercises_grammar     ON exercises(grammar_pattern_id) WHERE grammar_pattern_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_exercises_sense       ON exercises(word_sense_id) WHERE word_sense_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_exercises_collocation ON exercises(corpus_collocation_id) WHERE corpus_collocation_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_exercises_cefr        ON exercises(cefr_level);
CREATE INDEX IF NOT EXISTS idx_exercises_active      ON exercises(is_active) WHERE is_active = TRUE;
CREATE INDEX IF NOT EXISTS idx_exercises_tags_gin    ON exercises USING GIN (tags);
CREATE INDEX IF NOT EXISTS idx_exercises_content_gin ON exercises USING GIN (content);

-- exercise_attempts
CREATE INDEX IF NOT EXISTS idx_ea_exercise_id        ON exercise_attempts(exercise_id);
CREATE INDEX IF NOT EXISTS idx_ea_user_response_gin  ON exercise_attempts USING GIN (user_response);

-- ============================================================================
-- RPC Functions
-- ============================================================================

CREATE OR REPLACE FUNCTION tests_containing_sense(
    p_sense_id    INTEGER,
    p_language_id INTEGER
)
RETURNS TABLE (
    id              UUID,
    transcript      TEXT,
    difficulty      NUMERIC,
    vocab_token_map JSONB
)
LANGUAGE sql STABLE
AS $$
    SELECT t.id, t.transcript, t.difficulty, t.vocab_token_map
    FROM tests t
    JOIN dim_languages dl ON dl.id = p_language_id
    WHERE t.vocab_sense_ids @> ARRAY[p_sense_id]
      AND t.language_id = p_language_id
      AND t.is_active = TRUE;
$$;

-- NOTE: get_verb_noun_pairs requires corpus_collocations table (Plan 5).
-- Uncomment this function after that table has been created.
--
-- CREATE OR REPLACE FUNCTION get_verb_noun_pairs(
--     p_corpus_source_id INTEGER,
--     p_language_id      INTEGER,
--     p_pmi_threshold    NUMERIC DEFAULT 3.0
-- )
-- RETURNS TABLE (verb_phrase TEXT, noun_phrase TEXT, combined_pmi NUMERIC)
-- LANGUAGE sql STABLE
-- AS $$
--     SELECT DISTINCT
--         split_part(cc.collocation_text, ' ', 1)   AS verb_phrase,
--         split_part(cc.collocation_text, ' ', 2)   AS noun_phrase,
--         cc.pmi_score                               AS combined_pmi
--     FROM corpus_collocations cc
--     WHERE cc.pos_pattern       = 'VERB+NOUN'
--       AND cc.corpus_source_id  = p_corpus_source_id
--       AND cc.language_id       = p_language_id
--       AND cc.pmi_score        >= p_pmi_threshold
--     ORDER BY combined_pmi DESC
--     LIMIT 20;
-- $$;

-- ============================================================================
-- Analytics Views
-- ============================================================================

CREATE OR REPLACE VIEW vw_distractor_error_analysis AS
SELECT
    ea.user_id,
    e.tags->>'grammar_pattern'          AS pattern_code,
    ea.user_response->>'distractor_tag' AS error_type,
    COUNT(*)                             AS error_count,
    MIN(ea.created_at)                   AS first_seen,
    MAX(ea.created_at)                   AS last_seen
FROM exercise_attempts ea
JOIN exercises e ON ea.exercise_id = e.id
WHERE ea.is_correct = FALSE
  AND ea.user_response->>'distractor_tag' IS NOT NULL
  AND e.exercise_type = 'cloze_completion'
GROUP BY 1, 2, 3;

CREATE OR REPLACE VIEW vw_exercise_performance_by_type AS
SELECT
    e.exercise_type,
    e.cefr_level,
    e.language_id,
    COUNT(DISTINCT e.id)             AS exercise_count,
    COUNT(ea.id)                     AS total_attempts,
    SUM(ea.is_correct::int)          AS correct_count,
    ROUND(
        SUM(ea.is_correct::int)::numeric / NULLIF(COUNT(ea.id), 0) * 100,
        1
    )                                AS accuracy_pct
FROM exercises e
LEFT JOIN exercise_attempts ea ON ea.exercise_id = e.id
WHERE e.is_active = TRUE
GROUP BY 1, 2, 3;
