-- dim_word_senses.register — sociolinguistic register / keigo level for a sense.
-- Source of truth: wiki/features/exercise-generation-v2.md §4 / §P0.6; operator answer 13.
-- TASK-506 (Exercise Generation v2, Phase 0).
--
-- For Japanese (language_id=3) this carries the keigo level of the sense:
--   plain | polite | honorific | humble | formal | casual
-- NULL for senses in languages where register is not modelled (ZH/EN at present)
-- and for JA senses not yet (re)generated by the JA P1 prompt (TASK-508), which
-- populates this column going forward.
--
-- Additive and idempotent: applyable now regardless of JA data presence.

ALTER TABLE dim_word_senses
    ADD COLUMN IF NOT EXISTS register text;

COMMENT ON COLUMN dim_word_senses.register IS
    'Sociolinguistic register / JA keigo level (plain|polite|honorific|humble|formal|casual); '
    'NULL where not modelled. Populated by the JA P1 prompt (vocab_prompt1_core, TASK-508).';
