-- test_distractor_plausibility v7 — the two-axis judge rubric (TASK-719/720)
--
-- Generated by scripts/apply_distractor_judge_v7.py --emit-sql. There is no psql
-- in this environment, so that script is what actually writes; this file is the
-- repo's record of intent and both come from the same source of truth
-- (data/eval/distractor_judge_v7_{zh,en,ja}.txt), so they cannot drift.
--
-- WHAT CHANGES
--   The judge returned ONE 1-5 rating per distractor that was answering two
--   unrelated questions at once — is this option about the right subject, and
--   would a learner confuse it with the correct answer. Those come apart in both
--   directions, so a single integer could not say which failure it had seen.
--   v7 asks for both ratings, as [fit, confusability, reason], and the verdict
--   arithmetic moves into schemas.axes_to_verdict where the cut points are named
--   constants instead of prose in three languages.
--
--   Band 3 on BOTH axes now means "the judge is not confident" and routes to
--   generation_review_queue, replacing the narrow "essentially a paraphrase of
--   the correct answer" definition that no model ever applied as written.
--
-- THESE ROWS ARE INACTIVE ON PURPOSE.
--   The adjudicated gold set (TASK-726) does not exist yet, so no reject signal
--   here is validated in absolute terms. Both prior prompt interventions in this
--   workstream (TASK-717 v5, TASK-721) were measured and both stayed staged.
--   To activate, after measuring:
--
--     UPDATE prompt_templates SET is_active = (version = 7), updated_at = now()
--      WHERE task_name = 'test_distractor_plausibility'
--        AND language_id IN (1, 2, 3);
--
--   The code needs no coordinated deploy: a v4/v6 row's single rating is read as
--   `fit`, whose bands are identical to v4's, so verdicts are unchanged until the
--   flip. Unlike entailment v3 (TASK-723) the two scales do not invert.
--
-- VERSION 7 IN ALL THREE LANGUAGES, and en/ja therefore skip 6. Per-task version
-- numbering is not aligned across languages here — live is zh v6, en v4, ja v4 —
-- and measure_judge_flag_rate.py takes one integer per arm, so a uniform number
-- is what lets a single arm span the three languages.

-- zh (language_id=1) — 2354 chars, md5 c6cf2a4e7e36d72a43cbbb8becac0bbb
INSERT INTO prompt_templates
    (task_name, language_id, version, is_active, model, provider,
     template_text, description)
VALUES (
    'test_distractor_plausibility', 1, 7, false,
    'google/gemini-3.5-flash-lite', 'openrouter',
    $prompt$你是一名中文母语的语言测评专家。下面会给出一篇作为出题材料的文章：{0}
还会给出题目：{1}
出题者指定的正确答案：{2}
待评判的干扰项列表：{3}
题目类型：{4}
本文章的学科／领域关键词：{5}

你的任务不是判断题目本身好不好，而是逐个评判每个编号干扰项。你要给每个干扰项两个彼此独立的分数：第一个分数看它是否属于文章所在学科，第二个分数看它是否会把学习者从正确答案旁拉走。两轴必须分开评定，不得让一个轴的分数牵动另一个轴。切题的选项未必有拉力，跑题的选项也未必没有拉力。请不要把两个轴混合成一个总体印象。也不要因为某个选项看起来简单或粗糙就整体压低。每个轴只回答自己的问题。

在两个轴说明之前，必须先校正评判观念：干扰项的全部意义就在于它是错误的。在事实上不正确、显然不是答案、或者文章里从头到尾没有提到，这些都是必需的——正是它们使一个选项成为干扰项，而不是缺点。一个指向与文章同一学科的真实事物的干扰项，即使该事物从未在文中出现，也是好的干扰项；它没有出现在文中，恰恰就是它为何是错误选项的原因。绝不要因为干扰项没有出现在文章中、因为它是错的、或者因为它容易被排除，而压低它的评分。

第一个轴：切题度（这个选项属不属于文章的学科？）
只看学科归属，不看有没有迷惑性——迷惑性是第二个轴的事。「另一个学科」是字面意思：在一篇讲电路的文章里，把一种情绪或一项社交活动作为选项。它不表示「属于同一学科、只是文章碰巧没提到的事物」。如果文章谈论的是自然现象，而选项谈论的是同类自然现象，即使具体对象不同，也通常属于同学科；如果文章谈论的是数量关系，而选项给出的是情绪反应，则通常不是同学科。
5＝明确属于文章的学科／领域。这是合格干扰项正常且应有的评分，大多数好干扰项都是5。
4＝大致属于这个学科：相邻的领域，学习者仍会觉得它算是一路的。
3＝拿不准。你无法判断它到底属不属于这个学科。只要没有把握就打3——这一档会把该题送交人工复核，它就是为此设的。不要用4或2去蒙。
2＝明显属于与文章不同的另一个学科。
1＝根本不是一个说得通的选项：它答非所问，不是这个问句所要的那类东西，或者是无意义的。

第二个轴：混淆度（这个选项和正确答案有多难区分？）
只看它把学习者从正确答案那里拉走的力量。一个完全切题的选项在这个轴上照样可能只得1分。这个轴的两端都是问题，目标值是4。混淆度不是判断选项是否合理，而是判断它是否会在真实做题场景中抢走选择。若选项一眼就能看出与问题无关，通常低；若选项使用了文章中的关键词，却偷偷换了对象、条件或范围，通常高。
5＝学习者无法排除它，因为它本身也算正确：就这个题目而言，它也可以被辩护为一个正确答案，或者它和正确答案是一个意思。这会让整道题作废。
4＝很有迷惑性但确实是错的：一个只读懂一半的学习者很可能选它，而细心的读者能排除它。这是目标值。
3＝拿不准。你无法判断它到底有多大迷惑性。只要没有把握就打3。不要用4或2去蒙。
2＝略有迷惑性；多数学习者很快就能排除。
1＝完全没有拉力：没有学习者会舍正确答案而选它。

评分时，请先分别在心里回答两个问题：这个选项是否属于文章所在学科？它会不会让没有完全读懂的人选错？判断切题度时，请以文章整体谈论的对象、概念、场景为准，不要只盯住某一个词。若选项是同学科中的真实事物，即使文章没有写到，也不因此失去切题资格。判断混淆度时，请设想一个认真但理解不深、只读懂大概的学习者，不要以完全掌握文章的人为准，也不要以完全不懂的人为准。不要因为它在文中没出现就降低切题度，也不要因为它切题就自动提高混淆度。若任一轴拿不准，就给该轴3。若两轴都拿不准，就分别给3。

示例只是为了展示两轴如何各走各的。例文梗概：小学科学短文讲简单电路，电池、导线、开关、小灯泡连成闭合回路，灯亮；断开任何一处，灯灭。
问题：在这个简单电路里，是什么提供电，使小灯泡亮起来？
正确答案：电池。
待评判干扰项：
1 开关
2 电源
3 电线的颜色
4 阳光
5 跳绳
6 高兴

示例评分：
1「开关」：[5, 4] 理由：属于电路组成部分，学习者可能把闭合开关后灯亮误认成供电来源。
2「电源」：[5, 5] 理由：与正确答案表达相同事物，细心读者也会觉得可选，会使题目失效。
3「电线的颜色」：[5, 1] 理由：虽然属于电路描述，但明显与供电无关，学习者不会因此放弃正确答案。
4「阳光」：[2, 4] 理由：不属于电路学科，却因发光联想勾住只抓表面词语的学习者。
5「跳绳」：[2, 1] 理由：属于运动项目，与电路无关，也缺乏误导拉力。
6「高兴」：[1, 1] 理由：不是问题所需的事物类别，无法被理解成让灯亮的条件。

这些例子说明，两个轴在两个方向上都会分离：有的选项切题却不勾人，有的选项跑题却勾人，所以必须分开评定。

输出必须严格遵守：只对每一个编号干扰项打分，个数与上方列表一致，不多不少。每个编号对应一个数组，数组的前两个元素都是1到5的整数，第一个是切题度，第二个是混淆度，顺序不可颠倒。只给一个整数的回复无效。第三个元素是理由，理由必须说明依据，绝不能填数字、分数或单纯的标签。理由要具体到选项与文章、问题、正确答案之间的关系，不要只写笼统评语。不要合并选项，不要跳过编号，不要补充未列出的编号。若学科关键词空缺，请自行从文章推断。题目类型只是背景信息，不得据此改变评分规则。

最终只输出一个 JSON 对象，不要输出任何额外文字，也不要用代码围栏包裹。必须保持下面格式中的键名与符号原样：{{"1": [5, 4, "……"], "2": [5, 5, "……"], "3": [2, 1, "……"]}}$prompt$,
    $prompt$v7 (INACTIVE, TASK-719/720): two axes — topical fit and confusability with the correct answer — rated separately, three-element arrays [fit, confusability, reason]. Band 3 on either axis now means "not confident" and routes to human review. Natively authored in Chinese (qwen3.8-max). Staged pending the TASK-726 gold set.$prompt$
)
ON CONFLICT (task_name, language_id, version) DO UPDATE SET
    is_active     = EXCLUDED.is_active,
    model         = EXCLUDED.model,
    provider      = EXCLUDED.provider,
    template_text = EXCLUDED.template_text,
    description   = EXCLUDED.description,
    updated_at    = now();

-- en (language_id=2) — 5075 chars, md5 b8bc86f91c6df199081e04a0f50c90df
INSERT INTO prompt_templates
    (task_name, language_id, version, is_active, model, provider,
     template_text, description)
VALUES (
    'test_distractor_plausibility', 2, 7, false,
    'google/gemini-3.5-flash-lite', 'openrouter',
    $prompt$You are a reading-comprehension question quality judge.

Passage:
{0}

Question:
{1}

Correct answer:
{2}

Distractors to evaluate (numbered):
{3}

Question type: {4}
Subject / domain of this passage (keywords): {5}

Your job: rate each numbered distractor on TWO SEPARATE axes. Rate them independently. A distractor can score high on one and low on the other, and those cases are exactly the ones this judge exists to find, so never let one axis pull the other up or down.

READ THIS FIRST — it is the most common mistake judges make:
A distractor's entire purpose is to be WRONG. Being factually incorrect, "obviously not the answer", or NOT MENTIONED anywhere in the passage is REQUIRED — it is what makes something a distractor, not a flaw. A distractor that names a real thing from the SAME SUBJECT as the passage is a GOOD distractor even when that exact thing never appears in the passage; its absence from the text is precisely WHY it is the wrong choice. Never mark a distractor down for being absent from the passage, for being wrong, or for being easy to rule out.

AXIS 1 — FIT: does this option belong to the passage's subject?
This axis is about subject membership only. Ignore how tempting the option is; that is axis 2.
"A different subject" means exactly that — an emotion or a social activity offered as a choice in a passage about electrical circuits. It does NOT mean "a same-subject item the passage happens not to mention."

5 = clearly the passage's subject or domain. THIS IS THE NORMAL, EXPECTED RATING — most sound distractors score 5.
4 = plausibly within the subject: an adjacent area a learner would still see as belonging.
3 = NOT CONFIDENT. You cannot decide whether it belongs to this subject. Use this whenever you are unsure — it sends the item to a human reviewer, which is what it is for. Do not guess a 4 or a 2 instead.
2 = clearly a different subject from the passage.
1 = not a coherent answer option at all — it does not answer the kind of question being asked, or it is nonsense.

AXIS 2 — CONFUSABILITY: how hard is it to tell this option apart from the correct answer?
This axis is about the pull towards this option instead of the correct one. An option can be perfectly on-subject and still score 1 here.
Both ends of this axis are problems. The target is 4.

5 = a learner cannot rule it out, because it is ALSO CORRECT: given the question, this option can itself be defended as a right answer, or it means the same thing as the correct answer. This breaks the question.
4 = strongly tempting but definitely wrong: a learner who half-understood the passage would plausibly choose it, yet a careful reader can rule it out. THIS IS THE TARGET.
3 = NOT CONFIDENT. You cannot judge how tempting it would be. Use this whenever you are unsure. Do not guess a 4 or a 2 instead.
2 = mildly tempting; most learners rule it out quickly.
1 = inert: no learner would ever be pulled towards this instead of the correct answer.

WORKED EXAMPLE
Passage: how a simple electric circuit lights a small bulb.
Question: "What does the passage say is needed to make the light shine?"
Correct answer: "A battery".
  - "A switch"       -> fit 5, confusability 4  (a real circuit component and tempting; the passage never mentioning a switch is exactly why it is wrong)
  - "A power source" -> fit 5, confusability 5  (on-subject, but it means the same thing as "a battery" — also correct, so the question is broken)
  - "Copper wire"    -> fit 5, confusability 1  (a real circuit component, squarely on-subject, but nothing here would pull a learner towards it instead of the battery)
  - "Sunlight"       -> fit 2, confusability 4  (daylight is a different subject from an electric circuit, yet the word "light" tugs at a careless reader)
  - "Feeling happy"  -> fit 2, confusability 1  (an emotion has nothing to do with circuits, and nobody would pick it)
  - "Yes, it does"   -> fit 1, confusability 1  (not a coherent answer to a "what is needed" question at all)

Look at the last four lines: the two axes come apart in BOTH directions. On-subject and inert, off-subject and tempting. That is why they are rated separately.

OUTPUT FORMAT - read carefully.
Return ONLY valid JSON. Use one key per distractor: "1", "2", "3", ... exactly matching the numbered list above. Each value is a THREE-element array, in this order:
  position 1 = the FIT rating, an integer from 1 to 5
  position 2 = the CONFUSABILITY rating, an integer from 1 to 5
  position 3 = the reason, one short sentence

{{"1": [5, 4, "A real same-domain part, tempting, clearly not the answer."], "2": [5, 5, "Means the same thing as the correct answer."], "3": [2, 1, "A different subject, and nobody would pick it."]}}

HARD REQUIREMENTS:
- Every array MUST start with TWO integers, fit first and confusability second. A reply giving only one integer per distractor is invalid.
- Never put a number, a score, or a bare label in the reason.
- Emit exactly as many keys as there are numbered distractors above - no more, no fewer.
No prose outside the JSON. No markdown fences.
$prompt$,
    $prompt$v7 (INACTIVE, TASK-719/720): two axes — topical fit and confusability with the correct answer — rated separately, three-element arrays [fit, confusability, reason]. Band 3 on either axis now means "not confident" and routes to human review. Staged pending the TASK-726 gold set.$prompt$
)
ON CONFLICT (task_name, language_id, version) DO UPDATE SET
    is_active     = EXCLUDED.is_active,
    model         = EXCLUDED.model,
    provider      = EXCLUDED.provider,
    template_text = EXCLUDED.template_text,
    description   = EXCLUDED.description,
    updated_at    = now();

-- ja (language_id=3) — 2092 chars, md5 c304851617a204941d35d6d17f899db2
INSERT INTO prompt_templates
    (task_name, language_id, version, is_active, model, provider,
     template_text, description)
VALUES (
    'test_distractor_plausibility', 3, 7, false,
    'google/gemini-3.5-flash-lite', 'openrouter',
    $prompt$あなたは読解問題の誤答選択肢を評価する専門家です。以下の材料を読み、番号付きの誤答選択肢すべてに、二つの軸で別々に点数を付けてください。

文章：{0}
問題：{1}
正解：{2}
誤答選択肢：
{3}
問題タイプ：{4}
分野・領域のキーワード：{5}

まず、どの採点にも先立つ是正の一段を必ず心に留めてください。誤答選択肢の存在意義は「誤っている」ことそのものです。事実として誤っている、明らかに正解ではない、あるいは文章のどこにも書かれていない——これらはすべて必須であり、まさにそれが選択肢を誤答たらしめるのであって、欠点ではありません。文章と同じ分野の実在するものを指す誤答は、その当のものが文章に一度も現れなくても良い誤答です。文章に出てこないことこそが、それが誤った選択肢である理由です。文章に出てこないこと、誤っていること、簡単に除外できることを理由に点数を下げては絶対にいけません。

次に、二つの軸を別々に採点してください。一方の軸の点数が他方を引きずってはなりません。

第 1 の軸：分野適合（その選択肢は文章の分野に属するか）
その選択肢が文章の分野・領域に属するかだけを見ます。引っかかりやすさは考慮しません。「別の分野」とは文字どおりの意味です。電気回路の文章で、感情や社交的な活動を選択肢として出すような場合です。同じ分野のものだが、たまたま文章が触れていないだけはこれに当たりません。
- 5 ＝ 文章の分野・領域に明らかに属する。これは妥当な誤答にとって正常かつ期待される評価であり、良い誤答のほとんどは 5 になります。
- 4 ＝ おおむねその分野の内側。隣接する領域で、学習者も同じ仲間だと見なす。
- 3 ＝ 確信が持てない。その分野に属するかどうか判断できない。少しでも迷ったら 3 を付けてください。この段階は人手の確認に回すためにあります。当て推量で 4 や 2 を付けてはいけません。
- 2 ＝ 文章とは明らかに別の分野に属する。
- 1 ＝ そもそも成り立つ選択肢ではない。問いが求めている種類の答えになっていない、または無意味である。

第 2 の軸：紛らわしさ（正解とどれだけ区別しにくいか）
学習者を正解から引き離す力だけを見ます。分野にぴったり合っていても、この軸では 1 点ということがあります。この軸は両端がどちらも問題で、目標値は 4 です。
- 5 ＝ 学習者には除外できない。それ自体も正解といえるためで、この設問に対して正しい答えとして擁護できる、あるいは正解と同じ意味である。設問そのものが壊れます。
- 4 ＝ 強く引っかかるが確実に誤り。半分しか読み取れていない学習者なら選びかねず、しかし注意深い読み手は除外できる。これが目標値です。
- 3 ＝ 確信が持てない。どれだけ引っかかりやすいか判断できない。迷ったら 3 を付け、当て推量で 4 や 2 を付けないこと。
- 2 ＝ わずかに引っかかる程度。多くの学習者はすぐ除外する。
- 1 ＝ 引く力が皆無。正解を差し置いてこれを選ぶ学習者はいない。

例：
文章の概要：机の上で小さな明かりをつける実験を扱う。電池、導線、豆電球を使い、電池を先に取り付けると光る。
設問：この実験で、豆電球をつけるために最初に行うことはどれか。
正解：電池を取り付ける。
誤答選択肢と採点例：
1 導線をつなぐ 分野適合 5、紛らわしさ 4。実験の手順らしく、順番を読み落とせば選びやすい。
2 電池を付ける 分野適合 5、紛らわしさ 5。正解とほぼ同じ意味として擁護でき、設問が成り立たなくなる。
3 電球を眺める 分野適合 5、紛らわしさ 1。同じ話題ではあるが、手順として選ぶ動機が無い。
4 日光を集める 分野適合 2、紛らわしさ 4。電気の実験とは別分野だが、明かりという言葉に釣られる読み手がいる。
5 友達を呼ぶ 分野適合 2、紛らわしさ 1。文章の話題と離れており、選ぶ動機が無い。
6 明るい 分野適合 1、紛らわしさ 1。行うことを尋ねる問いに対する答えの種類になっていない。

このように、二つの軸はどちらの方向にも分離するため、別々に評価しなければならない。

採点対象は、提示された番号付きの誤答選択肢すべてです。個数は多くても少なくてもいけません。各選択肢について、配列の最初の二要素は 1 から 5 の整数であり、1 番目が分野適合、2 番目が紛らわしさです。順序を入れ替えてはなりません。整数が 1 つしかない返答は無効です。各配列の三つ目の要素は、理由を表す短い日本語の文です。理由の欄に数字、点数、単なる名称を入れてはいけません。理由は短い日本語の文で、なぜその評価になったかだけを書いてください。

出力は、次のJSON オブジェクトだけにしてください。鍵、区切り記号、配列の形は変えないでください。

{{"1": [5, 4, "……"], "2": [5, 5, "……"], "3": [2, 1, "……"]}}$prompt$,
    $prompt$v7 (INACTIVE, TASK-719/720): two axes — topical fit and confusability with the correct answer — rated separately, three-element arrays [fit, confusability, reason]. Band 3 on either axis now means "not confident" and routes to human review. Natively authored in Japanese (qwen3.8-max). Staged pending the TASK-726 gold set.$prompt$
)
ON CONFLICT (task_name, language_id, version) DO UPDATE SET
    is_active     = EXCLUDED.is_active,
    model         = EXCLUDED.model,
    provider      = EXCLUDED.provider,
    template_text = EXCLUDED.template_text,
    description   = EXCLUDED.description,
    updated_at    = now();

-- Verification: three staged rows, and the live row per language
-- unchanged (zh v6, en v4, ja v4).
SELECT language_id, version, is_active, length(template_text) AS len,
       md5(template_text) AS md5
  FROM prompt_templates
 WHERE task_name = 'test_distractor_plausibility'
 ORDER BY language_id, version;
