-- migrations/fix_daily_test_loads_user_id_fk.sql
-- Closes the schema-inconsistency gap surfaced in the 2026-05-12 wiki audit.
-- daily_test_loads.user_id originally FK'd to auth.users(id) while every
-- other user-owning table FKs to public.users(id) — the table that carries
-- subscription_tier, display_name, is_admin and other app-level columns.
--
-- public.users.id is itself FK'd 1:1 to auth.users.id (PK constraint), so
-- every existing row in daily_test_loads.user_id is guaranteed to exist in
-- public.users.id. The migration is a pure constraint swap with no data move.
--
-- Also drops two now-redundant narrow RLS policies created in the original
-- daily_test_loads.sql migration ("Users can read own daily loads" / "Users
-- can update own daily loads"). They are superseded by dtl_own_data (FOR ALL)
-- from migrations/enable_rls_on_user_owned_tables.sql (2026-05-12), and
-- leaving them in place clutters the policy set vs. the cousin tables.
--
-- Idempotent: safe to re-apply.

-- ===========================================================================
-- 1. Drop any FK on user_id that targets auth.users
-- ===========================================================================
-- Use a DO block so we don't have to know the autogenerated constraint name.
DO $$
DECLARE
  v_constraint_name text;
BEGIN
  SELECT con.conname INTO v_constraint_name
  FROM pg_constraint con
  JOIN pg_class    src ON src.oid = con.conrelid
  JOIN pg_class    tgt ON tgt.oid = con.confrelid
  JOIN pg_namespace tgt_ns ON tgt_ns.oid = tgt.relnamespace
  WHERE src.relname = 'daily_test_loads'
    AND con.contype = 'f'
    AND tgt.relname = 'users'
    AND tgt_ns.nspname = 'auth';

  IF v_constraint_name IS NOT NULL THEN
    EXECUTE format(
      'ALTER TABLE public.daily_test_loads DROP CONSTRAINT %I',
      v_constraint_name
    );
  END IF;
END$$;

-- ===========================================================================
-- 2. Add the FK to public.users
-- ===========================================================================
-- Drop the canonical name first in case a prior re-run left it behind.
ALTER TABLE public.daily_test_loads
  DROP CONSTRAINT IF EXISTS daily_test_loads_user_id_fkey;

ALTER TABLE public.daily_test_loads
  ADD CONSTRAINT daily_test_loads_user_id_fkey
  FOREIGN KEY (user_id)
  REFERENCES public.users(id)
  ON DELETE CASCADE;

-- ===========================================================================
-- 3. Drop the redundant narrow RLS policies
-- ===========================================================================
-- Superseded by dtl_own_data (FOR ALL) from enable_rls_on_user_owned_tables.sql.
DROP POLICY IF EXISTS "Users can read own daily loads"   ON public.daily_test_loads;
DROP POLICY IF EXISTS "Users can update own daily loads" ON public.daily_test_loads;

-- ===========================================================================
-- Verification queries (run after apply)
-- ===========================================================================
-- 1) FK should target public.users:
--    SELECT conname, pg_get_constraintdef(oid)
--    FROM pg_constraint
--    WHERE conrelid = 'public.daily_test_loads'::regclass
--      AND contype = 'f';
--    Expected: FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
--
-- 2) Policy set should be exactly the three from the 2026-05-12 migration:
--    SELECT policyname FROM pg_policies
--    WHERE schemaname = 'public' AND tablename = 'daily_test_loads'
--    ORDER BY policyname;
--    Expected: dtl_admin_view, dtl_own_data, dtl_service_role
