-- TASK-740 (Phase 1 of the difficulty->tier collapse)
-- =============================================================================
-- CONTEXT
--   Review 2026-08-29 found that "age tier" (topics.target_age_tier, T1-T6,
--   dim_complexity_tiers.id) and "difficulty" (tests.difficulty, 1-9) are two
--   axes sharing the word "tier", bridged by a difficulty_min/max range scan
--   that silently falls back to the full 1-9 schedule on a lookup miss
--   (services/test_generation/orchestrator.py:365-377). That silent fallback
--   is the most likely cause of tests being seeded at an ELO/complexity that
--   doesn't match their topic's nominal age tier.
--
--   Decision: target_age_tier becomes the SOLE level axis for test/question
--   generation and ELO seeding. `tests.difficulty` and the difficulty-keyed
--   config tables are NOT dropped here — other live readers (get_recommended_tests,
--   dictation_max_words(), conversation_generation.categorical_maps,
--   services/dictation/cap.py) still key off tests.difficulty and are out of
--   scope for this pass. They keep working unchanged; this migration is purely
--   additive plus one backfill.
--
-- THIS FILE
--   1. tests.target_age_tier (nullable FK -> dim_complexity_tiers) + backfill
--      from the existing difficulty_min/max band, per operator decision to
--      backfill history rather than go forward-only.
--   2. question_type_distributions_by_tier — a tier-keyed twin of
--      question_type_distributions (which is difficulty-keyed, 1-9). Operator
--      decision: one fixed distribution per tier is acceptable (no per-
--      difficulty sub-bands within a tier), seeded from that difficulty
--      table's T-band representative row so the initial values are unchanged
--      in practice, not re-guessed.
--   3. match_topics_global RPC — topic novelty search across ALL categories
--      (finding #1: a near-duplicate topic sailing through under a different
--      category, e.g. the recurring "cat t-shirt" topic). topics has no
--      language_id column (topics are language-agnostic concepts, translated
--      downstream), so this is a straight category-filter removal, not a
--      language-scoped variant. Additive: match_topics (category-scoped) is
--      left in place for any caller that still wants it.
--
-- Lock-window note (migrations/CLAUDE.md): the tests.target_age_tier backfill
-- is a single UPDATE ... FROM join, no per-value loop, and the new FK/CHECK
-- constraints are added the cheap way (see below) rather than inline in the
-- same ALTER as the column add.
-- =============================================================================

-- ──────────────────────────────────────────────────────────────
-- 1. tests.target_age_tier — nullable now, NOT VALID FK validated separately
-- ──────────────────────────────────────────────────────────────

ALTER TABLE public.tests
  ADD COLUMN IF NOT EXISTS target_age_tier smallint;

COMMENT ON COLUMN public.tests.target_age_tier IS
  'dim_complexity_tiers.id (1-6). Sole level axis going forward for test '
  'generation and ELO seeding — see TASK-740. tests.difficulty is kept for '
  'legacy readers (get_recommended_tests, dictation cap) and is no longer '
  'authoritative for new content.';

-- Backfill from the existing difficulty_min/max band. One pass, CASE-free:
-- a direct range join is cheaper to read than a 6-way CASE and does the same
-- single UPDATE.
UPDATE public.tests t
SET target_age_tier = dct.id
FROM public.dim_complexity_tiers dct
WHERE t.target_age_tier IS NULL
  AND t.difficulty IS NOT NULL
  AND t.difficulty BETWEEN dct.difficulty_min AND dct.difficulty_max;

-- FK added NOT VALID (brief lock, no scan), validated in a separate
-- statement (concurrent-friendly SHARE UPDATE EXCLUSIVE scan).
ALTER TABLE public.tests
  ADD CONSTRAINT tests_target_age_tier_fkey
  FOREIGN KEY (target_age_tier) REFERENCES public.dim_complexity_tiers(id)
  NOT VALID;

ALTER TABLE public.tests
  VALIDATE CONSTRAINT tests_target_age_tier_fkey;

CREATE INDEX IF NOT EXISTS idx_tests_target_age_tier
  ON public.tests(target_age_tier);

-- ──────────────────────────────────────────────────────────────
-- 2. question_type_distributions_by_tier — tier-native question mix
-- ──────────────────────────────────────────────────────────────
-- Operator decision: one fixed distribution per tier (no per-difficulty
-- sub-bands). Seeded from the existing question_type_distributions row at
-- each tier's difficulty_min, so day-1 behavior is unchanged; this table is
-- what services.test_generation.database_client.get_tier_question_distribution
-- (Phase 2) reads instead of scanning question_type_distributions by
-- difficulty.

CREATE TABLE IF NOT EXISTS public.question_type_distributions_by_tier (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tier_id             smallint NOT NULL UNIQUE REFERENCES public.dim_complexity_tiers(id),
    question_type_1     varchar NOT NULL REFERENCES public.dim_question_types(type_code),
    question_type_2     varchar NOT NULL REFERENCES public.dim_question_types(type_code),
    question_type_3     varchar NOT NULL REFERENCES public.dim_question_types(type_code),
    question_type_4     varchar NOT NULL REFERENCES public.dim_question_types(type_code),
    question_type_5     varchar NOT NULL REFERENCES public.dim_question_types(type_code),
    created_at          timestamptz DEFAULT now(),
    updated_at          timestamptz DEFAULT now()
);

COMMENT ON TABLE public.question_type_distributions_by_tier IS
  'Tier-native twin of question_type_distributions (difficulty-keyed, 1-9). '
  'TASK-740: test generation reads this once difficulty is retired as an '
  'axis. One fixed mix per tier — see plan Q3.';

INSERT INTO public.question_type_distributions_by_tier
  (tier_id, question_type_1, question_type_2, question_type_3, question_type_4, question_type_5)
SELECT dct.id,
       qtd.question_type_1, qtd.question_type_2, qtd.question_type_3,
       qtd.question_type_4, qtd.question_type_5
FROM public.dim_complexity_tiers dct
JOIN public.question_type_distributions qtd
  ON qtd.difficulty = dct.difficulty_min
ON CONFLICT (tier_id) DO NOTHING;

-- ──────────────────────────────────────────────────────────────
-- 3. match_topics_global — cross-category novelty search
-- ──────────────────────────────────────────────────────────────
-- Additive: match_topics (category-scoped) is untouched. Finding #1: a
-- near-duplicate topic can sail through as "novel" today because the
-- similarity pool never includes topics from other categories.

CREATE OR REPLACE FUNCTION public.match_topics_global(
    query_embedding vector,
    match_threshold double precision DEFAULT 0.85,
    match_count integer DEFAULT 5
)
RETURNS TABLE(id uuid, concept_english text, category_id integer, similarity double precision)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
BEGIN
    RETURN QUERY
    SELECT
        t.id,
        t.concept_english,
        t.category_id,
        (1 - (t.embedding <=> query_embedding))::FLOAT AS similarity
    FROM topics t
    WHERE t.embedding IS NOT NULL
      AND (1 - (t.embedding <=> query_embedding)) > match_threshold
    ORDER BY t.embedding <=> query_embedding
    LIMIT match_count;
END;
$function$;

-- ──────────────────────────────────────────────────────────────
-- 4. Verification queries (run manually after migration)
-- ──────────────────────────────────────────────────────────────
-- SELECT count(*) FILTER (WHERE target_age_tier IS NULL) AS unbackfilled,
--        count(*) AS total
-- FROM public.tests WHERE difficulty IS NOT NULL;
--
-- SELECT tier_id, question_type_1, question_type_2, question_type_3,
--        question_type_4, question_type_5
-- FROM public.question_type_distributions_by_tier ORDER BY tier_id;
--
-- SELECT * FROM public.match_topics_global(
--   (SELECT embedding FROM topics LIMIT 1), 0.80, 10
-- );
