-- migrations/user_word_watchlist_schema.sql
-- =============================================================================
-- CONTEXT
--   Step 1 of wiki/tasklist/word-list-import.plan.md ("Word List Upload ->
--   Ladder Exposure + Matched Test Queueing", v3). A user uploads a list of
--   words; the system (a) guarantees ladder exposure for each resolved sense
--   and (b) opportunistically boosts any existing/future test whose
--   `tests.vocab_sense_ids` overlaps the user's watchlist into their normal
--   daily recommendation flow, at a level near the user's current tier.
--
--   This table is the durable record connecting an uploaded word (resolved to
--   a `dim_word_senses` row per-user) to: whether ladder exercises have been
--   generated for it yet (Step 3), and the most recent test match found for
--   it (Step 4 immediate sweep / Step 5 recurring sweep cron). It is read by
--   the recurring sweep as: "for every active watchlist row, does any newly
--   created test's vocab_sense_ids include this sense_id?" — a large IN/ANY
--   lookup keyed on sense_id, filtered to active rows only. See the index
--   section below for how that query shape is served.
--
--   THIS FILE IS ADDITIVE ONLY: new table, new indexes, new RLS policies.
--   Nothing existing is altered. No data backfill, so none of the
--   migrations/CLAUDE.md exclusive-lock-window concerns apply (this is a
--   plain CREATE TABLE on a brand-new, empty table) — that guidance is
--   honored here only insofar as no unnecessary long-held locks are
--   introduced.
--
--   FK targets verified by reading migrations/create_all_tables.sql directly
--   (see report to task issuer for exact line numbers / files consulted):
--     - public.users(id)            uuid, PK                  (line ~285-304)
--     - public.dim_word_senses(id)  integer GENERATED ALWAYS AS IDENTITY (line ~350)
--     - public.dim_languages(id)    smallint GENERATED BY DEFAULT AS IDENTITY (line ~37)
--     - public.tests(id)            uuid, PK DEFAULT gen_random_uuid()      (line ~430)
--   `user_id -> public.users(id) ON DELETE CASCADE` matches the convention
--   established as canonical in migrations/fix_daily_test_loads_user_id_fk.sql
--   (public.users, not auth.users; CASCADE so a deleted account's watchlist
--   rows don't dangle). `sense_id`/`language_id` FKs intentionally carry no
--   ON DELETE clause, matching dim_word_senses/dim_languages references
--   elsewhere (e.g. public.user_flashcards, public.user_vocabulary_knowledge
--   in create_all_tables.sql) — these are reference-data tables rows are not
--   expected to be deleted out from under. `last_matched_test_id` also
--   carries no ON DELETE clause, matching the existing nullable
--   `REFERENCES public.tests(id)` columns in create_all_tables.sql (e.g.
--   feedback.test_id, line ~581) rather than inventing a new SET NULL
--   convention.
--
--   Open question carried over from the plan doc (not resolved here): whether
--   a watchlist entry should ever become non-active automatically (e.g. after
--   its first match) or only via explicit user action. No uniqueness
--   constraint on (user_id, sense_id) is added in this migration because that
--   answer determines whether re-upload of an already-watched word should
--   upsert an existing row or always insert a fresh one — that's a Step 3
--   (upload handler) design decision, not a Step 1 schema one. Flagging here
--   so Step 3 doesn't silently allow duplicate active rows per (user, sense)
--   without a deliberate choice.
-- =============================================================================

-- ──────────────────────────────────────────────────────────────
-- 1. user_word_watchlist
-- ──────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.user_word_watchlist (
    id                          bigint      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id                     uuid        NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    sense_id                    integer     NOT NULL REFERENCES public.dim_word_senses(id),
    language_id                 smallint    NOT NULL REFERENCES public.dim_languages(id),
    upload_batch_id             uuid        NOT NULL,
    created_at                  timestamptz NOT NULL DEFAULT now(),
    ladder_exercises_generated  boolean     NOT NULL DEFAULT false,
    last_matched_test_id        uuid        REFERENCES public.tests(id),
    last_matched_at             timestamptz,
    active                      boolean     NOT NULL DEFAULT true
);

COMMENT ON TABLE public.user_word_watchlist IS
  'Word-list upload watchlist (wiki/tasklist/word-list-import.plan.md Step 1). '
  'One row per (user, resolved sense) uploaded via the word-list feature. '
  'ladder_exercises_generated tracks whether Step 3 has ensured ladder '
  'exposure for this sense; last_matched_test_id/last_matched_at record the '
  'most recent test the Step 4/5 sweep boosted into the user''s recommendation '
  'flow for this word. active=false retires a row from future sweeps.';

COMMENT ON COLUMN public.user_word_watchlist.upload_batch_id IS
  'Groups all rows created from a single word-list submission (one uuid per '
  'POST /api/word-list/submit call, shared across all resolved words in it). '
  'Not a foreign key — no separate upload-batch table exists.';

COMMENT ON COLUMN public.user_word_watchlist.active IS
  'Whether this word is still eligible for the recurring match sweep (Step '
  '5). See open question in the file header re: auto-retirement.';

-- ──────────────────────────────────────────────────────────────
-- 2. Indexes
-- ──────────────────────────────────────────────────────────────

-- Foreign keys are always indexed in this schema, independent of the sweep
-- query below (referential-integrity scans and any future per-user/per-
-- language/per-batch listing queries need these regardless of `active`).
CREATE INDEX IF NOT EXISTS idx_user_word_watchlist_user_id
  ON public.user_word_watchlist(user_id);

CREATE INDEX IF NOT EXISTS idx_user_word_watchlist_language_id
  ON public.user_word_watchlist(language_id);

CREATE INDEX IF NOT EXISTS idx_user_word_watchlist_upload_batch_id
  ON public.user_word_watchlist(upload_batch_id);

-- last_matched_test_id is nullable and sparse (NULL until a sweep finds a
-- match) — partial index so unmatched rows (the common case, especially
-- right after upload) don't bloat it.
CREATE INDEX IF NOT EXISTS idx_user_word_watchlist_last_matched_test_id
  ON public.user_word_watchlist(last_matched_test_id)
  WHERE last_matched_test_id IS NOT NULL;

-- General sense_id index for lookups/joins that are not scoped to
-- active = true (e.g. admin/debug queries, referential lookups).
CREATE INDEX IF NOT EXISTS idx_user_word_watchlist_sense_id
  ON public.user_word_watchlist(sense_id);

-- The sweep-query index. Step 4/5 sweep shape is:
--   SELECT ... FROM user_word_watchlist
--   WHERE active = true AND sense_id = ANY(:matched_sense_ids)
-- A single partial index on sense_id, scoped to active = true, serves this
-- exactly: it is both "an index on sense_id" and "an index on active" in one
-- structure (smaller than a full index since retired rows are excluded, and
-- the planner needs no separate bitmap AND of two indexes to satisfy the
-- query). Mirrors the `WHERE is_active = TRUE` partial-index convention used
-- elsewhere in this repo (see migrations/create_all_tables.sql
-- idx_exercises_active, migrations/conversation_generation_tables.sql
-- idx_conv_active, etc.).
CREATE INDEX IF NOT EXISTS idx_user_word_watchlist_active_sense_id
  ON public.user_word_watchlist(sense_id)
  WHERE active = true;

-- ──────────────────────────────────────────────────────────────
-- 3. Row Level Security
-- ──────────────────────────────────────────────────────────────
-- Standard own-data + service-role + admin-view triple, matching the pattern
-- applied to every other user-owning table in
-- migrations/enable_rls_on_user_owned_tables.sql. The application accesses
-- this table exclusively via the service-role client (get_supabase_admin())
-- per that migration's stated pattern, so this is a future-proofing measure
-- for any direct anon-client access, not a behavior change for Step 3/4/5/7
-- code paths.

ALTER TABLE public.user_word_watchlist ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS uww_own_data ON public.user_word_watchlist;
CREATE POLICY uww_own_data ON public.user_word_watchlist
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS uww_service_role ON public.user_word_watchlist;
CREATE POLICY uww_service_role ON public.user_word_watchlist
  FOR ALL
  USING (auth.role() = 'service_role');

DROP POLICY IF EXISTS uww_admin_view ON public.user_word_watchlist;
CREATE POLICY uww_admin_view ON public.user_word_watchlist
  FOR SELECT
  USING (is_admin(auth.uid()));

-- ──────────────────────────────────────────────────────────────
-- 4. Rollback (commented — not executed by this file)
-- ──────────────────────────────────────────────────────────────
-- DROP POLICY IF EXISTS uww_admin_view    ON public.user_word_watchlist;
-- DROP POLICY IF EXISTS uww_service_role  ON public.user_word_watchlist;
-- DROP POLICY IF EXISTS uww_own_data      ON public.user_word_watchlist;
-- DROP TABLE IF EXISTS public.user_word_watchlist;

-- ──────────────────────────────────────────────────────────────
-- 5. Verification queries (run manually after migration — not executed here)
-- ──────────────────────────────────────────────────────────────
-- -- Table + columns exist with expected types:
-- SELECT column_name, data_type, is_nullable, column_default
-- FROM information_schema.columns
-- WHERE table_schema = 'public' AND table_name = 'user_word_watchlist'
-- ORDER BY ordinal_position;
--
-- -- FKs point at the verified targets:
-- SELECT conname, pg_get_constraintdef(oid)
-- FROM pg_constraint
-- WHERE conrelid = 'public.user_word_watchlist'::regclass AND contype = 'f';
--
-- -- All 6 indexes present, with the sweep index correctly scoped:
-- SELECT indexname, indexdef
-- FROM pg_indexes
-- WHERE schemaname = 'public' AND tablename = 'user_word_watchlist'
-- ORDER BY indexname;
--
-- -- RLS enabled with exactly the 3 expected policies:
-- SELECT rowsecurity FROM pg_tables
-- WHERE schemaname = 'public' AND tablename = 'user_word_watchlist';
--
-- SELECT policyname FROM pg_policies
-- WHERE schemaname = 'public' AND tablename = 'user_word_watchlist'
-- ORDER BY policyname;
--
-- -- Sweep query plan sanity check (should hit
-- -- idx_user_word_watchlist_active_sense_id via Index Scan/Bitmap Index Scan,
-- -- not a Seq Scan):
-- EXPLAIN ANALYZE
-- SELECT * FROM public.user_word_watchlist
-- WHERE active = true AND sense_id = ANY(ARRAY[1,2,3]::integer[]);
