"""
Recurring watchlist match-sweep — word-list-import Step 5.

Scheduled (once wired — see below) to run periodically across ALL languages
and ALL active `user_word_watchlist` rows, so a word with zero matching tests
at upload time (Step 4's immediate sweep) still surfaces one the day a
matching test gets generated by the normal daily rotation. Reuses Step 4's
write-side engine, `services.word_list_import.match_sweep.
sweep_immediate_matches`, unmodified — its own docstring/tests already
establish it is agnostic to the freshness of the watchlist rows it is handed.

This module's job is narrower than "run the matcher": it is the *candidate
finder* that keeps a recurring sweep affordable. Without it, every run would
have to check every active watchlist row against every test in the system.
Instead:

    1. Read a watermark (`word_upload_sweep_state.last_swept_created_at`) of
       the newest `tests.created_at` already scanned by a prior run.
    2. Fetch only `tests` rows created strictly after that watermark.
    3. Collect the union of their `vocab_sense_ids`.
    4. Fetch only `user_word_watchlist` rows that are `active = true` AND
       whose `sense_id` is in that set.
    5. Hand exactly that (usually tiny) candidate list to
       `sweep_immediate_matches`, which does the real ELO-aware matching and
       writes `last_matched_test_id`/`last_matched_at`.
    6. Advance the watermark.

This is a "new tests -> which watchlist rows might care" query, not the
reverse ("every watchlist row -> scan all tests") — the reverse would defeat
the point of the watermark, since the size of `user_word_watchlist` has
nothing to do with how many tests were created since the last run.

Advisory lock
-------------
Cross-worker mutex (APScheduler runs in every gunicorn worker; only the
lock-holder does the sweep), matching the exact skip semantics of
`services.study_plan_service._try_advisory_lock`/`_release_advisory_lock`:
best-effort, ``db.rpc(<lock_rpc>, {}).execute()`` wrapping a fixed advisory
key (migrations/word_upload_sweep_advisory_lock.sql, key 'WUSw'), and if the
RPC itself errors (e.g. the migration is not deployed yet in some
environment) this FALLS THROUGH TO True rather than refusing to run — a
misconfigured environment should still sweep (at worst paying for redundant
cross-worker duplicate work, which `sweep_immediate_matches`' writes are
idempotent against), not silently never sweep at all. Released in a
``finally`` on the same connection.

Cursor / watermark semantics and the clock-skew choice
-------------------------------------------------------
`tests.id` is a random UUID (see migrations/create_all_tables.sql), not a
sortable sequence, so the watermark MUST be `tests.created_at` — there is no
ID-based alternative available anywhere else in this repo to copy.

The new watermark value is always the **MAX(created_at) of the tests batch
this run actually fetched**, never wall-clock `now()`. Rationale: a value we
actually observed in a committed, visible row can never be later than
reality. An optimistic `now()` captured at request time CAN be later than
reality in the presence of an in-flight transaction — e.g. a test-generation
worker's `INSERT INTO tests (...) VALUES (..., now())` that assigns its
`created_at` a few milliseconds before our sweep's `now()` snapshot, but does
not COMMIT (and therefore is not visible to our SELECT) until after we have
already advanced the watermark past it. Under `now()`-based advancement, that
row's `created_at` would then be <= our new watermark forever, and it would
never be scanned by any future run. Under MAX(observed)-based advancement,
the same race is *reduced but not eliminated* (the watermark can still land
between an in-flight transaction's future `created_at` and its still-pending
commit) — there is no query-side timestamp cursor that fully closes this gap
without a sequence/LSN-based key, which is not available here. This module
therefore accepts the same residual risk every `created_at`-only "since last
run" cursor in this codebase's design space would carry (no stronger
precedent exists to copy — see the migration file's header for what was
checked), and leans on `sweep_immediate_matches` being safe to re-run (a
reaffirmed match is a no-op past a timestamp bump) as the mitigation of last
resort should a row need to be caught by a later, broader pass.

A run that finds **zero** new tests since the watermark is a cheap no-op: it
never queries `user_word_watchlist` at all, and never advances the watermark
(there is nothing new to advance it to).
"""

import logging
from datetime import datetime, timezone

from services.word_list_import.match_sweep import sweep_immediate_matches

logger = logging.getLogger(__name__)

_LOCK_RPC = 'pg_try_advisory_lock_for_word_upload_sweep'
_UNLOCK_RPC = 'pg_advisory_unlock_for_word_upload_sweep'

_CURSOR_TABLE = 'word_upload_sweep_state'
_CURSOR_ROW_ID = 1
_CURSOR_COLUMN = 'last_swept_created_at'


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


# ---------------------------------------------------------------------------
# Advisory lock — exact shape of study_plan_service._try_advisory_lock /
# _release_advisory_lock, retargeted at this cron's own RPC names/key.
# ---------------------------------------------------------------------------


def _try_advisory_lock(db) -> bool:
    """Best-effort cross-worker mutex for the word-upload watchlist sweep.

    Wraps the dedicated advisory-lock key (key 'WUSw', see
    migrations/word_upload_sweep_advisory_lock.sql). Same shape as
    services.study_plan_service._try_advisory_lock: falls through to True if
    the RPC itself errors (e.g. not yet deployed) so a misconfigured
    environment still runs the sweep — sweep_immediate_matches' writes are
    idempotent, so the only cost of a rare double-run is ~2x compute.
    """
    try:
        resp = db.rpc(_LOCK_RPC, {}).execute()
        data = resp.data
        if isinstance(data, list) and data:
            return bool(data[0])
        if data is not None:
            return bool(data)
    except Exception as exc:
        logger.warning(
            'Word-upload sweep advisory lock unavailable, proceeding without it: %s',
            exc,
        )
    return True


def _release_advisory_lock(db) -> None:
    try:
        db.rpc(_UNLOCK_RPC, {}).execute()
    except Exception as exc:
        logger.warning('Word-upload sweep advisory unlock failed: %s', exc)


# ---------------------------------------------------------------------------
# Cursor read/advance
# ---------------------------------------------------------------------------


def _read_cursor(db):
    """Return the current watermark string, or None if the singleton row is
    somehow missing (e.g. migration not yet applied in this environment) —
    callers treat None as "scan everything", the same fail-open posture the
    advisory lock takes."""
    resp = (
        db.table(_CURSOR_TABLE)
        .select(_CURSOR_COLUMN)
        .eq('id', _CURSOR_ROW_ID)
        .execute()
    )
    rows = resp.data or []
    if not rows:
        return None
    return rows[0].get(_CURSOR_COLUMN)


def _advance_cursor(db, new_value: str) -> None:
    db.table(_CURSOR_TABLE).update({
        _CURSOR_COLUMN: new_value,
        'updated_at': _now_iso(),
    }).eq('id', _CURSOR_ROW_ID).execute()


# ---------------------------------------------------------------------------
# Candidate-finding
# ---------------------------------------------------------------------------


def _fetch_tests_since(db, cursor) -> list:
    """Tests created strictly after `cursor`. `cursor=None` fetches every
    test (bootstrap case — the watermark row is missing)."""
    query = db.table('tests').select('id, created_at, vocab_sense_ids')
    if cursor:
        query = query.gt('created_at', cursor)
    resp = query.execute()
    return resp.data or []


def _extract_sense_ids(tests: list) -> set:
    sense_ids = set()
    for t in tests:
        for sid in (t.get('vocab_sense_ids') or []):
            sense_ids.add(sid)
    return sense_ids


def _max_created_at(tests: list) -> str:
    """Max of the batch's `created_at` strings. Left as raw ISO-8601 strings
    (no datetime parsing) — they all came from the same column of the same
    query, so string ordering agrees with chronological ordering, and the
    value is only ever fed back into another `.gt('created_at', ...)` filter
    Postgres parses itself; there is nothing to gain from round-tripping it
    through Python `datetime` in between."""
    return max(t['created_at'] for t in tests)


def _fetch_active_watchlist_rows_for_senses(db, sense_ids: set) -> list:
    """Active watchlist rows whose sense_id is one of `sense_ids`. Returns
    `[]` immediately (no query at all) if `sense_ids` is empty, so "new tests
    exist but none of them use any watched sense" stays cheap too."""
    if not sense_ids:
        return []
    resp = (
        db.table('user_word_watchlist')
        .select('id, user_id, sense_id, language_id, last_matched_test_id')
        .eq('active', True)
        .in_('sense_id', list(sense_ids))
        .execute()
    )
    return resp.data or []


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def run_watchlist_sweep(db_client) -> dict:
    """Cron entry point for the recurring watchlist match-sweep (Step 5).

    Args:
        db_client: Either a Supabase client directly (exposes `.table(...)`/
            `.rpc(...)`) or a duck-typed wrapper exposing `.client` for the
            underlying Supabase client — same flexibility
            `sweep_immediate_matches` and the rest of this feature's modules
            already assume.

    Returns:
        On lock contention:
            {'skipped': True, 'reason': 'lock_held'}
        On no new tests since the watermark:
            {
                'skipped': False,
                'no_new_tests': True,
                'sweep': None,
            }
        On a normal pass (including "new tests found, but none matched any
        active watchlist row's sense" — `sweep` is None in that sub-case too,
        since sweep_immediate_matches was never called):
            {
                'skipped': False,
                'no_new_tests': False,
                'new_tests_found': int,
                'sweep': <sweep_immediate_matches(...) return value> | None,
            }

    Never raises for expected conditions (lock held, no new tests, no
    matching watchlist rows) — those are reported via the return value, not
    exceptions. Per-row failures inside the actual match are already
    contained by `sweep_immediate_matches` itself.
    """
    db = db_client.client if hasattr(db_client, 'client') else db_client

    if not _try_advisory_lock(db):
        logger.info(
            'Word-upload watchlist sweep: another worker holds the lock; skipping.',
        )
        return {'skipped': True, 'reason': 'lock_held'}

    try:
        cursor = _read_cursor(db)
        new_tests = _fetch_tests_since(db, cursor)

        if not new_tests:
            logger.info('Word-upload watchlist sweep: no new tests since %s.', cursor)
            return {'skipped': False, 'no_new_tests': True, 'sweep': None}

        sense_ids = _extract_sense_ids(new_tests)
        watchlist_rows = _fetch_active_watchlist_rows_for_senses(db, sense_ids)

        sweep_result = None
        if watchlist_rows:
            sweep_result = sweep_immediate_matches(watchlist_rows, db)

        # Advance the watermark regardless of whether anything matched —
        # these tests have now been SCANNED, which is all the watermark
        # tracks. Not advancing here would make every future run re-scan the
        # same tests forever whenever they happen not to touch any watched
        # sense, defeating the point of the watermark.
        new_cursor = _max_created_at(new_tests)
        _advance_cursor(db, new_cursor)

        logger.info(
            'Word-upload watchlist sweep: %d new test(s) since %s, '
            '%d candidate watchlist row(s), cursor -> %s.',
            len(new_tests), cursor, len(watchlist_rows), new_cursor,
        )
        return {
            'skipped': False,
            'no_new_tests': False,
            'new_tests_found': len(new_tests),
            'sweep': sweep_result,
        }
    finally:
        _release_advisory_lock(db)
